In [1]:
#Load packages required for loading the npy files.
import numpy as np
import pandas as pd

# #Load the npy file called "data.npy"
Initial_input_data = np.load("/Users/mayukotakamiya/MachineLearning/initial_data/function_3/initial_inputs.npy")
Initial_output_data = np.load("/Users/mayukotakamiya/MachineLearning/initial_data/function_3/initial_outputs.npy")

#I want to know dimentionality of the initial_input_data  
Initial_input_data.shape




(15, 3)

In [2]:

# X and y already loaded
X = Initial_input_data
y = Initial_output_data

def propose_next_point(X, y, n_candidates=8000, w_exploit=0.6, w_explore=0.4, seed=42):
    """
    Simple explore/exploit heuristic:
    - exploit: sample near best observed point
    - explore: sample far from existing samples
    """

    rng = np.random.default_rng(seed)
    n, d = X.shape

    # Best observed point so far
    best_x = X[np.argmax(y)]

    # Determine sampling bounds from existing data
    lower_bounds = X.min(axis=0)
    upper_bounds = X.max(axis=0)

    # Generate random candidate points within observed bounds
    C = rng.uniform(lower_bounds, upper_bounds, size=(n_candidates, d))

    # Exploitation term (closer to best is better)
    dist_to_best = np.linalg.norm(C - best_x, axis=1)
    exploit = 1 - (dist_to_best / (dist_to_best.max() + 1e-12))

    # Exploration term (farther from existing points is better)
    dists = np.sqrt(((C[:, None, :] - X[None, :, :]) ** 2).sum(axis=2))
    min_dist = dists.min(axis=1)
    explore = min_dist / (min_dist.max() + 1e-12)

    # Combined score
    score = w_exploit * exploit + w_explore * explore

    return C[np.argmax(score)]

def format_query(x):
    return "-".join([f"{v:0.6f}" for v in x])

# Generate next query
next_x = propose_next_point(X, y)

print("Submit this to the portal:")
print(format_query(next_x))

Submit this to the portal:
0.145970-0.921486


In [2]:
###WEEK 2
#I want to see the data in /Users/mayukotakamiya/MachineLearning/initial_data/function_1/initial_inputs.npy
print(Initial_input_data)
#I WANT TO create a new npy file by adding a new data point which is [0.433534 0.458467]
new_data_point = np.array([[00.472953, 0.893937, 0.789355]])
Combined_input_data = np.concatenate((Initial_input_data, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_3/W2_inputs.npy", Combined_input_data)
print(Combined_input_data)

[[0.17152521 0.34391687 0.2487372 ]
 [0.24211446 0.64407427 0.27243281]
 [0.53490572 0.39850092 0.17338873]
 [0.49258141 0.61159319 0.34017639]
 [0.13462167 0.21991724 0.45820622]
 [0.34552327 0.94135983 0.26936348]
 [0.15183663 0.43999062 0.99088187]
 [0.64550284 0.39714294 0.91977134]
 [0.74691195 0.28419631 0.22629985]
 [0.17047699 0.6970324  0.14916943]
 [0.22054934 0.29782524 0.34355534]
 [0.66601366 0.67198515 0.2462953 ]
 [0.04680895 0.23136024 0.77061759]
 [0.60009728 0.72513573 0.06608864]
 [0.96599485 0.86111969 0.56682913]]
[[0.17152521 0.34391687 0.2487372 ]
 [0.24211446 0.64407427 0.27243281]
 [0.53490572 0.39850092 0.17338873]
 [0.49258141 0.61159319 0.34017639]
 [0.13462167 0.21991724 0.45820622]
 [0.34552327 0.94135983 0.26936348]
 [0.15183663 0.43999062 0.99088187]
 [0.64550284 0.39714294 0.91977134]
 [0.74691195 0.28419631 0.22629985]
 [0.17047699 0.6970324  0.14916943]
 [0.22054934 0.29782524 0.34355534]
 [0.66601366 0.67198515 0.2462953 ]
 [0.04680895 0.23136024 0.7

In [3]:
print(Initial_output_data)

#I want to create a new npy file bt adding a new data point to the Initial_output_data
new_output_data_point = np.array([-0.12536482360928636])
Combined_output_data = np.concatenate((Initial_output_data, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_3/W2_outputs.npy", Combined_output_data)

print(Combined_output_data)

[-0.1121222  -0.08796286 -0.11141465 -0.03483531 -0.04800758 -0.11062091
 -0.39892551 -0.11386851 -0.13146061 -0.09418956 -0.04694741 -0.10596504
 -0.11804826 -0.03637783 -0.05675837]
[-0.1121222  -0.08796286 -0.11141465 -0.03483531 -0.04800758 -0.11062091
 -0.39892551 -0.11386851 -0.13146061 -0.09418956 -0.04694741 -0.10596504
 -0.11804826 -0.03637783 -0.05675837 -0.12536482]


In [87]:
#Assess the exploitation vs exploration strategy
x=Combined_input_data
y=Combined_output_data

best_score_w2= np.max(y)
improvement= best_score_w2 - np.max(Initial_output_data)

print("Improvement:", improvement)
print("Output range:", y.min(), "to", y.max())
print("Std deviation:", np.std(y))


Improvement: 0.007087524491951498
Output range: -0.0036060626443634764 to 0.007087524491952269
Std deviation: 0.002376682573738607


In [ ]:
##Function1- For week2, it seems there is a big improvement by having the improvement more than 10% of the output range. Therefore, more exploitation than exploration.
##Function2- For week2, no improvement at all. Therefore use more exploration than exploitation
##Function3- for week2, no improvement at all.Therefore use more exploration than exploitation. 
##Function4- for week2, no improvement at all.Therefore use more exploration than exploitation. 
##Function5- for week2, no improvement at all.Therefore use more exploration than exploitation. 
##Function6- for week2, no improvement at all.Therefore use more exploration than exploitation. 
##Function7- for week2, no improvement at all.Therefore use more exploration than exploitation. 
#Function8- for week2, there is small-moderate improvement. Take a balanced approach (6:4)

In [88]:
#Re-run the loop
X=Combined_input_data
y=Combined_output_data

def propose_next_point(X, y, n_candidates=8000, w_exploit=0.75, w_explore=0.25, seed=234):
    """
    Simple explore/exploit heuristic:
    - exploit: sample near best observed point
    - explore: sample far from existing samples
    """

    rng = np.random.default_rng(seed)
    n, d = X.shape

    # Best observed point so far
    best_x = X[np.argmax(y)]
    
    radius = 0.05  # small local refinement

    # Determine sampling bounds from existing data
    lower = np.maximum(best_x - radius, X.min(axis=0))
    upper = np.minimum(best_x + radius, X.max(axis=0))


    # Generate random candidate points within observed bounds
    C = rng.uniform(lower, upper, size=(n_candidates, d))

    # Exploitation term (closer to best is better)
    dist_to_best = np.linalg.norm(C - best_x, axis=1)
    exploit = 1 - (dist_to_best / (dist_to_best.max() + 1e-12))

    # Exploration term (farther from existing points is better)
    dists = np.sqrt(((C[:, None, :] - X[None, :, :]) ** 2).sum(axis=2))
    min_dist = dists.min(axis=1)
    explore = min_dist / (min_dist.max() + 1e-12)

    # Combined score
    score = w_exploit * exploit + w_explore * explore

    return C[np.argmax(score)]

def format_query(x):
    return "-".join([f"{v:0.6f}" for v in x])

# Generate next query
next_x = propose_next_point(X, y)

print("Submit this to the portal:")
print(format_query(next_x))

Submit this to the portal:
0.433582-0.457940


In [4]:
####WEEK 3
new_data_point = np.array([[0.446509, 0.561763, 0.389215]])
Combined_input_data3 = np.concatenate((Combined_input_data, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_3/W3_inputs.npy", Combined_input_data3)
print(Combined_input_data3)

new_output_data_point = np.array([-0.009616998691595194])
Combined_output_data3 = np.concatenate((Combined_output_data, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_3/W3_outputs.npy", Combined_output_data3)

print(Combined_output_data3)


[[0.17152521 0.34391687 0.2487372 ]
 [0.24211446 0.64407427 0.27243281]
 [0.53490572 0.39850092 0.17338873]
 [0.49258141 0.61159319 0.34017639]
 [0.13462167 0.21991724 0.45820622]
 [0.34552327 0.94135983 0.26936348]
 [0.15183663 0.43999062 0.99088187]
 [0.64550284 0.39714294 0.91977134]
 [0.74691195 0.28419631 0.22629985]
 [0.17047699 0.6970324  0.14916943]
 [0.22054934 0.29782524 0.34355534]
 [0.66601366 0.67198515 0.2462953 ]
 [0.04680895 0.23136024 0.77061759]
 [0.60009728 0.72513573 0.06608864]
 [0.96599485 0.86111969 0.56682913]
 [0.472953   0.893937   0.789355  ]
 [0.446509   0.561763   0.389215  ]]
[-0.1121222  -0.08796286 -0.11141465 -0.03483531 -0.04800758 -0.11062091
 -0.39892551 -0.11386851 -0.13146061 -0.09418956 -0.04694741 -0.10596504
 -0.11804826 -0.03637783 -0.05675837 -0.12536482 -0.009617  ]


In [5]:
#WEEK 3 Assess the exploitation vs exploration strategy
x=Combined_input_data3
y=Combined_output_data3

best_score_w2= np.max(y)
improvement= best_score_w2 - np.max(Combined_output_data)

print("Improvement:", improvement)
print("Output range:", y.min(), "to", y.max())
print("Std deviation:", np.std(y))

Improvement: 0.02521831465848339
Output range: -0.3989255131463011 to -0.009616998691595194
Std deviation: 0.08255362343217516


In [8]:
#WEEK 3 -re run the loop. moderate improvement so adjust exploit vs explore ratio to 0.6: 0.4
X=Combined_input_data3
y=Combined_output_data3

def propose_next_point(X, y, n_candidates=8000, w_exploit=0.6, w_explore=0.4, seed=234):

    rng = np.random.default_rng(seed)
    n, d = X.shape

    # Best observed point so far
    best_x = X[np.argmax(y)]
    
    radius = 0.05  # small local refinement

    # Determine sampling bounds from existing data
    lower = np.maximum(best_x - radius, X.min(axis=0))
    upper = np.minimum(best_x + radius, X.max(axis=0))


    # Generate random candidate points within observed bounds
    C = rng.uniform(lower, upper, size=(n_candidates, d))

    # Exploitation term (closer to best is better)
    dist_to_best = np.linalg.norm(C - best_x, axis=1)
    exploit = 1 - (dist_to_best / (dist_to_best.max() + 1e-12))

    # Exploration term (farther from existing points is better)
    dists = np.sqrt(((C[:, None, :] - X[None, :, :]) ** 2).sum(axis=2))
    min_dist = dists.min(axis=1)
    explore = min_dist / (min_dist.max() + 1e-12)

    # Combined score
    score = w_exploit * exploit + w_explore * explore

    return C[np.argmax(score)]

def format_query(x):
    return "-".join([f"{v:0.6f}" for v in x])

# Generate next query
next_x = propose_next_point(X, y)

print("Submit this to the portal:")
print(format_query(next_x))

Submit this to the portal:
0.442990-0.561225-0.390190


In [9]:
####WEEK 4
new_data_point = np.array([[00.442990, 0.561225, 0.390190]])
Combined_input_data4 = np.concatenate((Combined_input_data3, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_3/W4_inputs.npy", Combined_input_data4)
print(Combined_input_data4)

new_output_data_point = np.array([-0.01954880502773955])
Combined_output_data4 = np.concatenate((Combined_output_data3, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_3/W4_outputs.npy", Combined_output_data4)

print(Combined_output_data4)

[[0.17152521 0.34391687 0.2487372 ]
 [0.24211446 0.64407427 0.27243281]
 [0.53490572 0.39850092 0.17338873]
 [0.49258141 0.61159319 0.34017639]
 [0.13462167 0.21991724 0.45820622]
 [0.34552327 0.94135983 0.26936348]
 [0.15183663 0.43999062 0.99088187]
 [0.64550284 0.39714294 0.91977134]
 [0.74691195 0.28419631 0.22629985]
 [0.17047699 0.6970324  0.14916943]
 [0.22054934 0.29782524 0.34355534]
 [0.66601366 0.67198515 0.2462953 ]
 [0.04680895 0.23136024 0.77061759]
 [0.60009728 0.72513573 0.06608864]
 [0.96599485 0.86111969 0.56682913]
 [0.472953   0.893937   0.789355  ]
 [0.446509   0.561763   0.389215  ]
 [0.44299    0.561225   0.39019   ]]
[-0.1121222  -0.08796286 -0.11141465 -0.03483531 -0.04800758 -0.11062091
 -0.39892551 -0.11386851 -0.13146061 -0.09418956 -0.04694741 -0.10596504
 -0.11804826 -0.03637783 -0.05675837 -0.12536482 -0.009617   -0.01954881]


In [10]:
#WEEK 4 - apply small neural network surrogate

import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPRegressor

# -------------------------------------------------
# 1. Load your current dataset (updated with last query)
# -------------------------------------------------

X = Combined_input_data4
y = Combined_output_data4

# -------------------------------------------------
# 2. Scale inputs (important for neural networks)
# -------------------------------------------------

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# -------------------------------------------------
# 3. Train a small neural network surrogate
# -------------------------------------------------

model = MLPRegressor(
    hidden_layer_sizes=(16,8),   # small network
    activation='relu',
    solver='adam',
    max_iter=1000,
    random_state=42
)

model.fit(X_scaled, y)

# -------------------------------------------------
# 4. Generate candidate points in the search space
# -------------------------------------------------

rng = np.random.default_rng(42)

lower = X.min(axis=0)
upper = X.max(axis=0)

candidates = rng.uniform(lower, upper, size=(5000, X.shape[1]))

# -------------------------------------------------
# 5. Predict output for candidates
# -------------------------------------------------

candidates_scaled = scaler.transform(candidates)

predictions = model.predict(candidates_scaled)

# -------------------------------------------------
# 6. Select best predicted candidate
# -------------------------------------------------

best_idx = np.argmax(predictions)

next_query = candidates[best_idx]

# -------------------------------------------------
# 7. Format for portal submission
# -------------------------------------------------

query_string = "-".join([f"{v:0.6f}" for v in next_query])

print("Next query:")
print(query_string)

Next query:
0.931079-0.729861-0.986877


In [11]:
#WEEK 5 
new_data_point = np.array([[0.931079, 0.729861, 0.986877]])
Combined_input_data5 = np.concatenate((Combined_input_data4, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_3/W5_inputs.npy", Combined_input_data5)
print(Combined_input_data5)

new_output_data_point = np.array([-0.37693289753014825])
Combined_output_data5 = np.concatenate((Combined_output_data4, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_3/W5_outputs.npy", Combined_output_data5)

print(Combined_output_data5)

[[0.17152521 0.34391687 0.2487372 ]
 [0.24211446 0.64407427 0.27243281]
 [0.53490572 0.39850092 0.17338873]
 [0.49258141 0.61159319 0.34017639]
 [0.13462167 0.21991724 0.45820622]
 [0.34552327 0.94135983 0.26936348]
 [0.15183663 0.43999062 0.99088187]
 [0.64550284 0.39714294 0.91977134]
 [0.74691195 0.28419631 0.22629985]
 [0.17047699 0.6970324  0.14916943]
 [0.22054934 0.29782524 0.34355534]
 [0.66601366 0.67198515 0.2462953 ]
 [0.04680895 0.23136024 0.77061759]
 [0.60009728 0.72513573 0.06608864]
 [0.96599485 0.86111969 0.56682913]
 [0.472953   0.893937   0.789355  ]
 [0.446509   0.561763   0.389215  ]
 [0.44299    0.561225   0.39019   ]
 [0.931079   0.729861   0.986877  ]]
[-0.1121222  -0.08796286 -0.11141465 -0.03483531 -0.04800758 -0.11062091
 -0.39892551 -0.11386851 -0.13146061 -0.09418956 -0.04694741 -0.10596504
 -0.11804826 -0.03637783 -0.05675837 -0.12536482 -0.009617   -0.01954881
 -0.3769329 ]


In [12]:
##WEEK 5 - Neural network surrogate (to capture nonlinear structure), Gradient-inspired refinement (move toward promising directions), 
# Candidate search (to remain stable with small data)


X = Combined_input_data5
y = Combined_output_data5

print("Dataset shape:", X.shape)

# -------------------------------------------------
# 2. Scale inputs
# -------------------------------------------------

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# -------------------------------------------------
# 3. Train neural network surrogate
# -------------------------------------------------

model = MLPRegressor(
    hidden_layer_sizes=(16, 8),
    activation="relu",
    solver="adam",
    max_iter=2000,
    random_state=42
)

model.fit(X_scaled, y)

# -------------------------------------------------
# 4. Identify best point
# -------------------------------------------------

best_idx = np.argmax(y)
best_x = X[best_idx]

# -------------------------------------------------
# 5. Generate candidate points
# -------------------------------------------------

rng = np.random.default_rng(42)

lower = X.min(axis=0)
upper = X.max(axis=0)

# Local candidates around best point (refinement)
local_candidates = rng.normal(loc=best_x, scale=0.05, size=(3000, 3))
local_candidates = np.clip(local_candidates, lower, upper)

# Global candidates (exploration)
global_candidates = rng.uniform(lower, upper, size=(3000, 3))

# Combine
candidates = np.vstack([local_candidates, global_candidates])

# -------------------------------------------------
# 6. Remove near-duplicate candidates
# -------------------------------------------------

dist = np.sqrt(((candidates[:, None, :] - X[None, :, :])**2).sum(axis=2))
min_dist = dist.min(axis=1)

mask = min_dist > 0.01
candidates = candidates[mask]
min_dist = min_dist[mask]

# -------------------------------------------------
# 7. Predict outputs
# -------------------------------------------------

candidates_scaled = scaler.transform(candidates)
predictions = model.predict(candidates_scaled)

# -------------------------------------------------
# 8. Add exploration bonus
# -------------------------------------------------

explore_score = min_dist / (min_dist.max() + 1e-12)

# Balanced score (slightly exploit-leaning)
score = predictions + 0.1 * explore_score

# -------------------------------------------------
# 9. Select next query
# -------------------------------------------------

next_query = candidates[np.argmax(score)]

# -------------------------------------------------
# 10. Format for portal
# -------------------------------------------------

query_string = "-".join([f"{v:0.6f}" for v in next_query])

print("Next query:")
print(query_string)

Dataset shape: (19, 3)
Next query:
0.051678-0.575402-0.458200


In [13]:
#WEEK 6
new_data_point = np.array([[0.931079, 0.729861, 0.986877]])
Combined_input_data6 = np.concatenate((Combined_input_data5, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_3/W6_inputs.npy", Combined_input_data6)
print(Combined_input_data6)

new_output_data_point = np.array([-0.37693289753014825])
Combined_output_data6 = np.concatenate((Combined_output_data5, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_3/W6_outputs.npy", Combined_output_data6)

print(Combined_output_data6)

[[0.17152521 0.34391687 0.2487372 ]
 [0.24211446 0.64407427 0.27243281]
 [0.53490572 0.39850092 0.17338873]
 [0.49258141 0.61159319 0.34017639]
 [0.13462167 0.21991724 0.45820622]
 [0.34552327 0.94135983 0.26936348]
 [0.15183663 0.43999062 0.99088187]
 [0.64550284 0.39714294 0.91977134]
 [0.74691195 0.28419631 0.22629985]
 [0.17047699 0.6970324  0.14916943]
 [0.22054934 0.29782524 0.34355534]
 [0.66601366 0.67198515 0.2462953 ]
 [0.04680895 0.23136024 0.77061759]
 [0.60009728 0.72513573 0.06608864]
 [0.96599485 0.86111969 0.56682913]
 [0.472953   0.893937   0.789355  ]
 [0.446509   0.561763   0.389215  ]
 [0.44299    0.561225   0.39019   ]
 [0.931079   0.729861   0.986877  ]
 [0.931079   0.729861   0.986877  ]]
[-0.1121222  -0.08796286 -0.11141465 -0.03483531 -0.04800758 -0.11062091
 -0.39892551 -0.11386851 -0.13146061 -0.09418956 -0.04694741 -0.10596504
 -0.11804826 -0.03637783 -0.05675837 -0.12536482 -0.009617   -0.01954881
 -0.3769329  -0.3769329 ]


In [14]:
##WEEK 6 
#Use a small neural network surrogate
#Combine:
#local refinement (around best)
#global exploration
#Add exploration bonus
#Keep architecture simple (avoid overfitting)

import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPRegressor

# -------------------------------------------------
# 1. Load dataset
# -------------------------------------------------

X = Combined_input_data6
y = Combined_output_data6

print("Dataset shape:", X.shape)

# -------------------------------------------------
# 2. Scale inputs
# -------------------------------------------------

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# -------------------------------------------------
# 3. Train neural network surrogate (small model)
# -------------------------------------------------

model = MLPRegressor(
    hidden_layer_sizes=(16, 8),   # small network
    activation="relu",
    solver="adam",
    alpha=1e-3,                   # regularisation to prevent overfitting
    max_iter=2500,
    random_state=42
)

model.fit(X_scaled, y)

# -------------------------------------------------
# 4. Identify best point
# -------------------------------------------------

best_idx = np.argmax(y)
best_x = X[best_idx]

print("Best value:", y[best_idx])

# -------------------------------------------------
# 5. Generate candidate points
# -------------------------------------------------

rng = np.random.default_rng(123)

lower = X.min(axis=0)
upper = X.max(axis=0)

# Local refinement
local_candidates = rng.normal(loc=best_x, scale=0.04, size=(3000, 3))
local_candidates = np.clip(local_candidates, lower, upper)

# Global exploration
global_candidates = rng.uniform(lower, upper, size=(3000, 3))

# Combine
candidates = np.vstack([local_candidates, global_candidates])

# -------------------------------------------------
# 6. Remove near-duplicate candidates
# -------------------------------------------------

dist = np.sqrt(((candidates[:, None, :] - X[None, :, :])**2).sum(axis=2))
min_dist = dist.min(axis=1)

mask = min_dist > 0.01
candidates = candidates[mask]
min_dist = min_dist[mask]

# -------------------------------------------------
# 7. Predict outputs
# -------------------------------------------------

candidates_scaled = scaler.transform(candidates)
predictions = model.predict(candidates_scaled)

# -------------------------------------------------
# 8. Balanced scoring
# -------------------------------------------------

explore_score = min_dist / (min_dist.max() + 1e-12)

# Balanced approach (Query 6)
score = predictions + 0.10 * explore_score

# -------------------------------------------------
# 9. Select next query
# -------------------------------------------------

next_query = candidates[np.argmax(score)]

# -------------------------------------------------
# 10. Format for portal
# -------------------------------------------------

query_string = "-".join([f"{v:0.6f}" for v in next_query])

print("Next query:")
print(query_string)

Dataset shape: (20, 3)
Best value: -0.009616998691595194
Next query:
0.087129-0.543738-0.077625
