In [1]:
#Load packages required for loading the npy files.
import numpy as np
import pandas as pd

# #Load the npy file called "data.npy"
Initial_input_data = np.load("/Users/mayukotakamiya/MachineLearning/initial_data/function_7/initial_inputs.npy")
Initial_output_data = np.load("/Users/mayukotakamiya/MachineLearning/initial_data/function_7/initial_outputs.npy")

#I want to know dimentionality of the initial_input_data  
Initial_input_data.shape




(30, 6)

In [2]:

# X and y already loaded
X = Initial_input_data
y = Initial_output_data

def propose_next_point(X, y, n_candidates=8000, w_exploit=0.6, w_explore=0.4, seed=42):
    """
    Simple explore/exploit heuristic:
    - exploit: sample near best observed point
    - explore: sample far from existing samples
    """

    rng = np.random.default_rng(seed)
    n, d = X.shape

    # Best observed point so far
    best_x = X[np.argmax(y)]

    # Determine sampling bounds from existing data
    lower_bounds = X.min(axis=0)
    upper_bounds = X.max(axis=0)

    # Generate random candidate points within observed bounds
    C = rng.uniform(lower_bounds, upper_bounds, size=(n_candidates, d))

    # Exploitation term (closer to best is better)
    dist_to_best = np.linalg.norm(C - best_x, axis=1)
    exploit = 1 - (dist_to_best / (dist_to_best.max() + 1e-12))

    # Exploration term (farther from existing points is better)
    dists = np.sqrt(((C[:, None, :] - X[None, :, :]) ** 2).sum(axis=2))
    min_dist = dists.min(axis=1)
    explore = min_dist / (min_dist.max() + 1e-12)

    # Combined score
    score = w_exploit * exploit + w_explore * explore

    return C[np.argmax(score)]

def format_query(x):
    return "-".join([f"{v:0.6f}" for v in x])

# Generate next query
next_x = propose_next_point(X, y)

print("Submit this to the portal:")
print(format_query(next_x))

Submit this to the portal:
0.145970-0.921486


In [2]:
###WEEK 2
#I want to see the data in /Users/mayukotakamiya/MachineLearning/initial_data/function_1/initial_inputs.npy
print(Initial_input_data)
#I WANT TO create a new npy file by adding a new data point which is [0.433534 0.458467]
new_data_point = np.array([[0.134590, 0.748865, 0.886892, 0.157267, 0.734626, 0.825781]])
Combined_input_data = np.concatenate((Initial_input_data, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_7/W2_inputs.npy", Combined_input_data)
print(Combined_input_data)

[[0.27262382 0.32449536 0.89710881 0.83295115 0.15406269 0.79586362]
 [0.54300258 0.9246939  0.34156746 0.64648585 0.71844033 0.34313266]
 [0.09083225 0.66152938 0.06593091 0.25857701 0.96345285 0.6402654 ]
 [0.11886697 0.61505494 0.90581639 0.8553003  0.41363143 0.58523563]
 [0.63021764 0.8380969  0.68001305 0.73189509 0.52673671 0.34842921]
 [0.76491917 0.25588292 0.60908422 0.21807904 0.32294277 0.09579366]
 [0.05789554 0.49167222 0.24742222 0.21811844 0.42042833 0.73096984]
 [0.19525188 0.07922665 0.55458046 0.17056682 0.01494418 0.10703171]
 [0.64230298 0.83687455 0.02179269 0.10148801 0.68307083 0.6924164 ]
 [0.78994255 0.19554501 0.57562333 0.07365919 0.25904917 0.05109986]
 [0.52849733 0.45742436 0.36009569 0.36204551 0.81689098 0.63747637]
 [0.72261522 0.01181284 0.06364591 0.16517311 0.07924415 0.35995166]
 [0.07566492 0.33450212 0.13273274 0.60831236 0.91838592 0.82233079]
 [0.94245084 0.37743962 0.48612233 0.22879108 0.08263175 0.71195755]
 [0.14864702 0.03394336 0.72880565

In [3]:
print(Initial_output_data)

#I want to create a new npy file bt adding a new data point to the Initial_output_data
new_output_data_point = np.array([0.057963126418195905])
Combined_output_data = np.concatenate((Initial_output_data, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_7/W2_outputs.npy", Combined_output_data)

print(Combined_output_data)

[0.6044327  0.56275307 0.00750324 0.0614243  0.2730468  0.08374657
 1.3649683  0.09264495 0.0178696  0.03356494 0.0735163  0.2063097
 0.00882563 0.26840032 0.61152553 0.01479818 0.27489251 0.06676325
 0.04211835 0.00270147 0.01820907 0.00701603 0.10050661 0.47539552
 0.67514163 0.51645722 0.00377748 0.00313433 0.02134252 0.09541116]
[0.6044327  0.56275307 0.00750324 0.0614243  0.2730468  0.08374657
 1.3649683  0.09264495 0.0178696  0.03356494 0.0735163  0.2063097
 0.00882563 0.26840032 0.61152553 0.01479818 0.27489251 0.06676325
 0.04211835 0.00270147 0.01820907 0.00701603 0.10050661 0.47539552
 0.67514163 0.51645722 0.00377748 0.00313433 0.02134252 0.09541116
 0.05796313]


In [87]:
#Assess the exploitation vs exploration strategy
x=Combined_input_data
y=Combined_output_data

best_score_w2= np.max(y)
improvement= best_score_w2 - np.max(Initial_output_data)

print("Improvement:", improvement)
print("Output range:", y.min(), "to", y.max())
print("Std deviation:", np.std(y))


Improvement: 0.007087524491951498
Output range: -0.0036060626443634764 to 0.007087524491952269
Std deviation: 0.002376682573738607


In [ ]:
##Function1- For week2, it seems there is a big improvement by having the improvement more than 10% of the output range. Therefore, more exploitation than exploration.
##Function2- For week2, no improvement at all. Therefore use more exploration than exploitation
##Function3- for week2, no improvement at all.Therefore use more exploration than exploitation. 
##Function4- for week2, no improvement at all.Therefore use more exploration than exploitation. 
##Function5- for week2, no improvement at all.Therefore use more exploration than exploitation. 
##Function6- for week2, no improvement at all.Therefore use more exploration than exploitation. 
##Function7- for week2, no improvement at all.Therefore use more exploration than exploitation. 
#Function8- for week2, there is small-moderate improvement. Take a balanced approach (6:4)

In [88]:
#Re-run the loop
X=Combined_input_data
y=Combined_output_data

def propose_next_point(X, y, n_candidates=8000, w_exploit=0.75, w_explore=0.25, seed=234):
    """
    Simple explore/exploit heuristic:
    - exploit: sample near best observed point
    - explore: sample far from existing samples
    """

    rng = np.random.default_rng(seed)
    n, d = X.shape

    # Best observed point so far
    best_x = X[np.argmax(y)]
    
    radius = 0.05  # small local refinement

    # Determine sampling bounds from existing data
    lower = np.maximum(best_x - radius, X.min(axis=0))
    upper = np.minimum(best_x + radius, X.max(axis=0))


    # Generate random candidate points within observed bounds
    C = rng.uniform(lower, upper, size=(n_candidates, d))

    # Exploitation term (closer to best is better)
    dist_to_best = np.linalg.norm(C - best_x, axis=1)
    exploit = 1 - (dist_to_best / (dist_to_best.max() + 1e-12))

    # Exploration term (farther from existing points is better)
    dists = np.sqrt(((C[:, None, :] - X[None, :, :]) ** 2).sum(axis=2))
    min_dist = dists.min(axis=1)
    explore = min_dist / (min_dist.max() + 1e-12)

    # Combined score
    score = w_exploit * exploit + w_explore * explore

    return C[np.argmax(score)]

def format_query(x):
    return "-".join([f"{v:0.6f}" for v in x])

# Generate next query
next_x = propose_next_point(X, y)

print("Submit this to the portal:")
print(format_query(next_x))

Submit this to the portal:
0.433582-0.457940


In [4]:
####WEEK 3
new_data_point = np.array([[0.105722, 0.539255, 0.206091, 0.171339, 0.375713, 0.779977]])
Combined_input_data3 = np.concatenate((Combined_input_data, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_7/W3_inputs.npy", Combined_input_data3)
print(Combined_input_data3)

new_output_data_point = np.array([1.1902497681664506])
Combined_output_data3 = np.concatenate((Combined_output_data, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_7/W3_outputs.npy", Combined_output_data3)

print(Combined_output_data3)


[[0.27262382 0.32449536 0.89710881 0.83295115 0.15406269 0.79586362]
 [0.54300258 0.9246939  0.34156746 0.64648585 0.71844033 0.34313266]
 [0.09083225 0.66152938 0.06593091 0.25857701 0.96345285 0.6402654 ]
 [0.11886697 0.61505494 0.90581639 0.8553003  0.41363143 0.58523563]
 [0.63021764 0.8380969  0.68001305 0.73189509 0.52673671 0.34842921]
 [0.76491917 0.25588292 0.60908422 0.21807904 0.32294277 0.09579366]
 [0.05789554 0.49167222 0.24742222 0.21811844 0.42042833 0.73096984]
 [0.19525188 0.07922665 0.55458046 0.17056682 0.01494418 0.10703171]
 [0.64230298 0.83687455 0.02179269 0.10148801 0.68307083 0.6924164 ]
 [0.78994255 0.19554501 0.57562333 0.07365919 0.25904917 0.05109986]
 [0.52849733 0.45742436 0.36009569 0.36204551 0.81689098 0.63747637]
 [0.72261522 0.01181284 0.06364591 0.16517311 0.07924415 0.35995166]
 [0.07566492 0.33450212 0.13273274 0.60831236 0.91838592 0.82233079]
 [0.94245084 0.37743962 0.48612233 0.22879108 0.08263175 0.71195755]
 [0.14864702 0.03394336 0.72880565

In [5]:
#WEEK 3 Assess the exploitation vs exploration strategy
x=Combined_input_data3
y=Combined_output_data3

best_score_w2= np.max(y)
improvement= best_score_w2 - np.max(Combined_output_data)

print("Improvement:", improvement)
print("Output range:", y.min(), "to", y.max())
print("Std deviation:", np.std(y))

Improvement: 0.0
Output range: 0.0027014650245082332 to 1.3649683044991994
Std deviation: 0.33940618415406537


In [6]:
###WEEK 3 - apply SVM 
X=Combined_input_data3
y=Combined_output_data3


threshold = np.quantile(y, 0.7)
labels = (y >= threshold).astype(int)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

from sklearn.svm import SVC

model = SVC(kernel='rbf', C=1.0, gamma='scale')
model.fit(X_scaled, labels)

rng = np.random.default_rng(42)

lower = X.min(axis=0)
upper = X.max(axis=0)

candidates = rng.uniform(lower, upper, size=(5000, X.shape[1]))

candidates_scaled = scaler.transform(candidates)

scores = model.decision_function(candidates_scaled)

next_point = candidates[np.argmin(np.abs(scores))]

query = "-".join([f"{v:0.6f}" for v in next_point])
print(query)

0.431487-0.905820-0.260199-0.489773-0.172207-0.211774


In [7]:
####WEEK 4
new_data_point = np.array([[0.431487, 0.905820, 0.260199, 0.489773, 0.172207, 0.211774]])
Combined_input_data4 = np.concatenate((Combined_input_data3, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_7/W4_inputs.npy", Combined_input_data4)
print(Combined_input_data4)

new_output_data_point = np.array([1.9192145262855722])
Combined_output_data4 = np.concatenate((Combined_output_data3, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_7/W4_outputs.npy", Combined_output_data4)

print(Combined_output_data4)

[[0.27262382 0.32449536 0.89710881 0.83295115 0.15406269 0.79586362]
 [0.54300258 0.9246939  0.34156746 0.64648585 0.71844033 0.34313266]
 [0.09083225 0.66152938 0.06593091 0.25857701 0.96345285 0.6402654 ]
 [0.11886697 0.61505494 0.90581639 0.8553003  0.41363143 0.58523563]
 [0.63021764 0.8380969  0.68001305 0.73189509 0.52673671 0.34842921]
 [0.76491917 0.25588292 0.60908422 0.21807904 0.32294277 0.09579366]
 [0.05789554 0.49167222 0.24742222 0.21811844 0.42042833 0.73096984]
 [0.19525188 0.07922665 0.55458046 0.17056682 0.01494418 0.10703171]
 [0.64230298 0.83687455 0.02179269 0.10148801 0.68307083 0.6924164 ]
 [0.78994255 0.19554501 0.57562333 0.07365919 0.25904917 0.05109986]
 [0.52849733 0.45742436 0.36009569 0.36204551 0.81689098 0.63747637]
 [0.72261522 0.01181284 0.06364591 0.16517311 0.07924415 0.35995166]
 [0.07566492 0.33450212 0.13273274 0.60831236 0.91838592 0.82233079]
 [0.94245084 0.37743962 0.48612233 0.22879108 0.08263175 0.71195755]
 [0.14864702 0.03394336 0.72880565

In [8]:
##WEEK 4- SVM and NN hybrid

import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.neural_network import MLPRegressor

# --------------------------------------------------
# 1. Load dataset
# --------------------------------------------------

X = Combined_input_data4
y = Combined_output_data4

print("Dataset shape:", X.shape)

# --------------------------------------------------
# 2. Convert outputs to classification labels
# --------------------------------------------------

threshold = np.quantile(y, 0.7)   # top 30% = good
labels = (y >= threshold).astype(int)

# --------------------------------------------------
# 3. Scale inputs
# --------------------------------------------------

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# --------------------------------------------------
# 4. Train SVM classifier
# --------------------------------------------------

svm = SVC(kernel="rbf", C=1.0, gamma="scale")
svm.fit(X_scaled, labels)

# --------------------------------------------------
# 5. Train neural network surrogate
# --------------------------------------------------

nn = MLPRegressor(
    hidden_layer_sizes=(24,12),
    activation="relu",
    solver="adam",
    max_iter=2000,
    random_state=42
)

nn.fit(X_scaled, y)

# --------------------------------------------------
# 6. Generate candidate points
# --------------------------------------------------

rng = np.random.default_rng(42)

lower = X.min(axis=0)
upper = X.max(axis=0)

candidates = rng.uniform(lower, upper, size=(10000, X.shape[1]))

# --------------------------------------------------
# 7. Remove candidates too close to existing points
# --------------------------------------------------

dist = np.sqrt(((candidates[:,None,:] - X[None,:,:])**2).sum(axis=2))
min_dist = dist.min(axis=1)

mask = min_dist > 0.01
candidates = candidates[mask]

# --------------------------------------------------
# 8. Score candidates using SVM + NN
# --------------------------------------------------

candidates_scaled = scaler.transform(candidates)

# SVM decision score (region quality)
svm_scores = svm.decision_function(candidates_scaled)

# NN predicted output
nn_predictions = nn.predict(candidates_scaled)

# Combine both scores
combined_score = nn_predictions + 0.1 * svm_scores

# --------------------------------------------------
# 9. Select best candidate
# --------------------------------------------------

best_candidate = candidates[np.argmax(combined_score)]

# --------------------------------------------------
# 10. Format for portal
# --------------------------------------------------

query_string = "-".join([f"{v:0.6f}" for v in best_candidate])

print("Next query:")
print(query_string)

Dataset shape: (33, 6)
Next query:
0.141474-0.918354-0.077736-0.858246-0.205707-0.070882


In [9]:
#WEEK 5 
new_data_point = np.array([[0.141474, 0.918354, 0.077736, 0.858246, 0.205707, 0.070882]])
Combined_input_data5 = np.concatenate((Combined_input_data4, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_7/W5_inputs.npy", Combined_input_data5)
print(Combined_input_data5)

new_output_data_point = np.array([0.41594919462458524])
Combined_output_data5 = np.concatenate((Combined_output_data4, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_7/W5_outputs.npy", Combined_output_data5)

print(Combined_output_data5)

[[0.27262382 0.32449536 0.89710881 0.83295115 0.15406269 0.79586362]
 [0.54300258 0.9246939  0.34156746 0.64648585 0.71844033 0.34313266]
 [0.09083225 0.66152938 0.06593091 0.25857701 0.96345285 0.6402654 ]
 [0.11886697 0.61505494 0.90581639 0.8553003  0.41363143 0.58523563]
 [0.63021764 0.8380969  0.68001305 0.73189509 0.52673671 0.34842921]
 [0.76491917 0.25588292 0.60908422 0.21807904 0.32294277 0.09579366]
 [0.05789554 0.49167222 0.24742222 0.21811844 0.42042833 0.73096984]
 [0.19525188 0.07922665 0.55458046 0.17056682 0.01494418 0.10703171]
 [0.64230298 0.83687455 0.02179269 0.10148801 0.68307083 0.6924164 ]
 [0.78994255 0.19554501 0.57562333 0.07365919 0.25904917 0.05109986]
 [0.52849733 0.45742436 0.36009569 0.36204551 0.81689098 0.63747637]
 [0.72261522 0.01181284 0.06364591 0.16517311 0.07924415 0.35995166]
 [0.07566492 0.33450212 0.13273274 0.60831236 0.91838592 0.82233079]
 [0.94245084 0.37743962 0.48612233 0.22879108 0.08263175 0.71195755]
 [0.14864702 0.03394336 0.72880565

In [10]:
##WEEK 5 - train a small neural network surrogate
#$generate both global and local candidates
#use the NN’s predicted output to rank them
#add a small exploration bonus
#avoid querying points too close to existing samples

import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPRegressor

# -------------------------------------------------
# 1. Load dataset
# -------------------------------------------------

X = Combined_input_data5
y = Combined_output_data5

print("Dataset shape:", X.shape)

# -------------------------------------------------
# 2. Scale inputs
# -------------------------------------------------

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# -------------------------------------------------
# 3. Train neural network surrogate
# -------------------------------------------------

model = MLPRegressor(
    hidden_layer_sizes=(40, 20),   # a bit larger for 6D
    activation="relu",
    solver="adam",
    alpha=1e-3,                    # light regularisation
    max_iter=4000,
    random_state=42
)

model.fit(X_scaled, y)

# -------------------------------------------------
# 4. Identify current best point
# -------------------------------------------------

best_idx = np.argmax(y)
best_x = X[best_idx]

print("Best value so far:", y[best_idx])
print("Best point so far:", best_x)

# -------------------------------------------------
# 5. Generate candidate points
# -------------------------------------------------

rng = np.random.default_rng(42)

lower = X.min(axis=0)
upper = X.max(axis=0)

# Global exploration candidates
global_candidates = rng.uniform(lower, upper, size=(8000, 6))

# Local refinement candidates around current best
local_candidates = rng.normal(loc=best_x, scale=0.04, size=(8000, 6))
local_candidates = np.clip(local_candidates, lower, upper)

# Combine candidates
candidates = np.vstack([global_candidates, local_candidates])

# -------------------------------------------------
# 6. Remove near-duplicate candidates
# -------------------------------------------------

dist = np.sqrt(((candidates[:, None, :] - X[None, :, :]) ** 2).sum(axis=2))
min_dist = dist.min(axis=1)

mask = min_dist > 0.01
candidates = candidates[mask]
min_dist = min_dist[mask]

print("Candidates after filtering:", candidates.shape[0])

# -------------------------------------------------
# 7. Predict outputs with neural network
# -------------------------------------------------

candidates_scaled = scaler.transform(candidates)
predictions = model.predict(candidates_scaled)

# -------------------------------------------------
# 8. Add exploration bonus
# -------------------------------------------------

explore_score = min_dist / (min_dist.max() + 1e-12)

# Balanced score: prediction + exploration bonus
score = predictions + 0.10 * explore_score

# -------------------------------------------------
# 9. Select best candidate
# -------------------------------------------------

best_candidate_idx = np.argmax(score)
next_query = candidates[best_candidate_idx]

print("Predicted score of next query:", predictions[best_candidate_idx])

# -------------------------------------------------
# 10. Format for portal submission
# -------------------------------------------------

query_string = "-".join([f"{v:0.6f}" for v in next_query])

print("Next query:")
print(query_string)

Dataset shape: (34, 6)
Best value so far: 1.9192145262855722
Best point so far: [0.431487 0.90582  0.260199 0.489773 0.172207 0.211774]
Candidates after filtering: 15998
Predicted score of next query: 2.003650249859447
Next query:
0.357308-0.924694-0.189948-0.426890-0.106825-0.131658


In [11]:
#WEEK 6
new_data_point = np.array([[0.141474, 0.918354, 0.077736, 0.858246, 0.205707, 0.070882]])
Combined_input_data6 = np.concatenate((Combined_input_data5, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_7/W6_inputs.npy", Combined_input_data6)
print(Combined_input_data6)

new_output_data_point = np.array([0.41594919462458524])
Combined_output_data6 = np.concatenate((Combined_output_data5, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_7/W6_outputs.npy", Combined_output_data6)

print(Combined_output_data6)

[[0.27262382 0.32449536 0.89710881 0.83295115 0.15406269 0.79586362]
 [0.54300258 0.9246939  0.34156746 0.64648585 0.71844033 0.34313266]
 [0.09083225 0.66152938 0.06593091 0.25857701 0.96345285 0.6402654 ]
 [0.11886697 0.61505494 0.90581639 0.8553003  0.41363143 0.58523563]
 [0.63021764 0.8380969  0.68001305 0.73189509 0.52673671 0.34842921]
 [0.76491917 0.25588292 0.60908422 0.21807904 0.32294277 0.09579366]
 [0.05789554 0.49167222 0.24742222 0.21811844 0.42042833 0.73096984]
 [0.19525188 0.07922665 0.55458046 0.17056682 0.01494418 0.10703171]
 [0.64230298 0.83687455 0.02179269 0.10148801 0.68307083 0.6924164 ]
 [0.78994255 0.19554501 0.57562333 0.07365919 0.25904917 0.05109986]
 [0.52849733 0.45742436 0.36009569 0.36204551 0.81689098 0.63747637]
 [0.72261522 0.01181284 0.06364591 0.16517311 0.07924415 0.35995166]
 [0.07566492 0.33450212 0.13273274 0.60831236 0.91838592 0.82233079]
 [0.94245084 0.37743962 0.48612233 0.22879108 0.08263175 0.71195755]
 [0.14864702 0.03394336 0.72880565

In [12]:
##WEEK 6 
#Use a slightly larger neural network surrogate
#Combine:
#global exploration (important in 6D)
#local refinement
#Add exploration bonus
#Avoid over-exploitation (previous stagnation risk)

import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPRegressor

# -------------------------------------------------
# 1. Load dataset
# -------------------------------------------------

X = Combined_input_data6
y = Combined_output_data6

print("Dataset shape:", X.shape)

# -------------------------------------------------
# 2. Scale inputs
# -------------------------------------------------

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# -------------------------------------------------
# 3. Train neural network surrogate
# -------------------------------------------------

model = MLPRegressor(
    hidden_layer_sizes=(40, 20),   # slightly larger for 6D
    activation="relu",
    solver="adam",
    alpha=1e-3,                    # regularisation
    max_iter=4000,
    random_state=42
)

model.fit(X_scaled, y)

# -------------------------------------------------
# 4. Identify best point
# -------------------------------------------------

best_idx = np.argmax(y)
best_x = X[best_idx]

print("Best value:", y[best_idx])

# -------------------------------------------------
# 5. Generate candidate points
# -------------------------------------------------

rng = np.random.default_rng(123)

lower = X.min(axis=0)
upper = X.max(axis=0)

# Global exploration (important in 6D)
global_candidates = rng.uniform(lower, upper, size=(8000, 6))

# Local refinement around best point
local_candidates = rng.normal(loc=best_x, scale=0.04, size=(8000, 6))
local_candidates = np.clip(local_candidates, lower, upper)

# Combine candidates
candidates = np.vstack([global_candidates, local_candidates])

# -------------------------------------------------
# 6. Remove near-duplicate candidates
# -------------------------------------------------

dist = np.sqrt(((candidates[:, None, :] - X[None, :, :])**2).sum(axis=2))
min_dist = dist.min(axis=1)

mask = min_dist > 0.01
candidates = candidates[mask]
min_dist = min_dist[mask]

print("Candidates after filtering:", candidates.shape[0])

# -------------------------------------------------
# 7. Predict outputs
# -------------------------------------------------

candidates_scaled = scaler.transform(candidates)
predictions = model.predict(candidates_scaled)

# -------------------------------------------------
# 8. Balanced scoring (avoid overfitting)
# -------------------------------------------------

explore_score = min_dist / (min_dist.max() + 1e-12)

# Balanced approach (slightly exploration-aware)
score = predictions + 0.12 * explore_score

# -------------------------------------------------
# 9. Select next query
# -------------------------------------------------

best_candidate_idx = np.argmax(score)
next_query = candidates[best_candidate_idx]

print("Predicted best value:", predictions[best_candidate_idx])

# -------------------------------------------------
# 10. Format for portal
# -------------------------------------------------

query_string = "-".join([f"{v:0.6f}" for v in next_query])

print("Next query:")
print(query_string)


Dataset shape: (35, 6)
Best value: 1.9192145262855722
Candidates after filtering: 16000
Predicted best value: 2.030651984066154
Next query:
0.404479-0.923183-0.215051-0.432142-0.058745-0.143931
