In [9]:
#Load packages required for loading the npy files.
import numpy as np
import pandas as pd

# #Load the npy file called "data.npy"
Initial_input_data = np.load("/Users/mayukotakamiya/MachineLearning/initial_data/function_2/initial_inputs.npy")
Initial_output_data = np.load("/Users/mayukotakamiya/MachineLearning/initial_data/function_2/initial_outputs.npy")

#I want to know dimentionality of the initial_input_data  
Initial_input_data.shape




(10, 2)

In [2]:

# X and y already loaded
X = Initial_input_data
y = Initial_output_data

def propose_next_point(X, y, n_candidates=8000, w_exploit=0.6, w_explore=0.4, seed=42):
    """
    Simple explore/exploit heuristic:
    - exploit: sample near best observed point
    - explore: sample far from existing samples
    """

    rng = np.random.default_rng(seed)
    n, d = X.shape

    # Best observed point so far
    best_x = X[np.argmax(y)]

    # Determine sampling bounds from existing data
    lower_bounds = X.min(axis=0)
    upper_bounds = X.max(axis=0)

    # Generate random candidate points within observed bounds
    C = rng.uniform(lower_bounds, upper_bounds, size=(n_candidates, d))

    # Exploitation term (closer to best is better)
    dist_to_best = np.linalg.norm(C - best_x, axis=1)
    exploit = 1 - (dist_to_best / (dist_to_best.max() + 1e-12))

    # Exploration term (farther from existing points is better)
    dists = np.sqrt(((C[:, None, :] - X[None, :, :]) ** 2).sum(axis=2))
    min_dist = dists.min(axis=1)
    explore = min_dist / (min_dist.max() + 1e-12)

    # Combined score
    score = w_exploit * exploit + w_explore * explore

    return C[np.argmax(score)]

def format_query(x):
    return "-".join([f"{v:0.6f}" for v in x])

# Generate next query
next_x = propose_next_point(X, y)

print("Submit this to the portal:")
print(format_query(next_x))

Submit this to the portal:
0.145970-0.921486


In [10]:
###WEEK 2
#I want to see the data in /Users/mayukotakamiya/MachineLearning/initial_data/function_1/initial_inputs.npy
print(Initial_input_data)
#I WANT TO create a new npy file by adding a new data point which is [0.433534 0.458467]
new_data_point = np.array([[0.145970, 0.921486]])
Combined_input_data = np.concatenate((Initial_input_data, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_2/W2_inputs.npy", Combined_input_data)
print(Combined_input_data)

[[0.66579958 0.12396913]
 [0.87779099 0.7786275 ]
 [0.14269907 0.34900513]
 [0.84527543 0.71112027]
 [0.45464714 0.29045518]
 [0.57771284 0.77197318]
 [0.43816606 0.68501826]
 [0.34174959 0.02869772]
 [0.33864816 0.21386725]
 [0.70263656 0.9265642 ]]
[[0.66579958 0.12396913]
 [0.87779099 0.7786275 ]
 [0.14269907 0.34900513]
 [0.84527543 0.71112027]
 [0.45464714 0.29045518]
 [0.57771284 0.77197318]
 [0.43816606 0.68501826]
 [0.34174959 0.02869772]
 [0.33864816 0.21386725]
 [0.70263656 0.9265642 ]
 [0.14597    0.921486  ]]


In [11]:
print(Initial_output_data)

#I want to create a new npy file bt adding a new data point to the Initial_output_data
new_output_data_point = np.array([00.051283499993391726])
Combined_output_data = np.concatenate((Initial_output_data, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_2/W2_outputs.npy", Combined_output_data)

print(Combined_output_data)

[ 0.53899612  0.42058624 -0.06562362  0.29399291  0.21496451  0.02310555
  0.24461934  0.03874902 -0.01385762  0.61120522]
[ 0.53899612  0.42058624 -0.06562362  0.29399291  0.21496451  0.02310555
  0.24461934  0.03874902 -0.01385762  0.61120522  0.0512835 ]


In [87]:
#Assess the exploitation vs exploration strategy
x=Combined_input_data
y=Combined_output_data

best_score_w2= np.max(y)
improvement= best_score_w2 - np.max(Initial_output_data)

print("Improvement:", improvement)
print("Output range:", y.min(), "to", y.max())
print("Std deviation:", np.std(y))


Improvement: 0.007087524491951498
Output range: -0.0036060626443634764 to 0.007087524491952269
Std deviation: 0.002376682573738607


In [ ]:
##Function1- For week2, it seems there is a big improvement by having the improvement more than 10% of the output range. Therefore, more exploitation than exploration.
##Function2- For week2, no improvement at all. Therefore use more exploration than exploitation
##Function3- for week2, no improvement at all.Therefore use more exploration than exploitation. 
##Function4- for week2, no improvement at all.Therefore use more exploration than exploitation. 
##Function5- for week2, no improvement at all.Therefore use more exploration than exploitation. 
##Function6- for week2, no improvement at all.Therefore use more exploration than exploitation. 
##Function7- for week2, no improvement at all.Therefore use more exploration than exploitation. 
#Function8- for week2, there is small-moderate improvement. Take a balanced approach (6:4)

In [88]:
#Re-run the loop
X=Combined_input_data
y=Combined_output_data

def propose_next_point(X, y, n_candidates=8000, w_exploit=0.75, w_explore=0.25, seed=234):
    """
    Simple explore/exploit heuristic:
    - exploit: sample near best observed point
    - explore: sample far from existing samples
    """

    rng = np.random.default_rng(seed)
    n, d = X.shape

    # Best observed point so far
    best_x = X[np.argmax(y)]
    
    radius = 0.05  # small local refinement

    # Determine sampling bounds from existing data
    lower = np.maximum(best_x - radius, X.min(axis=0))
    upper = np.minimum(best_x + radius, X.max(axis=0))


    # Generate random candidate points within observed bounds
    C = rng.uniform(lower, upper, size=(n_candidates, d))

    # Exploitation term (closer to best is better)
    dist_to_best = np.linalg.norm(C - best_x, axis=1)
    exploit = 1 - (dist_to_best / (dist_to_best.max() + 1e-12))

    # Exploration term (farther from existing points is better)
    dists = np.sqrt(((C[:, None, :] - X[None, :, :]) ** 2).sum(axis=2))
    min_dist = dists.min(axis=1)
    explore = min_dist / (min_dist.max() + 1e-12)

    # Combined score
    score = w_exploit * exploit + w_explore * explore

    return C[np.argmax(score)]

def format_query(x):
    return "-".join([f"{v:0.6f}" for v in x])

# Generate next query
next_x = propose_next_point(X, y)

print("Submit this to the portal:")
print(format_query(next_x))

Submit this to the portal:
0.433582-0.457940


In [12]:
####WEEK 3
new_data_point = np.array([[0.652719, 0.877025]])
Combined_input_data3 = np.concatenate((Combined_input_data, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_2/W3_inputs.npy", Combined_input_data3)
print(Combined_input_data3)

new_output_data_point = np.array([0.43822056967450884])
Combined_output_data3 = np.concatenate((Combined_output_data, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_2/W3_outputs.npy", Combined_output_data3)

print(Combined_output_data3)


[[0.66579958 0.12396913]
 [0.87779099 0.7786275 ]
 [0.14269907 0.34900513]
 [0.84527543 0.71112027]
 [0.45464714 0.29045518]
 [0.57771284 0.77197318]
 [0.43816606 0.68501826]
 [0.34174959 0.02869772]
 [0.33864816 0.21386725]
 [0.70263656 0.9265642 ]
 [0.14597    0.921486  ]
 [0.652719   0.877025  ]]
[ 0.53899612  0.42058624 -0.06562362  0.29399291  0.21496451  0.02310555
  0.24461934  0.03874902 -0.01385762  0.61120522  0.0512835   0.43822057]


In [13]:
#WEEK 3 Assess the exploitation vs exploration strategy
x=Combined_input_data3
y=Combined_output_data3

best_score_w2= np.max(y)
improvement= best_score_w2 - np.max(Combined_output_data)

print("Improvement:", improvement)
print("Output range:", y.min(), "to", y.max())
print("Std deviation:", np.std(y))

Improvement: 0.0
Output range: -0.06562362443733738 to 0.6112052157614438
Std deviation: 0.22043178697581692


In [14]:
#WEEK 3 -re run the loop. No improvement so adjust exploit vs explore ratio to 0.45:0.55
X=Combined_input_data3
y=Combined_output_data3

def propose_next_point(X, y, n_candidates=8000, w_exploit=0.45, w_explore=0.55, seed=234):

    rng = np.random.default_rng(seed)
    n, d = X.shape

    # Best observed point so far
    best_x = X[np.argmax(y)]
    
    radius = 0.05  # small local refinement

    # Determine sampling bounds from existing data
    lower = np.maximum(best_x - radius, X.min(axis=0))
    upper = np.minimum(best_x + radius, X.max(axis=0))


    # Generate random candidate points within observed bounds
    C = rng.uniform(lower, upper, size=(n_candidates, d))

    # Exploitation term (closer to best is better)
    dist_to_best = np.linalg.norm(C - best_x, axis=1)
    exploit = 1 - (dist_to_best / (dist_to_best.max() + 1e-12))

    # Exploration term (farther from existing points is better)
    dists = np.sqrt(((C[:, None, :] - X[None, :, :]) ** 2).sum(axis=2))
    min_dist = dists.min(axis=1)
    explore = min_dist / (min_dist.max() + 1e-12)

    # Combined score
    score = w_exploit * exploit + w_explore * explore

    return C[np.argmax(score)]

def format_query(x):
    return "-".join([f"{v:0.6f}" for v in x])

# Generate next query
next_x = propose_next_point(X, y)

print("Submit this to the portal:")
print(format_query(next_x))

Submit this to the portal:
0.751452-0.876910


In [15]:
####WEEK 4
new_data_point = np.array([[0.751452, 0.876910]])
Combined_input_data4 = np.concatenate((Combined_input_data3, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_2/W4_inputs.npy", Combined_input_data4)
print(Combined_input_data4)

new_output_data_point = np.array([0.56484447865487])
Combined_output_data4 = np.concatenate((Combined_output_data3, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_2/W4_outputs.npy", Combined_output_data4)

print(Combined_output_data4)

[[0.66579958 0.12396913]
 [0.87779099 0.7786275 ]
 [0.14269907 0.34900513]
 [0.84527543 0.71112027]
 [0.45464714 0.29045518]
 [0.57771284 0.77197318]
 [0.43816606 0.68501826]
 [0.34174959 0.02869772]
 [0.33864816 0.21386725]
 [0.70263656 0.9265642 ]
 [0.14597    0.921486  ]
 [0.652719   0.877025  ]
 [0.751452   0.87691   ]]
[ 0.53899612  0.42058624 -0.06562362  0.29399291  0.21496451  0.02310555
  0.24461934  0.03874902 -0.01385762  0.61120522  0.0512835   0.43822057
  0.56484448]


In [16]:
#WEEK 4 Assess the exploitation vs exploration strategy
x=Combined_input_data4
y=Combined_output_data4

best_score_w2= np.max(y)
improvement= best_score_w2 - np.max(Combined_output_data3)

print("Improvement:", improvement)
print("Output range:", y.min(), "to", y.max())
print("Std deviation:", np.std(y))

Improvement: 0.0
Output range: -0.06562362443733738 to 0.6112052157614438
Std deviation: 0.22950107460343838


In [17]:
#WEEK 4 -re run the loop. No improvement so adjust exploit vs explore ratio to 0.45:0.55
X=Combined_input_data4
y=Combined_output_data4

def propose_next_point(X, y, n_candidates=8000, w_exploit=0.45, w_explore=0.55, seed=100):

    rng = np.random.default_rng(seed)
    n, d = X.shape

    # Best observed point so far
    best_x = X[np.argmax(y)]
    
    radius = 0.05  # small local refinement

    # Determine sampling bounds from existing data
    lower = np.maximum(best_x - radius, X.min(axis=0))
    upper = np.minimum(best_x + radius, X.max(axis=0))


    # Generate random candidate points within observed bounds
    C = rng.uniform(lower, upper, size=(n_candidates, d))

    # Exploitation term (closer to best is better)
    dist_to_best = np.linalg.norm(C - best_x, axis=1)
    exploit = 1 - (dist_to_best / (dist_to_best.max() + 1e-12))

    # Exploration term (farther from existing points is better)
    dists = np.sqrt(((C[:, None, :] - X[None, :, :]) ** 2).sum(axis=2))
    min_dist = dists.min(axis=1)
    explore = min_dist / (min_dist.max() + 1e-12)
# Combined score
    score = w_exploit * exploit + w_explore * explore

    return C[np.argmax(score)]

def format_query(x):
    return "-".join([f"{v:0.6f}" for v in x])

# Generate next query
next_x = propose_next_point(X, y)

print("Submit this to the portal:")
print(format_query(next_x))

Submit this to the portal:
0.701759-0.877518


In [18]:
#WEEK 5 
new_data_point = np.array([[0.701759, 0.877518]])
Combined_input_data5 = np.concatenate((Combined_input_data4, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_2/W5_inputs.npy", Combined_input_data5)
print(Combined_input_data5)

new_output_data_point = np.array([0.5430405844702764])
Combined_output_data5 = np.concatenate((Combined_output_data4, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_2/W5_outputs.npy", Combined_output_data5)

print(Combined_output_data5)

[[0.66579958 0.12396913]
 [0.87779099 0.7786275 ]
 [0.14269907 0.34900513]
 [0.84527543 0.71112027]
 [0.45464714 0.29045518]
 [0.57771284 0.77197318]
 [0.43816606 0.68501826]
 [0.34174959 0.02869772]
 [0.33864816 0.21386725]
 [0.70263656 0.9265642 ]
 [0.14597    0.921486  ]
 [0.652719   0.877025  ]
 [0.751452   0.87691   ]
 [0.701759   0.877518  ]]
[ 0.53899612  0.42058624 -0.06562362  0.29399291  0.21496451  0.02310555
  0.24461934  0.03874902 -0.01385762  0.61120522  0.0512835   0.43822057
  0.56484448  0.54304058]


In [19]:
##WEEK 5 - Avoid aggressive exploitation (noise can mislead), Prefer: diverse sampling and moderate refinement near good regions

import numpy as np

X = Combined_input_data5
y = Combined_output_data5

print("Dataset shape:", X.shape)

# -------------------------------------------------
# 2. Identify best and top-performing points
# -------------------------------------------------

best_idx = np.argmax(y)
best_x = X[best_idx]

# Also consider top 30% points (robust against noise)
threshold = np.quantile(y, 0.7)
top_points = X[y >= threshold]

# -------------------------------------------------
# 3. Generate candidate points
# -------------------------------------------------

rng = np.random.default_rng(42)

lower = X.min(axis=0)
upper = X.max(axis=0)

# Global exploration (dominant)
global_candidates = rng.uniform(lower, upper, size=(4000, 2))

# Local candidates around multiple good points (not just best)
local_candidates = []

for pt in top_points:
    local = rng.normal(loc=pt, scale=0.05, size=(500, 2))
    local_candidates.append(local)

local_candidates = np.vstack(local_candidates)

# Combine
candidates = np.vstack([global_candidates, local_candidates])

# Clip to bounds
candidates = np.clip(candidates, lower, upper)

# -------------------------------------------------
# 4. Remove candidates too close to existing points
# -------------------------------------------------

dist = np.sqrt(((candidates[:, None, :] - X[None, :, :])**2).sum(axis=2))
min_dist = dist.min(axis=1)

mask = min_dist > 0.01
candidates = candidates[mask]
min_dist = min_dist[mask]

# -------------------------------------------------
# 5. Score candidates (noise-robust)
# -------------------------------------------------

# Exploitation: distance to multiple good points
dist_to_top = np.min(
    np.sqrt(((candidates[:, None, :] - top_points[None, :, :])**2).sum(axis=2)),
    axis=1
)

exploit_score = 1 - dist_to_top / (dist_to_top.max() + 1e-12)

# Exploration: distance from existing samples
explore_score = min_dist / (min_dist.max() + 1e-12)

# Slightly exploration-heavy (because noise)
score = 0.4 * exploit_score + 0.6 * explore_score

# -------------------------------------------------
# 6. Select next query
# -------------------------------------------------

next_query = candidates[np.argmax(score)]

# -------------------------------------------------
# 7. Format for portal
# -------------------------------------------------

query_string = "-".join([f"{v:0.6f}" for v in next_query])

print("Next query:")
print(query_string)

Dataset shape: (14, 2)
Next query:
0.847723-0.389764


In [22]:
#WEEK 6
new_data_point = np.array([[0.701759, 0.877518]])
Combined_input_data6 = np.concatenate((Combined_input_data5, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_2/W6_inputs.npy", Combined_input_data6)
print(Combined_input_data6)

new_output_data_point = np.array([50.5430405844702764])
Combined_output_data6 = np.concatenate((Combined_output_data5, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_2/W6_outputs.npy", Combined_output_data6)

print(Combined_output_data6)

[[0.66579958 0.12396913]
 [0.87779099 0.7786275 ]
 [0.14269907 0.34900513]
 [0.84527543 0.71112027]
 [0.45464714 0.29045518]
 [0.57771284 0.77197318]
 [0.43816606 0.68501826]
 [0.34174959 0.02869772]
 [0.33864816 0.21386725]
 [0.70263656 0.9265642 ]
 [0.14597    0.921486  ]
 [0.652719   0.877025  ]
 [0.751452   0.87691   ]
 [0.701759   0.877518  ]
 [0.701759   0.877518  ]]
[ 5.38996119e-01  4.20586240e-01 -6.56236244e-02  2.93992912e-01
  2.14964510e-01  2.31055498e-02  2.44619344e-01  3.87490152e-02
 -1.38576181e-02  6.11205216e-01  5.12835000e-02  4.38220570e-01
  5.64844479e-01  5.43040584e-01  5.05430406e+01]


In [23]:
##WEEK 6 
#Do not rely on a single best point
#Use top-performing region (robust to noise)
#Keep exploration slightly dominant
#Avoid neural networks (overkill + noise-sensitive)

X = Combined_input_data6
y = Combined_output_data6

print("Dataset shape:", X.shape)

# -------------------------------------------------
# 2. Identify robust high-performing region
# -------------------------------------------------

# Use top 30% instead of single best (noise-robust)
threshold = np.quantile(y, 0.7)
top_points = X[y >= threshold]

print("Number of top points:", len(top_points))

# -------------------------------------------------
# 3. Generate candidate points
# -------------------------------------------------

rng = np.random.default_rng(123)

lower = X.min(axis=0)
upper = X.max(axis=0)

# Global exploration (important due to noise)
global_candidates = rng.uniform(lower, upper, size=(4000, 2))

# Local sampling around multiple good points
local_candidates = []

for pt in top_points:
    local = rng.normal(loc=pt, scale=0.04, size=(500, 2))
    local_candidates.append(local)

local_candidates = np.vstack(local_candidates)

# Combine candidates
candidates = np.vstack([global_candidates, local_candidates])

# Clip to bounds
candidates = np.clip(candidates, lower, upper)

# -------------------------------------------------
# 4. Remove near-duplicate candidates
# -------------------------------------------------

dist = np.sqrt(((candidates[:, None, :] - X[None, :, :])**2).sum(axis=2))
min_dist = dist.min(axis=1)

mask = min_dist > 0.01
candidates = candidates[mask]
min_dist = min_dist[mask]

# -------------------------------------------------
# 5. Score candidates (noise-robust)
# -------------------------------------------------

# Exploitation: distance to top-performing region
dist_to_top = np.min(
    np.sqrt(((candidates[:, None, :] - top_points[None, :, :])**2).sum(axis=2)),
    axis=1
)

exploit_score = 1 - dist_to_top / (dist_to_top.max() + 1e-12)

# Exploration: distance from known points
explore_score = min_dist / (min_dist.max() + 1e-12)

# Exploration slightly dominates (noise-aware)
score = 0.45 * exploit_score + 0.55 * explore_score

# -------------------------------------------------
# 6. Select next query
# -------------------------------------------------

next_query = candidates[np.argmax(score)]

# -------------------------------------------------
# 7. Format for portal
# -------------------------------------------------

query_string = "-".join([f"{v:0.6f}" for v in next_query])

print("Next query:")
print(query_string)


Dataset shape: (15, 2)
Number of top points: 5
Next query:
0.872215-0.378675
