In [2]:
#Load packages required for loading the npy files.
import numpy as np
import pandas as pd

# #Load the npy file called "data.npy"
Initial_input_data = np.load("/Users/mayukotakamiya/MachineLearning/initial_data/function_1/initial_inputs.npy")
Initial_output_data = np.load("/Users/mayukotakamiya/MachineLearning/initial_data/function_1/initial_outputs.npy")

#I want to know dimentionality of the initial_input_data  
Initial_input_data.shape




(10, 2)

In [84]:

# X and y already loaded
X = Initial_input_data
y = Initial_output_data

def propose_next_point(X, y, n_candidates=8000, w_exploit=0.6, w_explore=0.4, seed=42):
    """
    Simple explore/exploit heuristic:
    - exploit: sample near best observed point
    - explore: sample far from existing samples
    """

    rng = np.random.default_rng(seed)
    n, d = X.shape

    # Best observed point so far
    best_x = X[np.argmax(y)]

    # Determine sampling bounds from existing data
    lower_bounds = X.min(axis=0)
    upper_bounds = X.max(axis=0)

    # Generate random candidate points within observed bounds
    C = rng.uniform(lower_bounds, upper_bounds, size=(n_candidates, d))

    # Exploitation term (closer to best is better)
    dist_to_best = np.linalg.norm(C - best_x, axis=1)
    exploit = 1 - (dist_to_best / (dist_to_best.max() + 1e-12))

    # Exploration term (farther from existing points is better)
    dists = np.sqrt(((C[:, None, :] - X[None, :, :]) ** 2).sum(axis=2))
    min_dist = dists.min(axis=1)
    explore = min_dist / (min_dist.max() + 1e-12)

    # Combined score
    score = w_exploit * exploit + w_explore * explore

    return C[np.argmax(score)]

def format_query(x):
    return "-".join([f"{v:0.6f}" for v in x])

# Generate next query
next_x = propose_next_point(X, y)

print("Submit this to the portal:")
print(format_query(next_x))

Submit this to the portal:
0.433534-0.458467


In [3]:
###WEEK 2
#I want to see the data in /Users/mayukotakamiya/MachineLearning/initial_data/function_1/initial_inputs.npy
print(Initial_input_data)
#I WANT TO create a new npy file by adding a new data point which is [0.433534 0.458467]
new_data_point = np.array([[0.433534, 0.458467]])
Combined_input_data = np.concatenate((Initial_input_data, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_1/W2_inputs.npy", Combined_input_data)
print(Combined_input_data)

[[0.31940389 0.76295937]
 [0.57432921 0.8798981 ]
 [0.73102363 0.73299988]
 [0.84035342 0.26473161]
 [0.65011406 0.68152635]
 [0.41043714 0.1475543 ]
 [0.31269116 0.07872278]
 [0.68341817 0.86105746]
 [0.08250725 0.40348751]
 [0.88388983 0.58225397]]
[[0.31940389 0.76295937]
 [0.57432921 0.8798981 ]
 [0.73102363 0.73299988]
 [0.84035342 0.26473161]
 [0.65011406 0.68152635]
 [0.41043714 0.1475543 ]
 [0.31269116 0.07872278]
 [0.68341817 0.86105746]
 [0.08250725 0.40348751]
 [0.88388983 0.58225397]
 [0.433534   0.458467  ]]


In [4]:
print(Initial_output_data)

#I want to create a new npy file bt adding a new data point to the Initial_output_data
new_output_data_point = np.array([0.007087524491952269])
Combined_output_data = np.concatenate((Initial_output_data, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_1/W2_outputs.npy", Combined_output_data)

print(Combined_output_data)

[ 1.32267704e-079  1.03307824e-046  7.71087511e-016  3.34177101e-124
 -3.60606264e-003 -2.15924904e-054 -2.08909327e-091  2.53500115e-040
  3.60677119e-081  6.22985647e-048]
[ 1.32267704e-079  1.03307824e-046  7.71087511e-016  3.34177101e-124
 -3.60606264e-003 -2.15924904e-054 -2.08909327e-091  2.53500115e-040
  3.60677119e-081  6.22985647e-048  7.08752449e-003]


In [87]:
#Assess the exploitation vs exploration strategy
x=Combined_input_data
y=Combined_output_data

best_score_w2= np.max(y)
improvement= best_score_w2 - np.max(Initial_output_data)

print("Improvement:", improvement)
print("Output range:", y.min(), "to", y.max())
print("Std deviation:", np.std(y))


Improvement: 0.007087524491951498
Output range: -0.0036060626443634764 to 0.007087524491952269
Std deviation: 0.002376682573738607


In [ ]:
##Function1- For week2, it seems there is a big improvement by having the improvement more than 10% of the output range. Therefore, more exploitation than exploration.
##Function2- For week2, no improvement at all. Therefore use more exploration than exploitation
##Function3- for week2, no improvement at all.Therefore use more exploration than exploitation. 
##Function4- for week2, no improvement at all.Therefore use more exploration than exploitation. 
##Function5- for week2, no improvement at all.Therefore use more exploration than exploitation. 
##Function6- for week2, no improvement at all.Therefore use more exploration than exploitation. 
##Function7- for week2, no improvement at all.Therefore use more exploration than exploitation. 
#Function8- for week2, there is small-moderate improvement. Take a balanced approach (6:4)

In [88]:
#Re-run the loop
X=Combined_input_data
y=Combined_output_data

def propose_next_point(X, y, n_candidates=8000, w_exploit=0.75, w_explore=0.25, seed=234):
    """
    Simple explore/exploit heuristic:
    - exploit: sample near best observed point
    - explore: sample far from existing samples
    """

    rng = np.random.default_rng(seed)
    n, d = X.shape

    # Best observed point so far
    best_x = X[np.argmax(y)]
    
    radius = 0.05  # small local refinement

    # Determine sampling bounds from existing data
    lower = np.maximum(best_x - radius, X.min(axis=0))
    upper = np.minimum(best_x + radius, X.max(axis=0))


    # Generate random candidate points within observed bounds
    C = rng.uniform(lower, upper, size=(n_candidates, d))

    # Exploitation term (closer to best is better)
    dist_to_best = np.linalg.norm(C - best_x, axis=1)
    exploit = 1 - (dist_to_best / (dist_to_best.max() + 1e-12))

    # Exploration term (farther from existing points is better)
    dists = np.sqrt(((C[:, None, :] - X[None, :, :]) ** 2).sum(axis=2))
    min_dist = dists.min(axis=1)
    explore = min_dist / (min_dist.max() + 1e-12)

    # Combined score
    score = w_exploit * exploit + w_explore * explore

    return C[np.argmax(score)]

def format_query(x):
    return "-".join([f"{v:0.6f}" for v in x])

# Generate next query
next_x = propose_next_point(X, y)

print("Submit this to the portal:")
print(format_query(next_x))

Submit this to the portal:
0.433582-0.457940


In [5]:
####WEEK 3
new_data_point = np.array([[0.434285, 0.458885]])
Combined_input_data3 = np.concatenate((Combined_input_data, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_1/W3_inputs.npy", Combined_input_data3)
print(Combined_input_data3)

new_output_data_point = np.array([0.005251741633542124])
Combined_output_data3 = np.concatenate((Combined_output_data, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_1/W3_outputs.npy", Combined_output_data3)

print(Combined_output_data3)


[[0.31940389 0.76295937]
 [0.57432921 0.8798981 ]
 [0.73102363 0.73299988]
 [0.84035342 0.26473161]
 [0.65011406 0.68152635]
 [0.41043714 0.1475543 ]
 [0.31269116 0.07872278]
 [0.68341817 0.86105746]
 [0.08250725 0.40348751]
 [0.88388983 0.58225397]
 [0.433534   0.458467  ]
 [0.434285   0.458885  ]]
[ 1.32267704e-079  1.03307824e-046  7.71087511e-016  3.34177101e-124
 -3.60606264e-003 -2.15924904e-054 -2.08909327e-091  2.53500115e-040
  3.60677119e-081  6.22985647e-048  7.08752449e-003  5.25174163e-003]


In [6]:
#WEEK 3 Assess the exploitation vs exploration strategy
x=Combined_input_data3
y=Combined_output_data3

best_score_w2= np.max(y)
improvement= best_score_w2 - np.max(Combined_output_data)

print("Improvement:", improvement)
print("Output range:", y.min(), "to", y.max())
print("Std deviation:", np.std(y))

Improvement: 0.0
Output range: -0.0036060626443634764 to 0.007087524491952269
Std deviation: 0.002653013137364431


In [7]:
#WEEK 3 -re run the loop. No improvement so adjust exploit vs explore ratio to 0.45:0.55
X=Combined_input_data3
y=Combined_output_data3

def propose_next_point(X, y, n_candidates=8000, w_exploit=0.45, w_explore=0.55, seed=234):

    rng = np.random.default_rng(seed)
    n, d = X.shape

    # Best observed point so far
    best_x = X[np.argmax(y)]
    
    radius = 0.05  # small local refinement

    # Determine sampling bounds from existing data
    lower = np.maximum(best_x - radius, X.min(axis=0))
    upper = np.minimum(best_x + radius, X.max(axis=0))


    # Generate random candidate points within observed bounds
    C = rng.uniform(lower, upper, size=(n_candidates, d))

    # Exploitation term (closer to best is better)
    dist_to_best = np.linalg.norm(C - best_x, axis=1)
    exploit = 1 - (dist_to_best / (dist_to_best.max() + 1e-12))

    # Exploration term (farther from existing points is better)
    dists = np.sqrt(((C[:, None, :] - X[None, :, :]) ** 2).sum(axis=2))
    min_dist = dists.min(axis=1)
    explore = min_dist / (min_dist.max() + 1e-12)

    # Combined score
    score = w_exploit * exploit + w_explore * explore

    return C[np.argmax(score)]

def format_query(x):
    return "-".join([f"{v:0.6f}" for v in x])

# Generate next query
next_x = propose_next_point(X, y)

print("Submit this to the portal:")
print(format_query(next_x))

Submit this to the portal:
0.383616-0.409388


In [8]:
####WEEK 4
new_data_point = np.array([[0.383616, 0.409388]])
Combined_input_data4 = np.concatenate((Combined_input_data3, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_1/W4_inputs.npy", Combined_input_data4)
print(Combined_input_data4)

new_output_data_point = np.array([0.004042733938041736])
Combined_output_data4 = np.concatenate((Combined_output_data3, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_1/W4_outputs.npy", Combined_output_data4)

print(Combined_output_data4)

[[0.31940389 0.76295937]
 [0.57432921 0.8798981 ]
 [0.73102363 0.73299988]
 [0.84035342 0.26473161]
 [0.65011406 0.68152635]
 [0.41043714 0.1475543 ]
 [0.31269116 0.07872278]
 [0.68341817 0.86105746]
 [0.08250725 0.40348751]
 [0.88388983 0.58225397]
 [0.433534   0.458467  ]
 [0.434285   0.458885  ]
 [0.383616   0.409388  ]]
[ 1.32267704e-079  1.03307824e-046  7.71087511e-016  3.34177101e-124
 -3.60606264e-003 -2.15924904e-054 -2.08909327e-091  2.53500115e-040
  3.60677119e-081  6.22985647e-048  7.08752449e-003  5.25174163e-003
  4.04273394e-003]


In [9]:
#WEEK 4 Assess the exploitation vs exploration strategy
x=Combined_input_data4
y=Combined_output_data4

best_score_w2= np.max(y)
improvement= best_score_w2 - np.max(Combined_output_data3)

print("Improvement:", improvement)
print("Output range:", y.min(), "to", y.max())
print("Std deviation:", np.std(y))

Improvement: 0.0
Output range: -0.0036060626443634764 to 0.007087524491952269
Std deviation: 0.0026976548563347465


In [10]:
#WEEK 4 -re run the loop. No improvement so adjust exploit vs explore ratio to 0.45:0.55
X=Combined_input_data4
y=Combined_output_data4

def propose_next_point(X, y, n_candidates=8000, w_exploit=0.45, w_explore=0.55, seed=100):

    rng = np.random.default_rng(seed)
    n, d = X.shape

    # Best observed point so far
    best_x = X[np.argmax(y)]
    
    radius = 0.05  # small local refinement

    # Determine sampling bounds from existing data
    lower = np.maximum(best_x - radius, X.min(axis=0))
    upper = np.minimum(best_x + radius, X.max(axis=0))


    # Generate random candidate points within observed bounds
    C = rng.uniform(lower, upper, size=(n_candidates, d))

    # Exploitation term (closer to best is better)
    dist_to_best = np.linalg.norm(C - best_x, axis=1)
    exploit = 1 - (dist_to_best / (dist_to_best.max() + 1e-12))

    # Exploration term (farther from existing points is better)
    dists = np.sqrt(((C[:, None, :] - X[None, :, :]) ** 2).sum(axis=2))
    min_dist = dists.min(axis=1)
    explore = min_dist / (min_dist.max() + 1e-12)

    # Combined score
    score = w_exploit * exploit + w_explore * explore
    return C[np.argmax(score)]

def format_query(x):
    return "-".join([f"{v:0.6f}" for v in x])

# Generate next query
next_x = propose_next_point(X, y)

print("Submit this to the portal:")
print(format_query(next_x))

Submit this to the portal:
0.383914-0.507406


In [11]:
#WEEK 5 
new_data_point = np.array([[0.383914, 0.507406]])
Combined_input_data5 = np.concatenate((Combined_input_data4, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_1/W5_inputs.npy", Combined_input_data5)
print(Combined_input_data5)

new_output_data_point = np.array([-5.0871855063036176e-8])
Combined_output_data5 = np.concatenate((Combined_output_data4, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_1/W5_outputs.npy", Combined_output_data5)

print(Combined_output_data5)

[[0.31940389 0.76295937]
 [0.57432921 0.8798981 ]
 [0.73102363 0.73299988]
 [0.84035342 0.26473161]
 [0.65011406 0.68152635]
 [0.41043714 0.1475543 ]
 [0.31269116 0.07872278]
 [0.68341817 0.86105746]
 [0.08250725 0.40348751]
 [0.88388983 0.58225397]
 [0.433534   0.458467  ]
 [0.434285   0.458885  ]
 [0.383616   0.409388  ]
 [0.383914   0.507406  ]]
[ 1.32267704e-079  1.03307824e-046  7.71087511e-016  3.34177101e-124
 -3.60606264e-003 -2.15924904e-054 -2.08909327e-091  2.53500115e-040
  3.60677119e-081  6.22985647e-048  7.08752449e-003  5.25174163e-003
  4.04273394e-003 -5.08718551e-008]


In [12]:
##Week 5 focuses on local search around the best point, keeps some exploration, avoids duplicate queries, adapts to your observed data
import numpy as np

X = Combined_input_data5
y = Combined_output_data5

print("Dataset shape:", X.shape)

best_idx = np.argmax(y)
best_x = X[best_idx]

print("Best point so far:", best_x)
print("Best value:", y[best_idx])

rng = np.random.default_rng(42)

lower = X.min(axis=0)
upper = X.max(axis=0)

# --- Local candidates (exploitation) ---
local_candidates = rng.normal(loc=best_x, scale=0.05, size=(2000, 2))

# --- Global candidates (exploration) ---
global_candidates = rng.uniform(lower, upper, size=(2000, 2))

# Combine
candidates = np.vstack([local_candidates, global_candidates])

# Clip to bounds
candidates = np.clip(candidates, lower, upper)

dist = np.sqrt(((candidates[:, None, :] - X[None, :, :])**2).sum(axis=2))
min_dist = dist.min(axis=1)

mask = min_dist > 0.01
candidates = candidates[mask]

# Exploitation: distance to best point (closer is better)
dist_to_best = np.linalg.norm(candidates - best_x, axis=1)
exploit_score = 1 - dist_to_best / (dist_to_best.max() + 1e-12)

# Exploration: distance from existing points (farther is better)
explore_score = min_dist[mask]
explore_score = explore_score / (explore_score.max() + 1e-12)

# Balanced score (slightly exploration-focused since last improvement may have stalled)
score = 0.45 * exploit_score + 0.55 * explore_score

next_query = candidates[np.argmax(score)]

query_string = "-".join([f"{v:0.6f}" for v in next_query])

print("Next query:")
print(query_string)

Dataset shape: (14, 2)
Best point so far: [0.433534 0.458467]
Best value: 0.007087524491952269
Next query:
0.674312-0.431524


In [13]:
#WEEK 6
new_data_point = np.array([[0.674312, 0.431524]])
Combined_input_data6 = np.concatenate((Combined_input_data5, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_1/W6_inputs.npy", Combined_input_data6)
print(Combined_input_data6)

new_output_data_point = np.array([5.12277145464331e-31])
Combined_output_data6 = np.concatenate((Combined_output_data5, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_1/W6_outputs.npy", Combined_output_data6)

print(Combined_output_data6)

[[0.31940389 0.76295937]
 [0.57432921 0.8798981 ]
 [0.73102363 0.73299988]
 [0.84035342 0.26473161]
 [0.65011406 0.68152635]
 [0.41043714 0.1475543 ]
 [0.31269116 0.07872278]
 [0.68341817 0.86105746]
 [0.08250725 0.40348751]
 [0.88388983 0.58225397]
 [0.433534   0.458467  ]
 [0.434285   0.458885  ]
 [0.383616   0.409388  ]
 [0.383914   0.507406  ]
 [0.674312   0.431524  ]]
[ 1.32267704e-079  1.03307824e-046  7.71087511e-016  3.34177101e-124
 -3.60606264e-003 -2.15924904e-054 -2.08909327e-091  2.53500115e-040
  3.60677119e-081  6.22985647e-048  7.08752449e-003  5.25174163e-003
  4.04273394e-003 -5.08718551e-008  5.12277145e-031]


In [14]:
##WEEK 6
#Focus near the current best point (refinement)
#Keep some exploration (avoid local trap)
#Reduce randomness compared to earlier rounds
#Avoid neural networks (unnecessary complexity)

X = Combined_input_data6
y = Combined_output_data6

print("Dataset shape:", X.shape)

# -------------------------------------------------
# 2. Identify best point
# -------------------------------------------------

best_idx = np.argmax(y)
best_x = X[best_idx]

print("Best value:", y[best_idx])
print("Best point:", best_x)

# -------------------------------------------------
# 3. Generate candidate points
# -------------------------------------------------

rng = np.random.default_rng(123)  # new seed to avoid duplicates

lower = X.min(axis=0)
upper = X.max(axis=0)

# Local refinement (main focus)
local_candidates = rng.normal(loc=best_x, scale=0.03, size=(3000, 2))
local_candidates = np.clip(local_candidates, lower, upper)

# Moderate global exploration
global_candidates = rng.uniform(lower, upper, size=(2000, 2))

# Combine candidates
candidates = np.vstack([local_candidates, global_candidates])

# -------------------------------------------------
# 4. Remove near-duplicate candidates
# -------------------------------------------------

dist = np.sqrt(((candidates[:, None, :] - X[None, :, :])**2).sum(axis=2))
min_dist = dist.min(axis=1)

mask = min_dist > 0.01
candidates = candidates[mask]
min_dist = min_dist[mask]

# -------------------------------------------------
# 5. Score candidates
# -------------------------------------------------

# Exploitation: closeness to best point
dist_to_best = np.linalg.norm(candidates - best_x, axis=1)
exploit_score = 1 - dist_to_best / (dist_to_best.max() + 1e-12)

# Exploration: distance from known points
explore_score = min_dist / (min_dist.max() + 1e-12)

# Balanced but slightly exploit-focused (Query 6)
score = 0.6 * exploit_score + 0.4 * explore_score

# -------------------------------------------------
# 6. Select next query
# -------------------------------------------------

next_query = candidates[np.argmax(score)]

# -------------------------------------------------
# 7. Format for portal
# -------------------------------------------------

query_string = "-".join([f"{v:0.6f}" for v in next_query])

print("Next query:")
print(query_string)

Dataset shape: (15, 2)
Best value: 0.007087524491952269
Best point: [0.433534 0.458467]
Next query:
0.538921-0.302247
