In [1]:
#Load packages required for loading the npy files.
import numpy as np
import pandas as pd

# #Load the npy file called "data.npy"
Initial_input_data = np.load("/Users/mayukotakamiya/MachineLearning/initial_data/function_5/initial_inputs.npy")
Initial_output_data = np.load("/Users/mayukotakamiya/MachineLearning/initial_data/function_5/initial_outputs.npy")

#I want to know dimentionality of the initial_input_data  
Initial_input_data.shape




(20, 4)

In [2]:

# X and y already loaded
X = Initial_input_data
y = Initial_output_data

def propose_next_point(X, y, n_candidates=8000, w_exploit=0.6, w_explore=0.4, seed=42):
    """
    Simple explore/exploit heuristic:
    - exploit: sample near best observed point
    - explore: sample far from existing samples
    """

    rng = np.random.default_rng(seed)
    n, d = X.shape

    # Best observed point so far
    best_x = X[np.argmax(y)]

    # Determine sampling bounds from existing data
    lower_bounds = X.min(axis=0)
    upper_bounds = X.max(axis=0)

    # Generate random candidate points within observed bounds
    C = rng.uniform(lower_bounds, upper_bounds, size=(n_candidates, d))

    # Exploitation term (closer to best is better)
    dist_to_best = np.linalg.norm(C - best_x, axis=1)
    exploit = 1 - (dist_to_best / (dist_to_best.max() + 1e-12))

    # Exploration term (farther from existing points is better)
    dists = np.sqrt(((C[:, None, :] - X[None, :, :]) ** 2).sum(axis=2))
    min_dist = dists.min(axis=1)
    explore = min_dist / (min_dist.max() + 1e-12)

    # Combined score
    score = w_exploit * exploit + w_explore * explore

    return C[np.argmax(score)]

def format_query(x):
    return "-".join([f"{v:0.6f}" for v in x])

# Generate next query
next_x = propose_next_point(X, y)

print("Submit this to the portal:")
print(format_query(next_x))

Submit this to the portal:
0.145970-0.921486


In [2]:
###WEEK 2
#I want to see the data in /Users/mayukotakamiya/MachineLearning/initial_data/function_1/initial_inputs.npy
print(Initial_input_data)
#I WANT TO create a new npy file by adding a new data point which is [0.433534 0.458467]
new_data_point = np.array([[0.126202, 0.238120, 0.862452, 0.947971]])
Combined_input_data = np.concatenate((Initial_input_data, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_5/W2_inputs.npy", Combined_input_data)
print(Combined_input_data)

[[0.19144708 0.03819337 0.60741781 0.41458414]
 [0.75865295 0.53651774 0.65600038 0.36034155]
 [0.43834987 0.8043397  0.21024527 0.15129482]
 [0.70605083 0.53419196 0.26424335 0.48208755]
 [0.83647799 0.19360965 0.6638927  0.78564888]
 [0.68343225 0.11866264 0.82904591 0.56757661]
 [0.55362148 0.66734998 0.32380582 0.81486975]
 [0.35235627 0.32224153 0.11697937 0.47311252]
 [0.15378571 0.72938169 0.42259844 0.44307417]
 [0.46344227 0.63002451 0.10790646 0.9576439 ]
 [0.67749115 0.35850951 0.47959222 0.07288048]
 [0.58397341 0.14724265 0.34809746 0.42861465]
 [0.30688872 0.31687813 0.62263448 0.09539906]
 [0.51114177 0.817957   0.72871042 0.11235362]
 [0.43893338 0.77409176 0.37816709 0.93369621]
 [0.22418902 0.84648049 0.87948418 0.87851568]
 [0.72526172 0.47987049 0.08894684 0.75976022]
 [0.35548161 0.63961937 0.41761768 0.12260384]
 [0.11987923 0.86254031 0.64333133 0.84980383]
 [0.12688467 0.15342962 0.77016219 0.19051811]]
[[0.19144708 0.03819337 0.60741781 0.41458414]
 [0.75865295

In [3]:
print(Initial_output_data)

#I want to create a new npy file bt adding a new data point to the Initial_output_data
new_output_data_point = np.array([558.945213159388])
Combined_output_data = np.concatenate((Initial_output_data, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_4/W2_outputs.npy", Combined_output_data)

print(Combined_output_data)

[6.44434399e+01 1.83013796e+01 1.12939795e-01 4.21089813e+00
 2.58370525e+02 7.84343889e+01 5.75715369e+01 1.09571876e+02
 8.84799176e+00 2.33223610e+02 2.44230883e+01 6.44201468e+01
 6.34767158e+01 7.97291299e+01 3.55806818e+02 1.08885962e+03
 2.88667516e+01 4.51815703e+01 4.31612757e+02 9.97233189e+00]
[6.44434399e+01 1.83013796e+01 1.12939795e-01 4.21089813e+00
 2.58370525e+02 7.84343889e+01 5.75715369e+01 1.09571876e+02
 8.84799176e+00 2.33223610e+02 2.44230883e+01 6.44201468e+01
 6.34767158e+01 7.97291299e+01 3.55806818e+02 1.08885962e+03
 2.88667516e+01 4.51815703e+01 4.31612757e+02 9.97233189e+00
 5.58945213e+02]


In [87]:
#Assess the exploitation vs exploration strategy
x=Combined_input_data
y=Combined_output_data

best_score_w2= np.max(y)
improvement= best_score_w2 - np.max(Initial_output_data)

print("Improvement:", improvement)
print("Output range:", y.min(), "to", y.max())
print("Std deviation:", np.std(y))


Improvement: 0.007087524491951498
Output range: -0.0036060626443634764 to 0.007087524491952269
Std deviation: 0.002376682573738607


In [ ]:
##Function1- For week2, it seems there is a big improvement by having the improvement more than 10% of the output range. Therefore, more exploitation than exploration.
##Function2- For week2, no improvement at all. Therefore use more exploration than exploitation
##Function3- for week2, no improvement at all.Therefore use more exploration than exploitation. 
##Function4- for week2, no improvement at all.Therefore use more exploration than exploitation. 
##Function5- for week2, no improvement at all.Therefore use more exploration than exploitation. 
##Function6- for week2, no improvement at all.Therefore use more exploration than exploitation. 
##Function7- for week2, no improvement at all.Therefore use more exploration than exploitation. 
#Function8- for week2, there is small-moderate improvement. Take a balanced approach (6:4)

In [88]:
#Re-run the loop
X=Combined_input_data
y=Combined_output_data

def propose_next_point(X, y, n_candidates=8000, w_exploit=0.75, w_explore=0.25, seed=234):
    """
    Simple explore/exploit heuristic:
    - exploit: sample near best observed point
    - explore: sample far from existing samples
    """

    rng = np.random.default_rng(seed)
    n, d = X.shape

    # Best observed point so far
    best_x = X[np.argmax(y)]
    
    radius = 0.05  # small local refinement

    # Determine sampling bounds from existing data
    lower = np.maximum(best_x - radius, X.min(axis=0))
    upper = np.minimum(best_x + radius, X.max(axis=0))


    # Generate random candidate points within observed bounds
    C = rng.uniform(lower, upper, size=(n_candidates, d))

    # Exploitation term (closer to best is better)
    dist_to_best = np.linalg.norm(C - best_x, axis=1)
    exploit = 1 - (dist_to_best / (dist_to_best.max() + 1e-12))

    # Exploration term (farther from existing points is better)
    dists = np.sqrt(((C[:, None, :] - X[None, :, :]) ** 2).sum(axis=2))
    min_dist = dists.min(axis=1)
    explore = min_dist / (min_dist.max() + 1e-12)

    # Combined score
    score = w_exploit * exploit + w_explore * explore

    return C[np.argmax(score)]

def format_query(x):
    return "-".join([f"{v:0.6f}" for v in x])

# Generate next query
next_x = propose_next_point(X, y)

print("Submit this to the portal:")
print(format_query(next_x))

Submit this to the portal:
0.433582-0.457940


In [4]:
####WEEK 3
new_data_point = np.array([[00.273981, 0.796829, 0.833178, 0.920948]])
Combined_input_data3 = np.concatenate((Combined_input_data, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_5/W3_inputs.npy", Combined_input_data3)
print(Combined_input_data3)

new_output_data_point = np.array([922.8978018634562])
Combined_output_data3 = np.concatenate((Combined_output_data, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_5/W3_outputs.npy", Combined_output_data3)

print(Combined_output_data3)


[[0.19144708 0.03819337 0.60741781 0.41458414]
 [0.75865295 0.53651774 0.65600038 0.36034155]
 [0.43834987 0.8043397  0.21024527 0.15129482]
 [0.70605083 0.53419196 0.26424335 0.48208755]
 [0.83647799 0.19360965 0.6638927  0.78564888]
 [0.68343225 0.11866264 0.82904591 0.56757661]
 [0.55362148 0.66734998 0.32380582 0.81486975]
 [0.35235627 0.32224153 0.11697937 0.47311252]
 [0.15378571 0.72938169 0.42259844 0.44307417]
 [0.46344227 0.63002451 0.10790646 0.9576439 ]
 [0.67749115 0.35850951 0.47959222 0.07288048]
 [0.58397341 0.14724265 0.34809746 0.42861465]
 [0.30688872 0.31687813 0.62263448 0.09539906]
 [0.51114177 0.817957   0.72871042 0.11235362]
 [0.43893338 0.77409176 0.37816709 0.93369621]
 [0.22418902 0.84648049 0.87948418 0.87851568]
 [0.72526172 0.47987049 0.08894684 0.75976022]
 [0.35548161 0.63961937 0.41761768 0.12260384]
 [0.11987923 0.86254031 0.64333133 0.84980383]
 [0.12688467 0.15342962 0.77016219 0.19051811]
 [0.126202   0.23812    0.862452   0.947971  ]
 [0.273981   

In [5]:
#WEEK 3 Assess the exploitation vs exploration strategy
x=Combined_input_data3
y=Combined_output_data3

best_score_w2= np.max(y)
improvement= best_score_w2 - np.max(Combined_output_data)

print("Improvement:", improvement)
print("Output range:", y.min(), "to", y.max())
print("Std deviation:", np.std(y))

Improvement: 0.0
Output range: 0.1129397953712203 to 1088.8596181962705
Std deviation: 294.227772354128


In [6]:
#WEEK 3 -re run the loop. no ate improvement so adjust exploit vs explore ratio to 0.6: 0.4
X=Combined_input_data3
y=Combined_output_data3

def propose_next_point(X, y, n_candidates=8000, w_exploit=0.45, w_explore=0.55, seed=234):

    rng = np.random.default_rng(seed)
    n, d = X.shape

    # Best observed point so far
    best_x = X[np.argmax(y)]
    
    radius = 0.05  # small local refinement

    # Determine sampling bounds from existing data
    lower = np.maximum(best_x - radius, X.min(axis=0))
    upper = np.minimum(best_x + radius, X.max(axis=0))


    # Generate random candidate points within observed bounds
    C = rng.uniform(lower, upper, size=(n_candidates, d))

    # Exploitation term (closer to best is better)
    dist_to_best = np.linalg.norm(C - best_x, axis=1)
    exploit = 1 - (dist_to_best / (dist_to_best.max() + 1e-12))

    # Exploration term (farther from existing points is better)
    dists = np.sqrt(((C[:, None, :] - X[None, :, :]) ** 2).sum(axis=2))
    min_dist = dists.min(axis=1)
    explore = min_dist / (min_dist.max() + 1e-12)

    # Combined score
    score = w_exploit * exploit + w_explore * explore

    return C[np.argmax(score)]

def format_query(x):
    return "-".join([f"{v:0.6f}" for v in x])

# Generate next query
next_x = propose_next_point(X, y)

print("Submit this to the portal:")
print(format_query(next_x))

Submit this to the portal:
0.175011-0.797393-0.836689-0.832844


In [8]:
####WEEK 4
new_data_point = np.array([[0.175011, 0.797393, 0.836689, 0.832844]])
Combined_input_data4 = np.concatenate((Combined_input_data3, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_5/W4_inputs.npy", Combined_input_data4)
print(Combined_input_data4)

new_output_data_point = np.array([588.1179726961976])
Combined_output_data4 = np.concatenate((Combined_output_data3, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_5/W4_outputs.npy", Combined_output_data4)

print(Combined_output_data4)

[[0.19144708 0.03819337 0.60741781 0.41458414]
 [0.75865295 0.53651774 0.65600038 0.36034155]
 [0.43834987 0.8043397  0.21024527 0.15129482]
 [0.70605083 0.53419196 0.26424335 0.48208755]
 [0.83647799 0.19360965 0.6638927  0.78564888]
 [0.68343225 0.11866264 0.82904591 0.56757661]
 [0.55362148 0.66734998 0.32380582 0.81486975]
 [0.35235627 0.32224153 0.11697937 0.47311252]
 [0.15378571 0.72938169 0.42259844 0.44307417]
 [0.46344227 0.63002451 0.10790646 0.9576439 ]
 [0.67749115 0.35850951 0.47959222 0.07288048]
 [0.58397341 0.14724265 0.34809746 0.42861465]
 [0.30688872 0.31687813 0.62263448 0.09539906]
 [0.51114177 0.817957   0.72871042 0.11235362]
 [0.43893338 0.77409176 0.37816709 0.93369621]
 [0.22418902 0.84648049 0.87948418 0.87851568]
 [0.72526172 0.47987049 0.08894684 0.75976022]
 [0.35548161 0.63961937 0.41761768 0.12260384]
 [0.11987923 0.86254031 0.64333133 0.84980383]
 [0.12688467 0.15342962 0.77016219 0.19051811]
 [0.126202   0.23812    0.862452   0.947971  ]
 [0.273981   

In [9]:
##WEEK 4 - NN + local optimisation

import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPRegressor

# -------------------------------------------------
# 1. Load dataset (after previous queries)
# -------------------------------------------------

X = Combined_input_data4
y = Combined_output_data4

print("Dataset shape:", X.shape)

# -------------------------------------------------
# 2. Scale inputs
# -------------------------------------------------

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# -------------------------------------------------
# 3. Train neural network surrogate
# -------------------------------------------------

model = MLPRegressor(
    hidden_layer_sizes=(16,8),
    activation="relu",
    solver="adam",
    max_iter=2000,
    random_state=42
)

model.fit(X_scaled, y)

# -------------------------------------------------
# 4. Identify current best point
# -------------------------------------------------

best_idx = np.argmax(y)
best_x = X[best_idx]

print("Current best point:", best_x)

# -------------------------------------------------
# 5. Generate candidate points
# -------------------------------------------------

rng = np.random.default_rng(42)

# local candidates around best point
local_candidates = rng.normal(best_x, 0.05, size=(4000, X.shape[1]))

# global candidates (exploration)
lower = X.min(axis=0)
upper = X.max(axis=0)

global_candidates = rng.uniform(lower, upper, size=(4000, X.shape[1]))

candidates = np.vstack([local_candidates, global_candidates])

# clip values to valid range
candidates = np.clip(candidates, lower, upper)

# -------------------------------------------------
# 6. Avoid querying points too close to existing ones
# -------------------------------------------------

dist = np.sqrt(((candidates[:,None,:] - X[None,:,:])**2).sum(axis=2))
min_dist = dist.min(axis=1)

mask = min_dist > 0.01
candidates = candidates[mask]

# -------------------------------------------------
# 7. Predict outputs using the neural network
# -------------------------------------------------

candidates_scaled = scaler.transform(candidates)

predictions = model.predict(candidates_scaled)

# -------------------------------------------------
# 8. Choose best predicted candidate
# -------------------------------------------------

best_candidate = candidates[np.argmax(predictions)]

# -------------------------------------------------
# 9. Format query for portal
# -------------------------------------------------

query_string = "-".join([f"{v:0.6f}" for v in best_candidate])

print("Next query:")
print(query_string)

Dataset shape: (23, 4)
Current best point: [0.22418902 0.84648049 0.87948418 0.87851568]
Next query:
0.119879-0.862540-0.879484-0.957644


/Users/mayukotakamiya/miniforge3/envs/tf-metal/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (2000) reached and the optimization hasn't converged yet.
  warnings.warn(


In [10]:
#WEEK 5 
new_data_point = np.array([[0.119879, 0.862540, 0.879484, 0.957644]])
Combined_input_data5 = np.concatenate((Combined_input_data4, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_5/W5_inputs.npy", Combined_input_data5)
print(Combined_input_data5)

new_output_data_point = np.array([1630.067549659214])
Combined_output_data5 = np.concatenate((Combined_output_data4, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_5/W5_outputs.npy", Combined_output_data5)

print(Combined_output_data5)

[[0.19144708 0.03819337 0.60741781 0.41458414]
 [0.75865295 0.53651774 0.65600038 0.36034155]
 [0.43834987 0.8043397  0.21024527 0.15129482]
 [0.70605083 0.53419196 0.26424335 0.48208755]
 [0.83647799 0.19360965 0.6638927  0.78564888]
 [0.68343225 0.11866264 0.82904591 0.56757661]
 [0.55362148 0.66734998 0.32380582 0.81486975]
 [0.35235627 0.32224153 0.11697937 0.47311252]
 [0.15378571 0.72938169 0.42259844 0.44307417]
 [0.46344227 0.63002451 0.10790646 0.9576439 ]
 [0.67749115 0.35850951 0.47959222 0.07288048]
 [0.58397341 0.14724265 0.34809746 0.42861465]
 [0.30688872 0.31687813 0.62263448 0.09539906]
 [0.51114177 0.817957   0.72871042 0.11235362]
 [0.43893338 0.77409176 0.37816709 0.93369621]
 [0.22418902 0.84648049 0.87948418 0.87851568]
 [0.72526172 0.47987049 0.08894684 0.75976022]
 [0.35548161 0.63961937 0.41761768 0.12260384]
 [0.11987923 0.86254031 0.64333133 0.84980383]
 [0.12688467 0.15342962 0.77016219 0.19051811]
 [0.126202   0.23812    0.862452   0.947971  ]
 [0.273981   

In [11]:
#WEEK 5- Use a neural network (moderate depth), Focus more on local refinement, Still include global candidates, Slightly exploit-heavy scoring

import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPRegressor

# -------------------------------------------------
# 1. Load dataset
# -------------------------------------------------

X = Combined_input_data5
y = Combined_output_data5

print("Dataset shape:", X.shape)

# -------------------------------------------------
# 2. Scale inputs
# -------------------------------------------------

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# -------------------------------------------------
# 3. Train neural network surrogate
# -------------------------------------------------

model = MLPRegressor(
    hidden_layer_sizes=(24, 12),
    activation="relu",
    solver="adam",
    max_iter=2500,
    random_state=42
)

model.fit(X_scaled, y)

# -------------------------------------------------
# 4. Identify best point
# -------------------------------------------------

best_idx = np.argmax(y)
best_x = X[best_idx]

print("Best value:", y[best_idx])
print("Best point:", best_x)

# -------------------------------------------------
# 5. Generate candidate points
# -------------------------------------------------

rng = np.random.default_rng(42)

lower = X.min(axis=0)
upper = X.max(axis=0)

# Strong local refinement (main focus)
local_candidates = rng.normal(loc=best_x, scale=0.03, size=(6000, 4))
local_candidates = np.clip(local_candidates, lower, upper)

# Small global exploration
global_candidates = rng.uniform(lower, upper, size=(2000, 4))

# Combine
candidates = np.vstack([local_candidates, global_candidates])

# -------------------------------------------------
# 6. Remove near-duplicate candidates
# -------------------------------------------------

dist = np.sqrt(((candidates[:, None, :] - X[None, :, :])**2).sum(axis=2))
min_dist = dist.min(axis=1)

mask = min_dist > 0.01
candidates = candidates[mask]
min_dist = min_dist[mask]

# -------------------------------------------------
# 7. Predict outputs
# -------------------------------------------------

candidates_scaled = scaler.transform(candidates)
predictions = model.predict(candidates_scaled)

# -------------------------------------------------
# 8. Scoring (exploit-heavy)
# -------------------------------------------------

explore_score = min_dist / (min_dist.max() + 1e-12)

# Strong exploitation because unimodal
score = predictions + 0.05 * explore_score

# -------------------------------------------------
# 9. Select next query
# -------------------------------------------------

next_query = candidates[np.argmax(score)]

# -------------------------------------------------
# 10. Format for portal
# -------------------------------------------------

query_string = "-".join([f"{v:0.6f}" for v in next_query])

print("Next query:")
print(query_string)

Dataset shape: (24, 4)
Best value: 1630.067549659214
Best point: [0.119879 0.86254  0.879484 0.957644]
Next query:
0.129885-0.862540-0.879484-0.957644


/Users/mayukotakamiya/miniforge3/envs/tf-metal/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (2500) reached and the optimization hasn't converged yet.
  warnings.warn(


In [12]:
#WEEK 6
new_data_point = np.array([[0.119879, 0.862540, 0.879484, 0.957644]])
Combined_input_data6 = np.concatenate((Combined_input_data5, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_5/W6_inputs.npy", Combined_input_data6)
print(Combined_input_data6)

new_output_data_point = np.array([1630.067549659214])
Combined_output_data6 = np.concatenate((Combined_output_data5, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_5/W6_outputs.npy", Combined_output_data6)

print(Combined_output_data6)

[[0.19144708 0.03819337 0.60741781 0.41458414]
 [0.75865295 0.53651774 0.65600038 0.36034155]
 [0.43834987 0.8043397  0.21024527 0.15129482]
 [0.70605083 0.53419196 0.26424335 0.48208755]
 [0.83647799 0.19360965 0.6638927  0.78564888]
 [0.68343225 0.11866264 0.82904591 0.56757661]
 [0.55362148 0.66734998 0.32380582 0.81486975]
 [0.35235627 0.32224153 0.11697937 0.47311252]
 [0.15378571 0.72938169 0.42259844 0.44307417]
 [0.46344227 0.63002451 0.10790646 0.9576439 ]
 [0.67749115 0.35850951 0.47959222 0.07288048]
 [0.58397341 0.14724265 0.34809746 0.42861465]
 [0.30688872 0.31687813 0.62263448 0.09539906]
 [0.51114177 0.817957   0.72871042 0.11235362]
 [0.43893338 0.77409176 0.37816709 0.93369621]
 [0.22418902 0.84648049 0.87948418 0.87851568]
 [0.72526172 0.47987049 0.08894684 0.75976022]
 [0.35548161 0.63961937 0.41761768 0.12260384]
 [0.11987923 0.86254031 0.64333133 0.84980383]
 [0.12688467 0.15342962 0.77016219 0.19051811]
 [0.126202   0.23812    0.862452   0.947971  ]
 [0.273981   

In [13]:
##WEEK 6 
#Use a neural network surrogate
#Strong local refinement (since unimodal)
#Minimal but necessary exploration
#Slightly exploit-heavy scoring

import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPRegressor

# -------------------------------------------------
# 1. Load dataset
# -------------------------------------------------

X = Combined_input_data6
y = Combined_output_data6

print("Dataset shape:", X.shape)

# -------------------------------------------------
# 2. Scale inputs
# -------------------------------------------------

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# -------------------------------------------------
# 3. Train neural network surrogate
# -------------------------------------------------

model = MLPRegressor(
    hidden_layer_sizes=(24, 12),
    activation="relu",
    solver="adam",
    alpha=1e-3,                 # regularisation
    max_iter=3000,
    random_state=42
)

model.fit(X_scaled, y)

# -------------------------------------------------
# 4. Identify best point
# -------------------------------------------------

best_idx = np.argmax(y)
best_x = X[best_idx]

print("Best value:", y[best_idx])
print("Best point:", best_x)

# -------------------------------------------------
# 5. Generate candidate points
# -------------------------------------------------

rng = np.random.default_rng(123)

lower = X.min(axis=0)
upper = X.max(axis=0)

# Strong local refinement (main focus)
local_candidates = rng.normal(loc=best_x, scale=0.025, size=(7000, 4))
local_candidates = np.clip(local_candidates, lower, upper)

# Small global exploration
global_candidates = rng.uniform(lower, upper, size=(2000, 4))

# Combine candidates
candidates = np.vstack([local_candidates, global_candidates])

# -------------------------------------------------
# 6. Remove near-duplicate candidates
# -------------------------------------------------

dist = np.sqrt(((candidates[:, None, :] - X[None, :, :])**2).sum(axis=2))
min_dist = dist.min(axis=1)

mask = min_dist > 0.01
candidates = candidates[mask]
min_dist = min_dist[mask]

# -------------------------------------------------
# 7. Predict outputs
# -------------------------------------------------

candidates_scaled = scaler.transform(candidates)
predictions = model.predict(candidates_scaled)

# -------------------------------------------------
# 8. Exploit-heavy scoring
# -------------------------------------------------

explore_score = min_dist / (min_dist.max() + 1e-12)

# Strong exploitation (unimodal assumption)
score = predictions + 0.05 * explore_score

# -------------------------------------------------
# 9. Select next query
# -------------------------------------------------

next_query = candidates[np.argmax(score)]

# -------------------------------------------------
# 10. Format for portal
# -------------------------------------------------

query_string = "-".join([f"{v:0.6f}" for v in next_query])

print("Next query:")
print(query_string)

Dataset shape: (25, 4)
Best value: 1630.067549659214
Best point: [0.119879 0.86254  0.879484 0.957644]
Next query:
0.129929-0.862540-0.879484-0.957644


/Users/mayukotakamiya/miniforge3/envs/tf-metal/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (3000) reached and the optimization hasn't converged yet.
  warnings.warn(
