In [1]:
#Load packages required for loading the npy files.
import numpy as np
import pandas as pd

# #Load the npy file called "data.npy"
Initial_input_data = np.load("/Users/mayukotakamiya/MachineLearning/initial_data/function_7/initial_inputs.npy")
Initial_output_data = np.load("/Users/mayukotakamiya/MachineLearning/initial_data/function_7/initial_outputs.npy")

#I want to know dimentionality of the initial_input_data  
Initial_input_data.shape




(30, 6)

In [2]:

# X and y already loaded
X = Initial_input_data
y = Initial_output_data

def propose_next_point(X, y, n_candidates=8000, w_exploit=0.6, w_explore=0.4, seed=42):
    """
    Simple explore/exploit heuristic:
    - exploit: sample near best observed point
    - explore: sample far from existing samples
    """

    rng = np.random.default_rng(seed)
    n, d = X.shape

    # Best observed point so far
    best_x = X[np.argmax(y)]

    # Determine sampling bounds from existing data
    lower_bounds = X.min(axis=0)
    upper_bounds = X.max(axis=0)

    # Generate random candidate points within observed bounds
    C = rng.uniform(lower_bounds, upper_bounds, size=(n_candidates, d))

    # Exploitation term (closer to best is better)
    dist_to_best = np.linalg.norm(C - best_x, axis=1)
    exploit = 1 - (dist_to_best / (dist_to_best.max() + 1e-12))

    # Exploration term (farther from existing points is better)
    dists = np.sqrt(((C[:, None, :] - X[None, :, :]) ** 2).sum(axis=2))
    min_dist = dists.min(axis=1)
    explore = min_dist / (min_dist.max() + 1e-12)

    # Combined score
    score = w_exploit * exploit + w_explore * explore

    return C[np.argmax(score)]

def format_query(x):
    return "-".join([f"{v:0.6f}" for v in x])

# Generate next query
next_x = propose_next_point(X, y)

print("Submit this to the portal:")
print(format_query(next_x))

Submit this to the portal:
0.145970-0.921486


In [2]:
###WEEK 2
#I want to see the data in /Users/mayukotakamiya/MachineLearning/initial_data/function_1/initial_inputs.npy
print(Initial_input_data)
#I WANT TO create a new npy file by adding a new data point which is [0.433534 0.458467]
new_data_point = np.array([[0.134590, 0.748865, 0.886892, 0.157267, 0.734626, 0.825781]])
Combined_input_data = np.concatenate((Initial_input_data, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_7/W2_inputs.npy", Combined_input_data)
print(Combined_input_data)

[[0.27262382 0.32449536 0.89710881 0.83295115 0.15406269 0.79586362]
 [0.54300258 0.9246939  0.34156746 0.64648585 0.71844033 0.34313266]
 [0.09083225 0.66152938 0.06593091 0.25857701 0.96345285 0.6402654 ]
 [0.11886697 0.61505494 0.90581639 0.8553003  0.41363143 0.58523563]
 [0.63021764 0.8380969  0.68001305 0.73189509 0.52673671 0.34842921]
 [0.76491917 0.25588292 0.60908422 0.21807904 0.32294277 0.09579366]
 [0.05789554 0.49167222 0.24742222 0.21811844 0.42042833 0.73096984]
 [0.19525188 0.07922665 0.55458046 0.17056682 0.01494418 0.10703171]
 [0.64230298 0.83687455 0.02179269 0.10148801 0.68307083 0.6924164 ]
 [0.78994255 0.19554501 0.57562333 0.07365919 0.25904917 0.05109986]
 [0.52849733 0.45742436 0.36009569 0.36204551 0.81689098 0.63747637]
 [0.72261522 0.01181284 0.06364591 0.16517311 0.07924415 0.35995166]
 [0.07566492 0.33450212 0.13273274 0.60831236 0.91838592 0.82233079]
 [0.94245084 0.37743962 0.48612233 0.22879108 0.08263175 0.71195755]
 [0.14864702 0.03394336 0.72880565

In [3]:
print(Initial_output_data)

#I want to create a new npy file bt adding a new data point to the Initial_output_data
new_output_data_point = np.array([0.057963126418195905])
Combined_output_data = np.concatenate((Initial_output_data, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_7/W2_outputs.npy", Combined_output_data)

print(Combined_output_data)

[0.6044327  0.56275307 0.00750324 0.0614243  0.2730468  0.08374657
 1.3649683  0.09264495 0.0178696  0.03356494 0.0735163  0.2063097
 0.00882563 0.26840032 0.61152553 0.01479818 0.27489251 0.06676325
 0.04211835 0.00270147 0.01820907 0.00701603 0.10050661 0.47539552
 0.67514163 0.51645722 0.00377748 0.00313433 0.02134252 0.09541116]
[0.6044327  0.56275307 0.00750324 0.0614243  0.2730468  0.08374657
 1.3649683  0.09264495 0.0178696  0.03356494 0.0735163  0.2063097
 0.00882563 0.26840032 0.61152553 0.01479818 0.27489251 0.06676325
 0.04211835 0.00270147 0.01820907 0.00701603 0.10050661 0.47539552
 0.67514163 0.51645722 0.00377748 0.00313433 0.02134252 0.09541116
 0.05796313]


In [87]:
#Assess the exploitation vs exploration strategy
x=Combined_input_data
y=Combined_output_data

best_score_w2= np.max(y)
improvement= best_score_w2 - np.max(Initial_output_data)

print("Improvement:", improvement)
print("Output range:", y.min(), "to", y.max())
print("Std deviation:", np.std(y))


Improvement: 0.007087524491951498
Output range: -0.0036060626443634764 to 0.007087524491952269
Std deviation: 0.002376682573738607


In [ ]:
##Function1- For week2, it seems there is a big improvement by having the improvement more than 10% of the output range. Therefore, more exploitation than exploration.
##Function2- For week2, no improvement at all. Therefore use more exploration than exploitation
##Function3- for week2, no improvement at all.Therefore use more exploration than exploitation. 
##Function4- for week2, no improvement at all.Therefore use more exploration than exploitation. 
##Function5- for week2, no improvement at all.Therefore use more exploration than exploitation. 
##Function6- for week2, no improvement at all.Therefore use more exploration than exploitation. 
##Function7- for week2, no improvement at all.Therefore use more exploration than exploitation. 
#Function8- for week2, there is small-moderate improvement. Take a balanced approach (6:4)

In [88]:
#Re-run the loop
X=Combined_input_data
y=Combined_output_data

def propose_next_point(X, y, n_candidates=8000, w_exploit=0.75, w_explore=0.25, seed=234):
    """
    Simple explore/exploit heuristic:
    - exploit: sample near best observed point
    - explore: sample far from existing samples
    """

    rng = np.random.default_rng(seed)
    n, d = X.shape

    # Best observed point so far
    best_x = X[np.argmax(y)]
    
    radius = 0.05  # small local refinement

    # Determine sampling bounds from existing data
    lower = np.maximum(best_x - radius, X.min(axis=0))
    upper = np.minimum(best_x + radius, X.max(axis=0))


    # Generate random candidate points within observed bounds
    C = rng.uniform(lower, upper, size=(n_candidates, d))

    # Exploitation term (closer to best is better)
    dist_to_best = np.linalg.norm(C - best_x, axis=1)
    exploit = 1 - (dist_to_best / (dist_to_best.max() + 1e-12))

    # Exploration term (farther from existing points is better)
    dists = np.sqrt(((C[:, None, :] - X[None, :, :]) ** 2).sum(axis=2))
    min_dist = dists.min(axis=1)
    explore = min_dist / (min_dist.max() + 1e-12)

    # Combined score
    score = w_exploit * exploit + w_explore * explore

    return C[np.argmax(score)]

def format_query(x):
    return "-".join([f"{v:0.6f}" for v in x])

# Generate next query
next_x = propose_next_point(X, y)

print("Submit this to the portal:")
print(format_query(next_x))

Submit this to the portal:
0.433582-0.457940


In [4]:
####WEEK 3
new_data_point = np.array([[0.105722, 0.539255, 0.206091, 0.171339, 0.375713, 0.779977]])
Combined_input_data3 = np.concatenate((Combined_input_data, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_7/W3_inputs.npy", Combined_input_data3)
print(Combined_input_data3)

new_output_data_point = np.array([1.1902497681664506])
Combined_output_data3 = np.concatenate((Combined_output_data, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_7/W3_outputs.npy", Combined_output_data3)

print(Combined_output_data3)


[[0.27262382 0.32449536 0.89710881 0.83295115 0.15406269 0.79586362]
 [0.54300258 0.9246939  0.34156746 0.64648585 0.71844033 0.34313266]
 [0.09083225 0.66152938 0.06593091 0.25857701 0.96345285 0.6402654 ]
 [0.11886697 0.61505494 0.90581639 0.8553003  0.41363143 0.58523563]
 [0.63021764 0.8380969  0.68001305 0.73189509 0.52673671 0.34842921]
 [0.76491917 0.25588292 0.60908422 0.21807904 0.32294277 0.09579366]
 [0.05789554 0.49167222 0.24742222 0.21811844 0.42042833 0.73096984]
 [0.19525188 0.07922665 0.55458046 0.17056682 0.01494418 0.10703171]
 [0.64230298 0.83687455 0.02179269 0.10148801 0.68307083 0.6924164 ]
 [0.78994255 0.19554501 0.57562333 0.07365919 0.25904917 0.05109986]
 [0.52849733 0.45742436 0.36009569 0.36204551 0.81689098 0.63747637]
 [0.72261522 0.01181284 0.06364591 0.16517311 0.07924415 0.35995166]
 [0.07566492 0.33450212 0.13273274 0.60831236 0.91838592 0.82233079]
 [0.94245084 0.37743962 0.48612233 0.22879108 0.08263175 0.71195755]
 [0.14864702 0.03394336 0.72880565

In [5]:
#WEEK 3 Assess the exploitation vs exploration strategy
x=Combined_input_data3
y=Combined_output_data3

best_score_w2= np.max(y)
improvement= best_score_w2 - np.max(Combined_output_data)

print("Improvement:", improvement)
print("Output range:", y.min(), "to", y.max())
print("Std deviation:", np.std(y))

Improvement: 0.0
Output range: 0.0027014650245082332 to 1.3649683044991994
Std deviation: 0.33940618415406537


In [6]:
###WEEK 3 - apply SVM 
X=Combined_input_data3
y=Combined_output_data3


threshold = np.quantile(y, 0.7)
labels = (y >= threshold).astype(int)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

from sklearn.svm import SVC

model = SVC(kernel='rbf', C=1.0, gamma='scale')
model.fit(X_scaled, labels)

rng = np.random.default_rng(42)

lower = X.min(axis=0)
upper = X.max(axis=0)

candidates = rng.uniform(lower, upper, size=(5000, X.shape[1]))

candidates_scaled = scaler.transform(candidates)

scores = model.decision_function(candidates_scaled)

next_point = candidates[np.argmin(np.abs(scores))]

query = "-".join([f"{v:0.6f}" for v in next_point])
print(query)

0.431487-0.905820-0.260199-0.489773-0.172207-0.211774


In [7]:
####WEEK 4
new_data_point = np.array([[0.431487, 0.905820, 0.260199, 0.489773, 0.172207, 0.211774]])
Combined_input_data4 = np.concatenate((Combined_input_data3, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_7/W4_inputs.npy", Combined_input_data4)
print(Combined_input_data4)

new_output_data_point = np.array([1.9192145262855722])
Combined_output_data4 = np.concatenate((Combined_output_data3, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_7/W4_outputs.npy", Combined_output_data4)

print(Combined_output_data4)

[[0.27262382 0.32449536 0.89710881 0.83295115 0.15406269 0.79586362]
 [0.54300258 0.9246939  0.34156746 0.64648585 0.71844033 0.34313266]
 [0.09083225 0.66152938 0.06593091 0.25857701 0.96345285 0.6402654 ]
 [0.11886697 0.61505494 0.90581639 0.8553003  0.41363143 0.58523563]
 [0.63021764 0.8380969  0.68001305 0.73189509 0.52673671 0.34842921]
 [0.76491917 0.25588292 0.60908422 0.21807904 0.32294277 0.09579366]
 [0.05789554 0.49167222 0.24742222 0.21811844 0.42042833 0.73096984]
 [0.19525188 0.07922665 0.55458046 0.17056682 0.01494418 0.10703171]
 [0.64230298 0.83687455 0.02179269 0.10148801 0.68307083 0.6924164 ]
 [0.78994255 0.19554501 0.57562333 0.07365919 0.25904917 0.05109986]
 [0.52849733 0.45742436 0.36009569 0.36204551 0.81689098 0.63747637]
 [0.72261522 0.01181284 0.06364591 0.16517311 0.07924415 0.35995166]
 [0.07566492 0.33450212 0.13273274 0.60831236 0.91838592 0.82233079]
 [0.94245084 0.37743962 0.48612233 0.22879108 0.08263175 0.71195755]
 [0.14864702 0.03394336 0.72880565

In [ ]:
##WEEK 4- SVM and NN hybrid

from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.neural_network import MLPRegressor

X = Combined_input_data4
y = Combined_output_data4

print("Dataset shape:", X.shape)

threshold = np.quantile(y, 0.7)   # top 30% = good
labels = (y >= threshold).astype(int)

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

svm = SVC(kernel="rbf", C=1.0, gamma="scale")
svm.fit(X_scaled, labels)

nn = MLPRegressor(
    hidden_layer_sizes=(24,12),
    activation="relu",
    solver="adam",
    max_iter=2000,
    random_state=42
)

nn.fit(X_scaled, y)

rng = np.random.default_rng(42)

lower = X.min(axis=0)
upper = X.max(axis=0)

candidates = rng.uniform(lower, upper, size=(10000, X.shape[1]))

dist = np.sqrt(((candidates[:,None,:] - X[None,:,:])**2).sum(axis=2))
min_dist = dist.min(axis=1)

mask = min_dist > 0.01
candidates = candidates[mask]

candidates_scaled = scaler.transform(candidates)

# SVM decision score (region quality)
svm_scores = svm.decision_function(candidates_scaled)

# NN predicted output
nn_predictions = nn.predict(candidates_scaled)

# Combine both scores
combined_score = nn_predictions + 0.1 * svm_scores

best_candidate = candidates[np.argmax(combined_score)]

query_string = "-".join([f"{v:0.6f}" for v in best_candidate])

print("Next query:")
print(query_string)

Dataset shape: (33, 6)
Next query:
0.141474-0.918354-0.077736-0.858246-0.205707-0.070882


In [9]:
#WEEK 5 
new_data_point = np.array([[0.141474, 0.918354, 0.077736, 0.858246, 0.205707, 0.070882]])
Combined_input_data5 = np.concatenate((Combined_input_data4, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_7/W5_inputs.npy", Combined_input_data5)
print(Combined_input_data5)

new_output_data_point = np.array([0.41594919462458524])
Combined_output_data5 = np.concatenate((Combined_output_data4, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_7/W5_outputs.npy", Combined_output_data5)

print(Combined_output_data5)

[[0.27262382 0.32449536 0.89710881 0.83295115 0.15406269 0.79586362]
 [0.54300258 0.9246939  0.34156746 0.64648585 0.71844033 0.34313266]
 [0.09083225 0.66152938 0.06593091 0.25857701 0.96345285 0.6402654 ]
 [0.11886697 0.61505494 0.90581639 0.8553003  0.41363143 0.58523563]
 [0.63021764 0.8380969  0.68001305 0.73189509 0.52673671 0.34842921]
 [0.76491917 0.25588292 0.60908422 0.21807904 0.32294277 0.09579366]
 [0.05789554 0.49167222 0.24742222 0.21811844 0.42042833 0.73096984]
 [0.19525188 0.07922665 0.55458046 0.17056682 0.01494418 0.10703171]
 [0.64230298 0.83687455 0.02179269 0.10148801 0.68307083 0.6924164 ]
 [0.78994255 0.19554501 0.57562333 0.07365919 0.25904917 0.05109986]
 [0.52849733 0.45742436 0.36009569 0.36204551 0.81689098 0.63747637]
 [0.72261522 0.01181284 0.06364591 0.16517311 0.07924415 0.35995166]
 [0.07566492 0.33450212 0.13273274 0.60831236 0.91838592 0.82233079]
 [0.94245084 0.37743962 0.48612233 0.22879108 0.08263175 0.71195755]
 [0.14864702 0.03394336 0.72880565

In [ ]:
##WEEK 5 - train a small neural network surrogate
#$generate both global and local candidates
#use the NN’s predicted output to rank them
#add a small exploration bonus
#avoid querying points too close to existing samples


X = Combined_input_data5
y = Combined_output_data5

print("Dataset shape:", X.shape)


scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

model = MLPRegressor(
    hidden_layer_sizes=(40, 20),   # a bit larger for 6D
    activation="relu",
    solver="adam",
    alpha=1e-3,                    # light regularisation
    max_iter=4000,
    random_state=42
)

model.fit(X_scaled, y)

best_idx = np.argmax(y)
best_x = X[best_idx]

print("Best value so far:", y[best_idx])
print("Best point so far:", best_x)

rng = np.random.default_rng(42)

lower = X.min(axis=0)
upper = X.max(axis=0)

# Global exploration candidates
global_candidates = rng.uniform(lower, upper, size=(8000, 6))

# Local refinement candidates around current best
local_candidates = rng.normal(loc=best_x, scale=0.04, size=(8000, 6))
local_candidates = np.clip(local_candidates, lower, upper)

# Combine candidates
candidates = np.vstack([global_candidates, local_candidates])

dist = np.sqrt(((candidates[:, None, :] - X[None, :, :]) ** 2).sum(axis=2))
min_dist = dist.min(axis=1)

mask = min_dist > 0.01
candidates = candidates[mask]
min_dist = min_dist[mask]

print("Candidates after filtering:", candidates.shape[0])

candidates_scaled = scaler.transform(candidates)
predictions = model.predict(candidates_scaled)

explore_score = min_dist / (min_dist.max() + 1e-12)

# Balanced score: prediction + exploration bonus
score = predictions + 0.10 * explore_score

best_candidate_idx = np.argmax(score)
next_query = candidates[best_candidate_idx]

print("Predicted score of next query:", predictions[best_candidate_idx])

query_string = "-".join([f"{v:0.6f}" for v in next_query])

print("Next query:")
print(query_string)

Dataset shape: (34, 6)
Best value so far: 1.9192145262855722
Best point so far: [0.431487 0.90582  0.260199 0.489773 0.172207 0.211774]
Candidates after filtering: 15998
Predicted score of next query: 2.003650249859447
Next query:
0.357308-0.924694-0.189948-0.426890-0.106825-0.131658


In [11]:
#WEEK 6
new_data_point = np.array([[0.141474, 0.918354, 0.077736, 0.858246, 0.205707, 0.070882]])
Combined_input_data6 = np.concatenate((Combined_input_data5, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_7/W6_inputs.npy", Combined_input_data6)
print(Combined_input_data6)

new_output_data_point = np.array([0.41594919462458524])
Combined_output_data6 = np.concatenate((Combined_output_data5, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_7/W6_outputs.npy", Combined_output_data6)

print(Combined_output_data6)

[[0.27262382 0.32449536 0.89710881 0.83295115 0.15406269 0.79586362]
 [0.54300258 0.9246939  0.34156746 0.64648585 0.71844033 0.34313266]
 [0.09083225 0.66152938 0.06593091 0.25857701 0.96345285 0.6402654 ]
 [0.11886697 0.61505494 0.90581639 0.8553003  0.41363143 0.58523563]
 [0.63021764 0.8380969  0.68001305 0.73189509 0.52673671 0.34842921]
 [0.76491917 0.25588292 0.60908422 0.21807904 0.32294277 0.09579366]
 [0.05789554 0.49167222 0.24742222 0.21811844 0.42042833 0.73096984]
 [0.19525188 0.07922665 0.55458046 0.17056682 0.01494418 0.10703171]
 [0.64230298 0.83687455 0.02179269 0.10148801 0.68307083 0.6924164 ]
 [0.78994255 0.19554501 0.57562333 0.07365919 0.25904917 0.05109986]
 [0.52849733 0.45742436 0.36009569 0.36204551 0.81689098 0.63747637]
 [0.72261522 0.01181284 0.06364591 0.16517311 0.07924415 0.35995166]
 [0.07566492 0.33450212 0.13273274 0.60831236 0.91838592 0.82233079]
 [0.94245084 0.37743962 0.48612233 0.22879108 0.08263175 0.71195755]
 [0.14864702 0.03394336 0.72880565

In [ ]:
##WEEK 6 
#Use a slightly larger neural network surrogate
#Combine:
#global exploration (important in 6D)
#local refinement
#Add exploration bonus
#Avoid over-exploitation (previous stagnation risk)

X = Combined_input_data6
y = Combined_output_data6

print("Dataset shape:", X.shape)

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

model = MLPRegressor(
    hidden_layer_sizes=(40, 20),   # slightly larger for 6D
    activation="relu",
    solver="adam",
    alpha=1e-3,                    # regularisation
    max_iter=4000,
    random_state=42
)

model.fit(X_scaled, y)

best_idx = np.argmax(y)
best_x = X[best_idx]

print("Best value:", y[best_idx])

rng = np.random.default_rng(123)

lower = X.min(axis=0)
upper = X.max(axis=0)

# Global exploration (important in 6D)
global_candidates = rng.uniform(lower, upper, size=(8000, 6))

# Local refinement around best point
local_candidates = rng.normal(loc=best_x, scale=0.04, size=(8000, 6))
local_candidates = np.clip(local_candidates, lower, upper)

# Combine candidates
candidates = np.vstack([global_candidates, local_candidates])


dist = np.sqrt(((candidates[:, None, :] - X[None, :, :])**2).sum(axis=2))
min_dist = dist.min(axis=1)

mask = min_dist > 0.01
candidates = candidates[mask]
min_dist = min_dist[mask]

print("Candidates after filtering:", candidates.shape[0])


candidates_scaled = scaler.transform(candidates)
predictions = model.predict(candidates_scaled)

explore_score = min_dist / (min_dist.max() + 1e-12)

# Balanced approach (slightly exploration-aware)
score = predictions + 0.12 * explore_score


best_candidate_idx = np.argmax(score)
next_query = candidates[best_candidate_idx]

print("Predicted best value:", predictions[best_candidate_idx])

query_string = "-".join([f"{v:0.6f}" for v in next_query])

print("Next query:")
print(query_string)


Dataset shape: (35, 6)
Best value: 1.9192145262855722
Candidates after filtering: 16000
Predicted best value: 2.030651984066154
Next query:
0.404479-0.923183-0.215051-0.432142-0.058745-0.143931


In [ ]:
#WEEK 7

Combined_input_data6 = np.load("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_7/W6_inputs.npy")
Combined_output_data6 = np.load("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_7/W6_outputs.npy")

new_data_point = np.array([[0.404479, 0.923183, 0.215051, 0.432142, 0.058745, 0.143931]])
Combined_input_data7 = np.concatenate((Combined_input_data6, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_7/W7_inputs.npy", Combined_input_data7)
print(Combined_input_data7)

new_output_data_point = np.array([2.169344011467542])
Combined_output_data7 = np.concatenate((Combined_output_data6, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_7/W7_outputs.npy", Combined_output_data7)

print(Combined_output_data7)

[[0.27262382 0.32449536 0.89710881 0.83295115 0.15406269 0.79586362]
 [0.54300258 0.9246939  0.34156746 0.64648585 0.71844033 0.34313266]
 [0.09083225 0.66152938 0.06593091 0.25857701 0.96345285 0.6402654 ]
 [0.11886697 0.61505494 0.90581639 0.8553003  0.41363143 0.58523563]
 [0.63021764 0.8380969  0.68001305 0.73189509 0.52673671 0.34842921]
 [0.76491917 0.25588292 0.60908422 0.21807904 0.32294277 0.09579366]
 [0.05789554 0.49167222 0.24742222 0.21811844 0.42042833 0.73096984]
 [0.19525188 0.07922665 0.55458046 0.17056682 0.01494418 0.10703171]
 [0.64230298 0.83687455 0.02179269 0.10148801 0.68307083 0.6924164 ]
 [0.78994255 0.19554501 0.57562333 0.07365919 0.25904917 0.05109986]
 [0.52849733 0.45742436 0.36009569 0.36204551 0.81689098 0.63747637]
 [0.72261522 0.01181284 0.06364591 0.16517311 0.07924415 0.35995166]
 [0.07566492 0.33450212 0.13273274 0.60831236 0.91838592 0.82233079]
 [0.94245084 0.37743962 0.48612233 0.22879108 0.08263175 0.71195755]
 [0.14864702 0.03394336 0.72880565

In [ ]:
#WEEK 7 

X = Combined_input_data7
y = Combined_output_data7

print("Dataset shape:", X.shape)


HIDDEN_LAYERS = (40, 20)   # expressive but controlled NN
ALPHA = 1e-3               # regularisation
LOCAL_RADIUS = 0.04
N_LOCAL = 6000
N_GLOBAL = 7000
MIN_SEP = 0.01
EXPLORE_BONUS = 0.12
SEED = 321
MAX_ITER = 4500


scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)


model = MLPRegressor(
    hidden_layer_sizes=HIDDEN_LAYERS,
    activation="relu",
    solver="adam",
    alpha=ALPHA,
    max_iter=MAX_ITER,
    random_state=SEED
)

model.fit(X_scaled, y)

best_idx = np.argmax(y)
best_x = X[best_idx]
best_y = y[best_idx]

print("Best value so far:", best_y)
print("Best point so far:", best_x)

rng = np.random.default_rng(SEED)

lower = X.min(axis=0)
upper = X.max(axis=0)

# Local refinement around best point
local_candidates = rng.normal(loc=best_x, scale=LOCAL_RADIUS, size=(N_LOCAL, 6))
local_candidates = np.clip(local_candidates, lower, upper)

# Global exploration
global_candidates = rng.uniform(lower, upper, size=(N_GLOBAL, 6))

# Combine candidates
candidates = np.vstack([local_candidates, global_candidates])


dist_to_existing = np.sqrt(((candidates[:, None, :] - X[None, :, :]) ** 2).sum(axis=2))
min_dist_existing = dist_to_existing.min(axis=1)

mask = min_dist_existing > MIN_SEP
candidates = candidates[mask]
min_dist_existing = min_dist_existing[mask]

print("Candidates after filtering:", candidates.shape[0])


candidates_scaled = scaler.transform(candidates)
predictions = model.predict(candidates_scaled)


explore_score = min_dist_existing / (min_dist_existing.max() + 1e-12)
score = predictions + EXPLORE_BONUS * explore_score


next_query = candidates[np.argmax(score)]

query_string = "-".join([f"{v:0.6f}" for v in next_query])

print("Next query:")
print(query_string)

Dataset shape: (36, 6)
Best value so far: 2.169344011467542
Best point so far: [0.404479 0.923183 0.215051 0.432142 0.058745 0.143931]
Candidates after filtering: 13000
Next query:
0.081256-0.858766-0.039664-0.165324-0.032659-0.153156


In [4]:
#WEEK 8

new_data_point = np.array([[0.081256, 0.858766, 0.039664, 0.165324, 0.032659, 0.153156]])
Combined_input_data8 = np.concatenate((Combined_input_data7, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_7/W8_inputs.npy", Combined_input_data8)
print(Combined_input_data8)

new_output_data_point = np.array([0.09314122519456491])
Combined_output_data8 = np.concatenate((Combined_output_data7, new_output_data_point), axis=0)
Combined_output_data8 = np.concatenate((Combined_output_data7, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_7/W8_outputs.npy", Combined_output_data8)

print(Combined_output_data8)

[[0.27262382 0.32449536 0.89710881 0.83295115 0.15406269 0.79586362]
 [0.54300258 0.9246939  0.34156746 0.64648585 0.71844033 0.34313266]
 [0.09083225 0.66152938 0.06593091 0.25857701 0.96345285 0.6402654 ]
 [0.11886697 0.61505494 0.90581639 0.8553003  0.41363143 0.58523563]
 [0.63021764 0.8380969  0.68001305 0.73189509 0.52673671 0.34842921]
 [0.76491917 0.25588292 0.60908422 0.21807904 0.32294277 0.09579366]
 [0.05789554 0.49167222 0.24742222 0.21811844 0.42042833 0.73096984]
 [0.19525188 0.07922665 0.55458046 0.17056682 0.01494418 0.10703171]
 [0.64230298 0.83687455 0.02179269 0.10148801 0.68307083 0.6924164 ]
 [0.78994255 0.19554501 0.57562333 0.07365919 0.25904917 0.05109986]
 [0.52849733 0.45742436 0.36009569 0.36204551 0.81689098 0.63747637]
 [0.72261522 0.01181284 0.06364591 0.16517311 0.07924415 0.35995166]
 [0.07566492 0.33450212 0.13273274 0.60831236 0.91838592 0.82233079]
 [0.94245084 0.37743962 0.48612233 0.22879108 0.08263175 0.71195755]
 [0.14864702 0.03394336 0.72880565

In [ ]:
#WEEK 8

X = Combined_input_data8
y = Combined_output_data8

print("Dataset shape:", X.shape)


# diversity-aware / slightly higher-temperature search
HIDDEN_LAYERS = (40, 20)
ALPHA = 1e-3
LOCAL_RADIUS = 0.040

# candidate budget
N_LOCAL_BEST = 3500
N_LOCAL_TOP = 4000
N_GLOBAL = 6500

# attention + shortlist settings
TOP_QUANTILE = 0.80   # top 20% attention set
TOP_K = 40
EXPLORE_BONUS = 0.12

# near-duplicate protection
MIN_SEP = 0.01

SEED = 456
MAX_ITER = 4500


scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

model = MLPRegressor(
    hidden_layer_sizes=HIDDEN_LAYERS,
    activation="relu",
    solver="adam",
    alpha=ALPHA,
    max_iter=MAX_ITER,
    random_state=SEED
)

model.fit(X_scaled, y)

best_idx = np.argmax(y)
best_x = X[best_idx]
best_y = y[best_idx]

threshold = np.quantile(y, TOP_QUANTILE)
top_points = X[y >= threshold]

print("Best value so far:", best_y)
print("Best point so far:", best_x)
print("Top attention points:", len(top_points))

if len(top_points) == 0:
    top_points = X[best_idx:best_idx + 1]


rng = np.random.default_rng(SEED)

lower = X.min(axis=0)
upper = X.max(axis=0)

# local candidates around current best
local_best = rng.normal(loc=best_x, scale=LOCAL_RADIUS, size=(N_LOCAL_BEST, 6))

# local candidates around top-performing region
local_top = []
n_per_top = max(100, N_LOCAL_TOP // len(top_points))
for pt in top_points:
    local = rng.normal(loc=pt, scale=LOCAL_RADIUS * 1.1, size=(n_per_top, 6))
    local_top.append(local)
local_top = np.vstack(local_top)

# global exploration candidates
global_candidates = rng.uniform(lower, upper, size=(N_GLOBAL, 6))

# combine and clip
candidates = np.vstack([local_best, local_top, global_candidates])
candidates = np.clip(candidates, lower, upper)


dist_to_existing = np.sqrt(((candidates[:, None, :] - X[None, :, :]) ** 2).sum(axis=2))
min_dist_existing = dist_to_existing.min(axis=1)

mask = min_dist_existing > MIN_SEP
candidates = candidates[mask]
min_dist_existing = min_dist_existing[mask]

print("Candidates after filtering:", candidates.shape[0])


candidates_scaled = scaler.transform(candidates)
predictions = model.predict(candidates_scaled)


explore_score = min_dist_existing / (min_dist_existing.max() + 1e-12)

# score = model prediction + novelty bonus
score = predictions + EXPLORE_BONUS * explore_score


top_k_idx = np.argsort(score)[-TOP_K:]
shortlist = candidates[top_k_idx]
shortlist_score = score[top_k_idx]
shortlist_explore = explore_score[top_k_idx]

# slightly favour novelty inside the shortlist
final_score = shortlist_score + 0.06 * shortlist_explore
next_query = shortlist[np.argmax(final_score)]


query_string = "-".join([f"{v:0.6f}" for v in next_query])

print("Next query:")
print(query_string)

Dataset shape: (37, 6)
Best value so far: 2.169344011467542
Best point so far: [0.404479 0.923183 0.215051 0.432142 0.058745 0.143931]
Top attention points: 8
Candidates after filtering: 14000
Next query:
0.450446-0.924694-0.270156-0.454057-0.014944-0.106737


In [6]:
#WEEK 9

new_data_point = np.array([[00.450446, 0.924694, 0.270156, 0.454057, 0.014944, 0.106737]])
Combined_input_data9 = np.concatenate((Combined_input_data8, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_7/W9_inputs.npy", Combined_input_data9)
print(Combined_input_data9)

new_output_data_point = np.array([2.4254284551713785])
Combined_output_data9 = np.concatenate((Combined_output_data8, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_7/W9_outputs.npy", Combined_output_data9)

print(Combined_output_data9)

[[0.27262382 0.32449536 0.89710881 0.83295115 0.15406269 0.79586362]
 [0.54300258 0.9246939  0.34156746 0.64648585 0.71844033 0.34313266]
 [0.09083225 0.66152938 0.06593091 0.25857701 0.96345285 0.6402654 ]
 [0.11886697 0.61505494 0.90581639 0.8553003  0.41363143 0.58523563]
 [0.63021764 0.8380969  0.68001305 0.73189509 0.52673671 0.34842921]
 [0.76491917 0.25588292 0.60908422 0.21807904 0.32294277 0.09579366]
 [0.05789554 0.49167222 0.24742222 0.21811844 0.42042833 0.73096984]
 [0.19525188 0.07922665 0.55458046 0.17056682 0.01494418 0.10703171]
 [0.64230298 0.83687455 0.02179269 0.10148801 0.68307083 0.6924164 ]
 [0.78994255 0.19554501 0.57562333 0.07365919 0.25904917 0.05109986]
 [0.52849733 0.45742436 0.36009569 0.36204551 0.81689098 0.63747637]
 [0.72261522 0.01181284 0.06364591 0.16517311 0.07924415 0.35995166]
 [0.07566492 0.33450212 0.13273274 0.60831236 0.91838592 0.82233079]
 [0.94245084 0.37743962 0.48612233 0.22879108 0.08263175 0.71195755]
 [0.14864702 0.03394336 0.72880565

In [ ]:
#WEEK 9 

X = Combined_input_data9
y = Combined_output_data9

print("Dataset shape:", X.shape)

# More trust in the surrogate than earlier rounds,
# but still regularised because 6D remains sparse
HIDDEN_LAYERS = (40, 20)
ALPHA = 1e-3
LOCAL_RADIUS = 0.035

# Candidate budget
N_LOCAL_BEST = 4200
N_LOCAL_TOP = 3200
N_GLOBAL = 3800

# Attention to strongest region, but not too narrow
TOP_QUANTILE = 0.82   # top 18%
TOP_K = 30
EXPLORE_BONUS = 0.10

# Duplicate protection
MIN_SEP = 0.01

SEED = 789
MAX_ITER = 5000


scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

model = MLPRegressor(
    hidden_layer_sizes=HIDDEN_LAYERS,
    activation="relu",
    solver="adam",
    alpha=ALPHA,
    max_iter=MAX_ITER,
    random_state=SEED
)

model.fit(X_scaled, y)

best_idx = np.argmax(y)
best_x = X[best_idx]
best_y = y[best_idx]

threshold = np.quantile(y, TOP_QUANTILE)
top_points = X[y >= threshold]

print("Best value so far:", best_y)
print("Best point so far:", best_x)
print("Top attention points:", len(top_points))

if len(top_points) == 0:
    top_points = X[best_idx:best_idx + 1]

rng = np.random.default_rng(SEED)

lower = X.min(axis=0)
upper = X.max(axis=0)

# Local refinement around current best
local_best = rng.normal(loc=best_x, scale=LOCAL_RADIUS, size=(N_LOCAL_BEST, 6))

# Local refinement around other strong points
local_top = []
n_per_top = max(90, N_LOCAL_TOP // len(top_points))
for pt in top_points:
    local = rng.normal(loc=pt, scale=LOCAL_RADIUS * 1.08, size=(n_per_top, 6))
    local_top.append(local)
local_top = np.vstack(local_top)

# Global exploration
global_candidates = rng.uniform(lower, upper, size=(N_GLOBAL, 6))

# Combine and clip
candidates = np.vstack([local_best, local_top, global_candidates])
candidates = np.clip(candidates, lower, upper)

dist_to_existing = np.sqrt(((candidates[:, None, :] - X[None, :, :]) ** 2).sum(axis=2))
min_dist_existing = dist_to_existing.min(axis=1)

mask = min_dist_existing > MIN_SEP
candidates = candidates[mask]
min_dist_existing = min_dist_existing[mask]

print("Candidates after filtering:", candidates.shape[0])

candidates_scaled = scaler.transform(candidates)
predictions = model.predict(candidates_scaled)

explore_score = min_dist_existing / (min_dist_existing.max() + 1e-12)

# Surrogate-led score with moderate diversity protection
score = predictions + EXPLORE_BONUS * explore_score

top_k_idx = np.argsort(score)[-TOP_K:]
shortlist = candidates[top_k_idx]
shortlist_score = score[top_k_idx]
shortlist_explore = explore_score[top_k_idx]

# Slight novelty preference inside the shortlist
final_score = shortlist_score + 0.05 * shortlist_explore
next_query = shortlist[np.argmax(final_score)]

query_string = "-".join([f"{v:0.6f}" for v in next_query])

print("Next query:")
print(query_string)


Dataset shape: (38, 6)
Best value so far: 2.4254284551713785
Best point so far: [0.450446 0.924694 0.270156 0.454057 0.014944 0.106737]
Top attention points: 7
Candidates after filtering: 11199
Next query:
0.528963-0.924694-0.332356-0.488855-0.014944-0.051100


In [8]:
#WEEK 10

new_data_point = np.array([[0.528963, 0.924694, 0.332356, 0.488855, 0.014944, 0.051100]])
Combined_input_data10 = np.concatenate((Combined_input_data9, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_7/W10_inputs.npy", Combined_input_data10)
print(Combined_input_data10)

new_output_data_point = np.array([2.2184376283085556])
Combined_output_data10 = np.concatenate((Combined_output_data9, new_output_data_point), axis=0)
Combined_output_data10 = np.concatenate((Combined_output_data9, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_7/W10_outputs.npy", Combined_output_data10)

print(Combined_output_data10)

[[0.27262382 0.32449536 0.89710881 0.83295115 0.15406269 0.79586362]
 [0.54300258 0.9246939  0.34156746 0.64648585 0.71844033 0.34313266]
 [0.09083225 0.66152938 0.06593091 0.25857701 0.96345285 0.6402654 ]
 [0.11886697 0.61505494 0.90581639 0.8553003  0.41363143 0.58523563]
 [0.63021764 0.8380969  0.68001305 0.73189509 0.52673671 0.34842921]
 [0.76491917 0.25588292 0.60908422 0.21807904 0.32294277 0.09579366]
 [0.05789554 0.49167222 0.24742222 0.21811844 0.42042833 0.73096984]
 [0.19525188 0.07922665 0.55458046 0.17056682 0.01494418 0.10703171]
 [0.64230298 0.83687455 0.02179269 0.10148801 0.68307083 0.6924164 ]
 [0.78994255 0.19554501 0.57562333 0.07365919 0.25904917 0.05109986]
 [0.52849733 0.45742436 0.36009569 0.36204551 0.81689098 0.63747637]
 [0.72261522 0.01181284 0.06364591 0.16517311 0.07924415 0.35995166]
 [0.07566492 0.33450212 0.13273274 0.60831236 0.91838592 0.82233079]
 [0.94245084 0.37743962 0.48612233 0.22879108 0.08263175 0.71195755]
 [0.14864702 0.03394336 0.72880565

In [ ]:
#WEEK 10
from sklearn.pipeline import make_pipeline
from sklearn.linear_model import Ridge

X = Combined_input_data10
y = Combined_output_data10

model = make_pipeline(StandardScaler(), Ridge(alpha=2.0))
model.fit(X, y)

best_x = X[np.argmax(y)]
lower = X.min(axis=0)
upper = X.max(axis=0)

rng = np.random.default_rng(107)

# mostly local, some global
local_candidates = rng.normal(loc=best_x, scale=0.035, size=(4000, 6))
global_candidates = rng.uniform(lower, upper, size=(3000, 6))
candidates = np.vstack([local_candidates, global_candidates])
candidates = np.clip(candidates, lower, upper)

pred = model.predict(candidates)

dist = np.sqrt(((candidates[:, None, :] - X[None, :, :]) ** 2).sum(axis=2))
min_dist = dist.min(axis=1)

score = pred + 0.10 * (min_dist / (min_dist.max() + 1e-12))
next_query = candidates[np.argmax(score)]

query_string = "-".join([f"{v:0.6f}" for v in next_query])
print(query_string)

ridge = model.named_steps["ridge"]
print("Feature coefficients:", ridge.coef_)

0.077787-0.895312-0.243664-0.090153-0.037179-0.733761
Feature coefficients: [-0.04109221  0.26356417 -0.01403025 -0.06430664 -0.28106675 -0.01003625]


In [10]:
#WEEK 11

new_data_point = np.array([[0.077787, 0.895312, 0.243664, 0.090153, 0.037179, 0.733761]])
Combined_input_data11 = np.concatenate((Combined_input_data10, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_7/W11_inputs.npy", Combined_input_data11)
print(Combined_input_data11)

new_output_data_point = np.array([0.08431804222931552])
Combined_output_data11 = np.concatenate((Combined_output_data10, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_7/W11_outputs.npy", Combined_output_data11)

print(Combined_output_data11)

[[0.27262382 0.32449536 0.89710881 0.83295115 0.15406269 0.79586362]
 [0.54300258 0.9246939  0.34156746 0.64648585 0.71844033 0.34313266]
 [0.09083225 0.66152938 0.06593091 0.25857701 0.96345285 0.6402654 ]
 [0.11886697 0.61505494 0.90581639 0.8553003  0.41363143 0.58523563]
 [0.63021764 0.8380969  0.68001305 0.73189509 0.52673671 0.34842921]
 [0.76491917 0.25588292 0.60908422 0.21807904 0.32294277 0.09579366]
 [0.05789554 0.49167222 0.24742222 0.21811844 0.42042833 0.73096984]
 [0.19525188 0.07922665 0.55458046 0.17056682 0.01494418 0.10703171]
 [0.64230298 0.83687455 0.02179269 0.10148801 0.68307083 0.6924164 ]
 [0.78994255 0.19554501 0.57562333 0.07365919 0.25904917 0.05109986]
 [0.52849733 0.45742436 0.36009569 0.36204551 0.81689098 0.63747637]
 [0.72261522 0.01181284 0.06364591 0.16517311 0.07924415 0.35995166]
 [0.07566492 0.33450212 0.13273274 0.60831236 0.91838592 0.82233079]
 [0.94245084 0.37743962 0.48612233 0.22879108 0.08263175 0.71195755]
 [0.14864702 0.03394336 0.72880565

In [ ]:
#WEEK 11
from sklearn.cluster import KMeans

X = Combined_input_data11
y = Combined_output_data11

threshold = np.quantile(y, 0.75)
top_X = X[y >= threshold]
top_y = y[y >= threshold]

k = min(4, len(top_X))
kmeans = KMeans(n_clusters=k, random_state=17, n_init=10)
labels = kmeans.fit_predict(top_X)

cluster_info = []
for c in range(k):
    cluster_points = top_X[labels == c]
    cluster_y = top_y[labels == c]
    cluster_info.append((cluster_y.mean(), cluster_points.mean(axis=0), cluster_points))

cluster_info.sort(key=lambda t: t[0], reverse=True)
best_centroid = cluster_info[0][1]

rng = np.random.default_rng(17)
local = rng.normal(loc=best_centroid, scale=0.04, size=(3000, X.shape[1]))
global_ = rng.uniform(X.min(axis=0), X.max(axis=0), size=(3000, X.shape[1]))
candidates = np.vstack([local, global_])
candidates = np.clip(candidates, X.min(axis=0), X.max(axis=0))

dist = np.sqrt(((candidates[:, None, :] - X[None, :, :]) ** 2).sum(axis=2))
min_dist = dist.min(axis=1)

# choose candidate near best cluster but not too close to old points
dist_to_centroid = np.linalg.norm(candidates - best_centroid, axis=1)
score = -dist_to_centroid + 0.2 * min_dist
next_query = candidates[np.argmax(score)]

print("-".join([f"{v:0.6f}" for v in next_query]))

0.476982-0.924694-0.278880-0.493956-0.200328-0.173190


In [12]:
#WEEK 12

new_data_point = np.array([[0.476982, 0.924694, 0.278880, 0.493956, 0.200328, 0.173190]])
Combined_input_data12 = np.concatenate((Combined_input_data11, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_7/W12_inputs.npy", Combined_input_data12)
print(Combined_input_data12)

new_output_data_point = np.array([2.082240008643757])
Combined_output_data12 = np.concatenate((Combined_output_data11, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_7/W12_outputs.npy", Combined_output_data12)

print(Combined_output_data12)

[[0.27262382 0.32449536 0.89710881 0.83295115 0.15406269 0.79586362]
 [0.54300258 0.9246939  0.34156746 0.64648585 0.71844033 0.34313266]
 [0.09083225 0.66152938 0.06593091 0.25857701 0.96345285 0.6402654 ]
 [0.11886697 0.61505494 0.90581639 0.8553003  0.41363143 0.58523563]
 [0.63021764 0.8380969  0.68001305 0.73189509 0.52673671 0.34842921]
 [0.76491917 0.25588292 0.60908422 0.21807904 0.32294277 0.09579366]
 [0.05789554 0.49167222 0.24742222 0.21811844 0.42042833 0.73096984]
 [0.19525188 0.07922665 0.55458046 0.17056682 0.01494418 0.10703171]
 [0.64230298 0.83687455 0.02179269 0.10148801 0.68307083 0.6924164 ]
 [0.78994255 0.19554501 0.57562333 0.07365919 0.25904917 0.05109986]
 [0.52849733 0.45742436 0.36009569 0.36204551 0.81689098 0.63747637]
 [0.72261522 0.01181284 0.06364591 0.16517311 0.07924415 0.35995166]
 [0.07566492 0.33450212 0.13273274 0.60831236 0.91838592 0.82233079]
 [0.94245084 0.37743962 0.48612233 0.22879108 0.08263175 0.71195755]
 [0.14864702 0.03394336 0.72880565

In [ ]:
#WEEK 12
from sklearn.decomposition import PCA
from sklearn.pipeline import make_pipeline
from sklearn.linear_model import Ridge

X = Combined_input_data12
y = Combined_output_data12

threshold = np.quantile(y, 0.80)
top_X = X[y >= threshold]

best_x = X[np.argmax(y)]
lower = X.min(axis=0)
upper = X.max(axis=0)

pca = PCA(n_components=3)
pca.fit(top_X)
pc1, pc2, pc3 = pca.components_

model = make_pipeline(StandardScaler(), Ridge(alpha=2.0))
model.fit(X, y)

rng = np.random.default_rng(127)
n_candidates = 9000

a = rng.normal(0, 0.022, size=(n_candidates, 1))
b = rng.normal(0, 0.015, size=(n_candidates, 1))
c = rng.normal(0, 0.010, size=(n_candidates, 1))
noise = rng.normal(0, 0.006, size=(n_candidates, 6))

candidates = best_x + a * pc1 + b * pc2 + c * pc3 + noise
candidates = np.clip(candidates, lower, upper)

pred = model.predict(candidates)
dist = np.sqrt(((candidates[:, None, :] - X[None, :, :])**2).sum(axis=2))
min_dist = dist.min(axis=1)

score = pred + 0.10 * (min_dist / (min_dist.max() + 1e-12))
next_query = candidates[np.argmax(score)]

print("-".join([f"{v:0.6f}" for v in next_query]))

0.499348-0.924694-0.276460-0.472547-0.014944-0.065022


In [14]:
#WEEK 13

new_data_point = np.array([[0.499348, 0.924694, 0.276460, 0.472547, 0.014944, 0.065022]])
Combined_input_data13 = np.concatenate((Combined_input_data12, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_7/W13_inputs.npy", Combined_input_data13)
print(Combined_input_data13)

new_output_data_point = np.array([2.376652185692289])
Combined_output_data13 = np.concatenate((Combined_output_data12, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_7/W13_outputs.npy", Combined_output_data13)

print(Combined_output_data13)

[[0.27262382 0.32449536 0.89710881 0.83295115 0.15406269 0.79586362]
 [0.54300258 0.9246939  0.34156746 0.64648585 0.71844033 0.34313266]
 [0.09083225 0.66152938 0.06593091 0.25857701 0.96345285 0.6402654 ]
 [0.11886697 0.61505494 0.90581639 0.8553003  0.41363143 0.58523563]
 [0.63021764 0.8380969  0.68001305 0.73189509 0.52673671 0.34842921]
 [0.76491917 0.25588292 0.60908422 0.21807904 0.32294277 0.09579366]
 [0.05789554 0.49167222 0.24742222 0.21811844 0.42042833 0.73096984]
 [0.19525188 0.07922665 0.55458046 0.17056682 0.01494418 0.10703171]
 [0.64230298 0.83687455 0.02179269 0.10148801 0.68307083 0.6924164 ]
 [0.78994255 0.19554501 0.57562333 0.07365919 0.25904917 0.05109986]
 [0.52849733 0.45742436 0.36009569 0.36204551 0.81689098 0.63747637]
 [0.72261522 0.01181284 0.06364591 0.16517311 0.07924415 0.35995166]
 [0.07566492 0.33450212 0.13273274 0.60831236 0.91838592 0.82233079]
 [0.94245084 0.37743962 0.48612233 0.22879108 0.08263175 0.71195755]
 [0.14864702 0.03394336 0.72880565

In [ ]:
#WEEK 13

X = Combined_input_data13
y = Combined_output_data13

best_x = X[np.argmax(y)]
lower = X.min(axis=0)
upper = X.max(axis=0)

model = make_pipeline(StandardScaler(), Ridge(alpha=2.0))
model.fit(X, y)

rng = np.random.default_rng(107)

# Action classes:
# 1) local refinement
# 2) regional jump
# 3) broader exploration
local_candidates = rng.normal(loc=best_x, scale=0.020, size=(3000, 6))
regional_candidates = rng.normal(loc=best_x, scale=0.040, size=(3000, 6))
global_candidates = rng.uniform(lower, upper, size=(2500, 6))

candidates = np.vstack([local_candidates, regional_candidates, global_candidates])
candidates = np.clip(candidates, lower, upper)

pred = model.predict(candidates)
dist = np.sqrt(((candidates[:, None, :] - X[None, :, :])**2).sum(axis=2))
min_dist = dist.min(axis=1)

score = pred + 0.08 * (min_dist / (min_dist.max() + 1e-12))
next_query = candidates[np.argmax(score)]

print("-".join([f"{v:0.6f}" for v in next_query]))

0.369201-0.924694-0.332180-0.387542-0.014944-0.051100
