In [9]:
#Load packages required for loading the npy files.
import numpy as np
import pandas as pd

# #Load the npy file called "data.npy"
Initial_input_data = np.load("/Users/mayukotakamiya/MachineLearning/initial_data/function_2/initial_inputs.npy")
Initial_output_data = np.load("/Users/mayukotakamiya/MachineLearning/initial_data/function_2/initial_outputs.npy")

#I want to know dimentionality of the initial_input_data  
Initial_input_data.shape




(10, 2)

In [2]:

# X and y already loaded
X = Initial_input_data
y = Initial_output_data

def propose_next_point(X, y, n_candidates=8000, w_exploit=0.6, w_explore=0.4, seed=42):
    """
    Simple explore/exploit heuristic:
    - exploit: sample near best observed point
    - explore: sample far from existing samples
    """

    rng = np.random.default_rng(seed)
    n, d = X.shape

    # Best observed point so far
    best_x = X[np.argmax(y)]

    # Determine sampling bounds from existing data
    lower_bounds = X.min(axis=0)
    upper_bounds = X.max(axis=0)

    # Generate random candidate points within observed bounds
    C = rng.uniform(lower_bounds, upper_bounds, size=(n_candidates, d))

    # Exploitation term (closer to best is better)
    dist_to_best = np.linalg.norm(C - best_x, axis=1)
    exploit = 1 - (dist_to_best / (dist_to_best.max() + 1e-12))

    # Exploration term (farther from existing points is better)
    dists = np.sqrt(((C[:, None, :] - X[None, :, :]) ** 2).sum(axis=2))
    min_dist = dists.min(axis=1)
    explore = min_dist / (min_dist.max() + 1e-12)

    # Combined score
    score = w_exploit * exploit + w_explore * explore

    return C[np.argmax(score)]

def format_query(x):
    return "-".join([f"{v:0.6f}" for v in x])

# Generate next query
next_x = propose_next_point(X, y)

print("Submit this to the portal:")
print(format_query(next_x))

Submit this to the portal:
0.145970-0.921486


In [10]:
###WEEK 2
#I want to see the data in /Users/mayukotakamiya/MachineLearning/initial_data/function_1/initial_inputs.npy
print(Initial_input_data)
#I WANT TO create a new npy file by adding a new data point which is [0.433534 0.458467]
new_data_point = np.array([[0.145970, 0.921486]])
Combined_input_data = np.concatenate((Initial_input_data, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_2/W2_inputs.npy", Combined_input_data)
print(Combined_input_data)

[[0.66579958 0.12396913]
 [0.87779099 0.7786275 ]
 [0.14269907 0.34900513]
 [0.84527543 0.71112027]
 [0.45464714 0.29045518]
 [0.57771284 0.77197318]
 [0.43816606 0.68501826]
 [0.34174959 0.02869772]
 [0.33864816 0.21386725]
 [0.70263656 0.9265642 ]]
[[0.66579958 0.12396913]
 [0.87779099 0.7786275 ]
 [0.14269907 0.34900513]
 [0.84527543 0.71112027]
 [0.45464714 0.29045518]
 [0.57771284 0.77197318]
 [0.43816606 0.68501826]
 [0.34174959 0.02869772]
 [0.33864816 0.21386725]
 [0.70263656 0.9265642 ]
 [0.14597    0.921486  ]]


In [11]:
print(Initial_output_data)

#I want to create a new npy file bt adding a new data point to the Initial_output_data
new_output_data_point = np.array([00.051283499993391726])
Combined_output_data = np.concatenate((Initial_output_data, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_2/W2_outputs.npy", Combined_output_data)

print(Combined_output_data)

[ 0.53899612  0.42058624 -0.06562362  0.29399291  0.21496451  0.02310555
  0.24461934  0.03874902 -0.01385762  0.61120522]
[ 0.53899612  0.42058624 -0.06562362  0.29399291  0.21496451  0.02310555
  0.24461934  0.03874902 -0.01385762  0.61120522  0.0512835 ]


In [87]:
#Assess the exploitation vs exploration strategy
x=Combined_input_data
y=Combined_output_data

best_score_w2= np.max(y)
improvement= best_score_w2 - np.max(Initial_output_data)

print("Improvement:", improvement)
print("Output range:", y.min(), "to", y.max())
print("Std deviation:", np.std(y))


Improvement: 0.007087524491951498
Output range: -0.0036060626443634764 to 0.007087524491952269
Std deviation: 0.002376682573738607


In [ ]:
##Function1- For week2, it seems there is a big improvement by having the improvement more than 10% of the output range. Therefore, more exploitation than exploration.
##Function2- For week2, no improvement at all. Therefore use more exploration than exploitation
##Function3- for week2, no improvement at all.Therefore use more exploration than exploitation. 
##Function4- for week2, no improvement at all.Therefore use more exploration than exploitation. 
##Function5- for week2, no improvement at all.Therefore use more exploration than exploitation. 
##Function6- for week2, no improvement at all.Therefore use more exploration than exploitation. 
##Function7- for week2, no improvement at all.Therefore use more exploration than exploitation. 
#Function8- for week2, there is small-moderate improvement. Take a balanced approach (6:4)

In [88]:
#Re-run the loop
X=Combined_input_data
y=Combined_output_data

def propose_next_point(X, y, n_candidates=8000, w_exploit=0.75, w_explore=0.25, seed=234):
    """
    Simple explore/exploit heuristic:
    - exploit: sample near best observed point
    - explore: sample far from existing samples
    """

    rng = np.random.default_rng(seed)
    n, d = X.shape

    # Best observed point so far
    best_x = X[np.argmax(y)]
    
    radius = 0.05  # small local refinement

    # Determine sampling bounds from existing data
    lower = np.maximum(best_x - radius, X.min(axis=0))
    upper = np.minimum(best_x + radius, X.max(axis=0))


    # Generate random candidate points within observed bounds
    C = rng.uniform(lower, upper, size=(n_candidates, d))

    # Exploitation term (closer to best is better)
    dist_to_best = np.linalg.norm(C - best_x, axis=1)
    exploit = 1 - (dist_to_best / (dist_to_best.max() + 1e-12))

    # Exploration term (farther from existing points is better)
    dists = np.sqrt(((C[:, None, :] - X[None, :, :]) ** 2).sum(axis=2))
    min_dist = dists.min(axis=1)
    explore = min_dist / (min_dist.max() + 1e-12)

    # Combined score
    score = w_exploit * exploit + w_explore * explore

    return C[np.argmax(score)]

def format_query(x):
    return "-".join([f"{v:0.6f}" for v in x])

# Generate next query
next_x = propose_next_point(X, y)

print("Submit this to the portal:")
print(format_query(next_x))

Submit this to the portal:
0.433582-0.457940


In [12]:
####WEEK 3
new_data_point = np.array([[0.652719, 0.877025]])
Combined_input_data3 = np.concatenate((Combined_input_data, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_2/W3_inputs.npy", Combined_input_data3)
print(Combined_input_data3)

new_output_data_point = np.array([0.43822056967450884])
Combined_output_data3 = np.concatenate((Combined_output_data, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_2/W3_outputs.npy", Combined_output_data3)

print(Combined_output_data3)


[[0.66579958 0.12396913]
 [0.87779099 0.7786275 ]
 [0.14269907 0.34900513]
 [0.84527543 0.71112027]
 [0.45464714 0.29045518]
 [0.57771284 0.77197318]
 [0.43816606 0.68501826]
 [0.34174959 0.02869772]
 [0.33864816 0.21386725]
 [0.70263656 0.9265642 ]
 [0.14597    0.921486  ]
 [0.652719   0.877025  ]]
[ 0.53899612  0.42058624 -0.06562362  0.29399291  0.21496451  0.02310555
  0.24461934  0.03874902 -0.01385762  0.61120522  0.0512835   0.43822057]


In [13]:
#WEEK 3 Assess the exploitation vs exploration strategy
x=Combined_input_data3
y=Combined_output_data3

best_score_w2= np.max(y)
improvement= best_score_w2 - np.max(Combined_output_data)

print("Improvement:", improvement)
print("Output range:", y.min(), "to", y.max())
print("Std deviation:", np.std(y))

Improvement: 0.0
Output range: -0.06562362443733738 to 0.6112052157614438
Std deviation: 0.22043178697581692


In [14]:
#WEEK 3 -re run the loop. No improvement so adjust exploit vs explore ratio to 0.45:0.55
X=Combined_input_data3
y=Combined_output_data3

def propose_next_point(X, y, n_candidates=8000, w_exploit=0.45, w_explore=0.55, seed=234):

    rng = np.random.default_rng(seed)
    n, d = X.shape

    # Best observed point so far
    best_x = X[np.argmax(y)]
    
    radius = 0.05  # small local refinement

    # Determine sampling bounds from existing data
    lower = np.maximum(best_x - radius, X.min(axis=0))
    upper = np.minimum(best_x + radius, X.max(axis=0))


    # Generate random candidate points within observed bounds
    C = rng.uniform(lower, upper, size=(n_candidates, d))

    # Exploitation term (closer to best is better)
    dist_to_best = np.linalg.norm(C - best_x, axis=1)
    exploit = 1 - (dist_to_best / (dist_to_best.max() + 1e-12))

    # Exploration term (farther from existing points is better)
    dists = np.sqrt(((C[:, None, :] - X[None, :, :]) ** 2).sum(axis=2))
    min_dist = dists.min(axis=1)
    explore = min_dist / (min_dist.max() + 1e-12)

    # Combined score
    score = w_exploit * exploit + w_explore * explore

    return C[np.argmax(score)]

def format_query(x):
    return "-".join([f"{v:0.6f}" for v in x])

# Generate next query
next_x = propose_next_point(X, y)

print("Submit this to the portal:")
print(format_query(next_x))

Submit this to the portal:
0.751452-0.876910


In [15]:
####WEEK 4
new_data_point = np.array([[0.751452, 0.876910]])
Combined_input_data4 = np.concatenate((Combined_input_data3, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_2/W4_inputs.npy", Combined_input_data4)
print(Combined_input_data4)

new_output_data_point = np.array([0.56484447865487])
Combined_output_data4 = np.concatenate((Combined_output_data3, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_2/W4_outputs.npy", Combined_output_data4)

print(Combined_output_data4)

[[0.66579958 0.12396913]
 [0.87779099 0.7786275 ]
 [0.14269907 0.34900513]
 [0.84527543 0.71112027]
 [0.45464714 0.29045518]
 [0.57771284 0.77197318]
 [0.43816606 0.68501826]
 [0.34174959 0.02869772]
 [0.33864816 0.21386725]
 [0.70263656 0.9265642 ]
 [0.14597    0.921486  ]
 [0.652719   0.877025  ]
 [0.751452   0.87691   ]]
[ 0.53899612  0.42058624 -0.06562362  0.29399291  0.21496451  0.02310555
  0.24461934  0.03874902 -0.01385762  0.61120522  0.0512835   0.43822057
  0.56484448]


In [16]:
#WEEK 4 Assess the exploitation vs exploration strategy
x=Combined_input_data4
y=Combined_output_data4

best_score_w2= np.max(y)
improvement= best_score_w2 - np.max(Combined_output_data3)

print("Improvement:", improvement)
print("Output range:", y.min(), "to", y.max())
print("Std deviation:", np.std(y))

Improvement: 0.0
Output range: -0.06562362443733738 to 0.6112052157614438
Std deviation: 0.22950107460343838


In [17]:
#WEEK 4 -re run the loop. No improvement so adjust exploit vs explore ratio to 0.45:0.55
X=Combined_input_data4
y=Combined_output_data4

def propose_next_point(X, y, n_candidates=8000, w_exploit=0.45, w_explore=0.55, seed=100):

    rng = np.random.default_rng(seed)
    n, d = X.shape

    # Best observed point so far
    best_x = X[np.argmax(y)]
    
    radius = 0.05  # small local refinement

    # Determine sampling bounds from existing data
    lower = np.maximum(best_x - radius, X.min(axis=0))
    upper = np.minimum(best_x + radius, X.max(axis=0))


    # Generate random candidate points within observed bounds
    C = rng.uniform(lower, upper, size=(n_candidates, d))

    # Exploitation term (closer to best is better)
    dist_to_best = np.linalg.norm(C - best_x, axis=1)
    exploit = 1 - (dist_to_best / (dist_to_best.max() + 1e-12))

    # Exploration term (farther from existing points is better)
    dists = np.sqrt(((C[:, None, :] - X[None, :, :]) ** 2).sum(axis=2))
    min_dist = dists.min(axis=1)
    explore = min_dist / (min_dist.max() + 1e-12)
# Combined score
    score = w_exploit * exploit + w_explore * explore

    return C[np.argmax(score)]

def format_query(x):
    return "-".join([f"{v:0.6f}" for v in x])

# Generate next query
next_x = propose_next_point(X, y)

print("Submit this to the portal:")
print(format_query(next_x))

Submit this to the portal:
0.701759-0.877518


In [18]:
#WEEK 5 
new_data_point = np.array([[0.701759, 0.877518]])
Combined_input_data5 = np.concatenate((Combined_input_data4, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_2/W5_inputs.npy", Combined_input_data5)
print(Combined_input_data5)

new_output_data_point = np.array([0.5430405844702764])
Combined_output_data5 = np.concatenate((Combined_output_data4, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_2/W5_outputs.npy", Combined_output_data5)

print(Combined_output_data5)

[[0.66579958 0.12396913]
 [0.87779099 0.7786275 ]
 [0.14269907 0.34900513]
 [0.84527543 0.71112027]
 [0.45464714 0.29045518]
 [0.57771284 0.77197318]
 [0.43816606 0.68501826]
 [0.34174959 0.02869772]
 [0.33864816 0.21386725]
 [0.70263656 0.9265642 ]
 [0.14597    0.921486  ]
 [0.652719   0.877025  ]
 [0.751452   0.87691   ]
 [0.701759   0.877518  ]]
[ 0.53899612  0.42058624 -0.06562362  0.29399291  0.21496451  0.02310555
  0.24461934  0.03874902 -0.01385762  0.61120522  0.0512835   0.43822057
  0.56484448  0.54304058]


In [ ]:
##WEEK 5 - Avoid aggressive exploitation (noise can mislead), Prefer: diverse sampling and moderate refinement near good regions

X = Combined_input_data5
y = Combined_output_data5

print("Dataset shape:", X.shape)

best_idx = np.argmax(y)
best_x = X[best_idx]

# Also consider top 30% points (robust against noise)
threshold = np.quantile(y, 0.7)
top_points = X[y >= threshold]

rng = np.random.default_rng(42)

lower = X.min(axis=0)
upper = X.max(axis=0)

# Global exploration (dominant)
global_candidates = rng.uniform(lower, upper, size=(4000, 2))

# Local candidates around multiple good points (not just best)
local_candidates = []

for pt in top_points:
    local = rng.normal(loc=pt, scale=0.05, size=(500, 2))
    local_candidates.append(local)

local_candidates = np.vstack(local_candidates)

# Combine
candidates = np.vstack([global_candidates, local_candidates])

# Clip to bounds
candidates = np.clip(candidates, lower, upper)

dist = np.sqrt(((candidates[:, None, :] - X[None, :, :])**2).sum(axis=2))
min_dist = dist.min(axis=1)

mask = min_dist > 0.01
candidates = candidates[mask]
min_dist = min_dist[mask]

# Exploitation: distance to multiple good points
dist_to_top = np.min(
    np.sqrt(((candidates[:, None, :] - top_points[None, :, :])**2).sum(axis=2)),
    axis=1
)

exploit_score = 1 - dist_to_top / (dist_to_top.max() + 1e-12)

# Exploration: distance from existing samples
explore_score = min_dist / (min_dist.max() + 1e-12)

# Slightly exploration-heavy (because noise)
score = 0.4 * exploit_score + 0.6 * explore_score

next_query = candidates[np.argmax(score)]

query_string = "-".join([f"{v:0.6f}" for v in next_query])

print("Next query:")
print(query_string)

Dataset shape: (14, 2)
Next query:
0.847723-0.389764


In [22]:
#WEEK 6
new_data_point = np.array([[0.701759, 0.877518]])
Combined_input_data6 = np.concatenate((Combined_input_data5, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_2/W6_inputs.npy", Combined_input_data6)
print(Combined_input_data6)

new_output_data_point = np.array([50.5430405844702764])
Combined_output_data6 = np.concatenate((Combined_output_data5, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_2/W6_outputs.npy", Combined_output_data6)

print(Combined_output_data6)

[[0.66579958 0.12396913]
 [0.87779099 0.7786275 ]
 [0.14269907 0.34900513]
 [0.84527543 0.71112027]
 [0.45464714 0.29045518]
 [0.57771284 0.77197318]
 [0.43816606 0.68501826]
 [0.34174959 0.02869772]
 [0.33864816 0.21386725]
 [0.70263656 0.9265642 ]
 [0.14597    0.921486  ]
 [0.652719   0.877025  ]
 [0.751452   0.87691   ]
 [0.701759   0.877518  ]
 [0.701759   0.877518  ]]
[ 5.38996119e-01  4.20586240e-01 -6.56236244e-02  2.93992912e-01
  2.14964510e-01  2.31055498e-02  2.44619344e-01  3.87490152e-02
 -1.38576181e-02  6.11205216e-01  5.12835000e-02  4.38220570e-01
  5.64844479e-01  5.43040584e-01  5.05430406e+01]


In [ ]:
##WEEK 6 
#Do not rely on a single best point
#Use top-performing region (robust to noise)
#Keep exploration slightly dominant
#Avoid neural networks (overkill + noise-sensitive)

X = Combined_input_data6
y = Combined_output_data6

print("Dataset shape:", X.shape)

# Use top 30% instead of single best (noise-robust)
threshold = np.quantile(y, 0.7)
top_points = X[y >= threshold]

print("Number of top points:", len(top_points))

rng = np.random.default_rng(123)

lower = X.min(axis=0)
upper = X.max(axis=0)

# Global exploration (important due to noise)
global_candidates = rng.uniform(lower, upper, size=(4000, 2))

# Local sampling around multiple good points
local_candidates = []

for pt in top_points:
    local = rng.normal(loc=pt, scale=0.04, size=(500, 2))
    local_candidates.append(local)

local_candidates = np.vstack(local_candidates)

# Combine candidates
candidates = np.vstack([global_candidates, local_candidates])

# Clip to bounds
candidates = np.clip(candidates, lower, upper)

dist = np.sqrt(((candidates[:, None, :] - X[None, :, :])**2).sum(axis=2))
min_dist = dist.min(axis=1)

mask = min_dist > 0.01
candidates = candidates[mask]
min_dist = min_dist[mask]

# Exploitation: distance to top-performing region
dist_to_top = np.min(
    np.sqrt(((candidates[:, None, :] - top_points[None, :, :])**2).sum(axis=2)),
    axis=1
)

exploit_score = 1 - dist_to_top / (dist_to_top.max() + 1e-12)

# Exploration: distance from known points
explore_score = min_dist / (min_dist.max() + 1e-12)

# Exploration slightly dominates (noise-aware)
score = 0.45 * exploit_score + 0.55 * explore_score

next_query = candidates[np.argmax(score)]

query_string = "-".join([f"{v:0.6f}" for v in next_query])

print("Next query:")
print(query_string)


Dataset shape: (15, 2)
Number of top points: 5
Next query:
0.872215-0.378675


In [ ]:
#WEEK 7
Combined_input_data6 = np.load("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_2/W6_inputs.npy")
Combined_output_data6 = np.load("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_2/W6_outputs.npy")

new_data_point = np.array([[00.872215, 0.378675]])
Combined_input_data7 = np.concatenate((Combined_input_data6, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_2/W7_inputs.npy", Combined_input_data7)
print(Combined_input_data7)

new_output_data_point = np.array([0.7694789520062829])
Combined_output_data7 = np.concatenate((Combined_output_data6, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_2/W7_outputs.npy", Combined_output_data7)

print(Combined_output_data7)

[[0.66579958 0.12396913]
 [0.87779099 0.7786275 ]
 [0.14269907 0.34900513]
 [0.84527543 0.71112027]
 [0.45464714 0.29045518]
 [0.57771284 0.77197318]
 [0.43816606 0.68501826]
 [0.34174959 0.02869772]
 [0.33864816 0.21386725]
 [0.70263656 0.9265642 ]
 [0.14597    0.921486  ]
 [0.652719   0.877025  ]
 [0.751452   0.87691   ]
 [0.701759   0.877518  ]
 [0.701759   0.877518  ]
 [0.872215   0.378675  ]]
[ 5.38996119e-01  4.20586240e-01 -6.56236244e-02  2.93992912e-01
  2.14964510e-01  2.31055498e-02  2.44619344e-01  3.87490152e-02
 -1.38576181e-02  6.11205216e-01  5.12835000e-02  4.38220570e-01
  5.64844479e-01  5.43040584e-01  5.05430406e+01  7.69478952e-01]


In [ ]:
#WEEK 7

X = Combined_input_data7
y = Combined_output_data7

print("Dataset shape:", X.shape)

TOP_QUANTILE = 0.70      # top 30% treated as good region
EXPLOIT_WEIGHT = 0.45
EXPLORE_WEIGHT = 0.55
LOCAL_RADIUS = 0.04
N_GLOBAL = 4000
N_LOCAL_PER_TOP = 500
MIN_SEP = 0.01
SEED = 321

threshold = np.quantile(y, TOP_QUANTILE)
top_points = X[y >= threshold]

print("Threshold for top region:", threshold)
print("Number of top points:", len(top_points))

# Safety fallback in case very few points qualify
if len(top_points) == 0:
    best_idx = np.argmax(y)
    top_points = X[best_idx:best_idx + 1]

rng = np.random.default_rng(SEED)

lower = X.min(axis=0)
upper = X.max(axis=0)

# Global exploration candidates
global_candidates = rng.uniform(lower, upper, size=(N_GLOBAL, 2))

# Local candidates around all top-performing points
local_candidates = []
for pt in top_points:
    local = rng.normal(loc=pt, scale=LOCAL_RADIUS, size=(N_LOCAL_PER_TOP, 2))
    local_candidates.append(local)

local_candidates = np.vstack(local_candidates)

# Combine and clip to observed bounds
candidates = np.vstack([global_candidates, local_candidates])
candidates = np.clip(candidates, lower, upper)

dist_to_existing = np.sqrt(((candidates[:, None, :] - X[None, :, :]) ** 2).sum(axis=2))
min_dist_existing = dist_to_existing.min(axis=1)

mask = min_dist_existing > MIN_SEP
candidates = candidates[mask]
min_dist_existing = min_dist_existing[mask]

print("Candidates after filtering:", candidates.shape[0])

# Exploitation: closer to any top-performing point is better
dist_to_top = np.sqrt(((candidates[:, None, :] - top_points[None, :, :]) ** 2).sum(axis=2))
min_dist_top = dist_to_top.min(axis=1)
exploit_score = 1 - min_dist_top / (min_dist_top.max() + 1e-12)

# Exploration: farther from existing points is better
explore_score = min_dist_existing / (min_dist_existing.max() + 1e-12)

# Combined score (slightly exploration-heavy due to noise)
score = EXPLOIT_WEIGHT * exploit_score + EXPLORE_WEIGHT * explore_score

next_query = candidates[np.argmax(score)]

query_string = "-".join([f"{v:0.6f}" for v in next_query])

print("Next query:")
print(query_string)

Dataset shape: (16, 2)
Threshold for top region: 0.5410183516985972
Number of top points: 5
Candidates after filtering: 6232
Next query:
0.640096-0.510236


In [3]:
#WEEK 8

new_data_point = np.array([[0.640096, 0.510236]])
Combined_input_data8 = np.concatenate((Combined_input_data7, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_2/W8_inputs.npy", Combined_input_data8)
print(Combined_input_data8)

new_output_data_point = np.array([0.2194199409557066])
Combined_output_data8 = np.concatenate((Combined_output_data7, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_2/W8_outputs.npy", Combined_output_data8)

print(Combined_output_data8)

[[0.66579958 0.12396913]
 [0.87779099 0.7786275 ]
 [0.14269907 0.34900513]
 [0.84527543 0.71112027]
 [0.45464714 0.29045518]
 [0.57771284 0.77197318]
 [0.43816606 0.68501826]
 [0.34174959 0.02869772]
 [0.33864816 0.21386725]
 [0.70263656 0.9265642 ]
 [0.14597    0.921486  ]
 [0.652719   0.877025  ]
 [0.751452   0.87691   ]
 [0.701759   0.877518  ]
 [0.701759   0.877518  ]
 [0.872215   0.378675  ]
 [0.640096   0.510236  ]]
[ 5.38996119e-01  4.20586240e-01 -6.56236244e-02  2.93992912e-01
  2.14964510e-01  2.31055498e-02  2.44619344e-01  3.87490152e-02
 -1.38576181e-02  6.11205216e-01  5.12835000e-02  4.38220570e-01
  5.64844479e-01  5.43040584e-01  5.05430406e+01  7.69478952e-01
  2.19419941e-01]


In [ ]:
#WEEK 8 

X = Combined_input_data8
y = Combined_output_data8

print("Dataset shape:", X.shape)

# "Higher temperature" -> more exploration because of noise
EXPLOIT_WEIGHT = 0.42
EXPLORE_WEIGHT = 0.58

# top region used as an "attention set"
TOP_QUANTILE = 0.70   # top 30%

# wider local radius than Function 1 because of noise
LOCAL_RADIUS = 0.040

# candidate budget
N_GLOBAL = 5000
N_LOCAL_PER_TOP = 600

# avoid near-duplicate queries
MIN_SEP = 0.01

# top-k shortlist size
TOP_K = 40

SEED = 456

threshold = np.quantile(y, TOP_QUANTILE)
top_points = X[y >= threshold]

print("Threshold for top region:", threshold)
print("Top attention points:", len(top_points))

if len(top_points) == 0:
    best_idx = np.argmax(y)
    top_points = X[best_idx:best_idx+1]

rng = np.random.default_rng(SEED)

lower = X.min(axis=0)
upper = X.max(axis=0)

# global exploration candidates
global_candidates = rng.uniform(lower, upper, size=(N_GLOBAL, 2))

# local candidates around each top-performing point
local_candidates = []
for pt in top_points:
    local = rng.normal(loc=pt, scale=LOCAL_RADIUS, size=(N_LOCAL_PER_TOP, 2))
    local_candidates.append(local)

local_candidates = np.vstack(local_candidates)

# combine and clip to bounds
candidates = np.vstack([global_candidates, local_candidates])
candidates = np.clip(candidates, lower, upper)

dist_to_existing = np.sqrt(((candidates[:, None, :] - X[None, :, :]) ** 2).sum(axis=2))
min_dist_existing = dist_to_existing.min(axis=1)

mask = min_dist_existing > MIN_SEP
candidates = candidates[mask]
min_dist_existing = min_dist_existing[mask]

print("Candidates after filtering:", candidates.shape[0])

# Exploitation: closeness to top-performing region
dist_to_top = np.sqrt(((candidates[:, None, :] - top_points[None, :, :]) ** 2).sum(axis=2))
min_dist_top = dist_to_top.min(axis=1)
exploit_score = 1 - min_dist_top / (min_dist_top.max() + 1e-12)

# Exploration: distance from known points
explore_score = min_dist_existing / (min_dist_existing.max() + 1e-12)

# Combined score
score = EXPLOIT_WEIGHT * exploit_score + EXPLORE_WEIGHT * explore_score

# top-k shortlist
top_k_idx = np.argsort(score)[-TOP_K:]
shortlist = candidates[top_k_idx]
shortlist_score = score[top_k_idx]
shortlist_explore = explore_score[top_k_idx]

# final selection prefers both quality and novelty
final_score = shortlist_score + 0.08 * shortlist_explore
next_query = shortlist[np.argmax(final_score)]

query_string = "-".join([f"{v:0.6f}" for v in next_query])

print("Next query:")
print(query_string)

Dataset shape: (17, 2)
Threshold for top region: 0.5398050120355897
Top attention points: 5
Candidates after filtering: 7648
Next query:
0.389551-0.923422


In [5]:
#WEEK 9

new_data_point = np.array([[0.389551, 0.923422]])
Combined_input_data9 = np.concatenate((Combined_input_data8, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_2/W9_inputs.npy", Combined_input_data9)
print(Combined_input_data9)

new_output_data_point = np.array([-1.9222048797672574e-28])
Combined_output_data9 = np.concatenate((Combined_output_data8, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_2/W9_outputs.npy", Combined_output_data9)

print(Combined_output_data9)

[[0.66579958 0.12396913]
 [0.87779099 0.7786275 ]
 [0.14269907 0.34900513]
 [0.84527543 0.71112027]
 [0.45464714 0.29045518]
 [0.57771284 0.77197318]
 [0.43816606 0.68501826]
 [0.34174959 0.02869772]
 [0.33864816 0.21386725]
 [0.70263656 0.9265642 ]
 [0.14597    0.921486  ]
 [0.652719   0.877025  ]
 [0.751452   0.87691   ]
 [0.701759   0.877518  ]
 [0.701759   0.877518  ]
 [0.872215   0.378675  ]
 [0.640096   0.510236  ]
 [0.389551   0.923422  ]]
[ 5.38996119e-01  4.20586240e-01 -6.56236244e-02  2.93992912e-01
  2.14964510e-01  2.31055498e-02  2.44619344e-01  3.87490152e-02
 -1.38576181e-02  6.11205216e-01  5.12835000e-02  4.38220570e-01
  5.64844479e-01  5.43040584e-01  5.05430406e+01  7.69478952e-01
  2.19419941e-01 -1.92220488e-28]


In [ ]:
#WEEK 9 

X = Combined_input_data9
y = Combined_output_data9

print("Dataset shape:", X.shape)

# Moderate exploitation because noise is still important
EXPLOIT_WEIGHT = 0.55
EXPLORE_WEIGHT = 0.45

# Regional attention rather than single-point trust
TOP_QUANTILE = 0.75   # top 25% = good region

# Slightly wider local search due to noise
LOCAL_RADIUS = 0.030

# Candidate budget
N_LOCAL_TOP = 3500
N_LOCAL_BEST = 1500
N_GLOBAL = 2500

# Shortlist + duplicate protection
TOP_K = 25
MIN_SEP = 0.01

SEED = 789

best_idx = np.argmax(y)
best_x = X[best_idx]
best_y = y[best_idx]

threshold = np.quantile(y, TOP_QUANTILE)
top_points = X[y >= threshold]

print("Best value so far:", best_y)
print("Best point so far:", best_x)
print("Top-region points:", len(top_points))

if len(top_points) == 0:
    top_points = X[best_idx:best_idx + 1]

rng = np.random.default_rng(SEED)

lower = X.min(axis=0)
upper = X.max(axis=0)

# Local candidates around best point
local_best = rng.normal(loc=best_x, scale=LOCAL_RADIUS, size=(N_LOCAL_BEST, 2))

# Local candidates around robust top-performing region
local_top = []
n_per_top = max(80, N_LOCAL_TOP // len(top_points))
for pt in top_points:
    local = rng.normal(loc=pt, scale=LOCAL_RADIUS * 1.1, size=(n_per_top, 2))
    local_top.append(local)
local_top = np.vstack(local_top)

# Global exploration candidates
global_candidates = rng.uniform(lower, upper, size=(N_GLOBAL, 2))

# Combine and clip
candidates = np.vstack([local_best, local_top, global_candidates])
candidates = np.clip(candidates, lower, upper)


dist_to_existing = np.sqrt(((candidates[:, None, :] - X[None, :, :]) ** 2).sum(axis=2))
min_dist_existing = dist_to_existing.min(axis=1)

mask = min_dist_existing > MIN_SEP
candidates = candidates[mask]
min_dist_existing = min_dist_existing[mask]

print("Candidates after filtering:", candidates.shape[0])


# Exploitation: closeness to the top-performing region
dist_to_top = np.sqrt(((candidates[:, None, :] - top_points[None, :, :]) ** 2).sum(axis=2))
min_dist_top = dist_to_top.min(axis=1)
exploit_score = 1 - min_dist_top / (min_dist_top.max() + 1e-12)

# Exploration: novelty relative to previous samples
explore_score = min_dist_existing / (min_dist_existing.max() + 1e-12)

# Combined score
score = EXPLOIT_WEIGHT * exploit_score + EXPLORE_WEIGHT * explore_score


top_k_idx = np.argsort(score)[-TOP_K:]
shortlist = candidates[top_k_idx]
shortlist_score = score[top_k_idx]
shortlist_explore = explore_score[top_k_idx]

# Slight novelty preference among strong candidates
final_score = shortlist_score + 0.05 * shortlist_explore
next_query = shortlist[np.argmax(final_score)]

query_string = "-".join([f"{v:0.6f}" for v in next_query])

print("Next query:")
print(query_string)

Dataset shape: (18, 2)
Best value so far: 50.543040584470276
Best point so far: [0.701759 0.877518]
Top-region points: 5
Candidates after filtering: 6931
Next query:
0.876671-0.156991


In [7]:
#WEEK 10

new_data_point = np.array([[0.876671, 0.156991]])
Combined_input_data10 = np.concatenate((Combined_input_data9, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_2/W10_inputs.npy", Combined_input_data10)
print(Combined_input_data10)

new_output_data_point = np.array([0.40039538635290284])
Combined_output_data10 = np.concatenate((Combined_output_data9, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_2/W10_outputs.npy", Combined_output_data10)

print(Combined_output_data10)

[[0.66579958 0.12396913]
 [0.87779099 0.7786275 ]
 [0.14269907 0.34900513]
 [0.84527543 0.71112027]
 [0.45464714 0.29045518]
 [0.57771284 0.77197318]
 [0.43816606 0.68501826]
 [0.34174959 0.02869772]
 [0.33864816 0.21386725]
 [0.70263656 0.9265642 ]
 [0.14597    0.921486  ]
 [0.652719   0.877025  ]
 [0.751452   0.87691   ]
 [0.701759   0.877518  ]
 [0.701759   0.877518  ]
 [0.872215   0.378675  ]
 [0.640096   0.510236  ]
 [0.389551   0.923422  ]
 [0.876671   0.156991  ]]
[ 5.38996119e-01  4.20586240e-01 -6.56236244e-02  2.93992912e-01
  2.14964510e-01  2.31055498e-02  2.44619344e-01  3.87490152e-02
 -1.38576181e-02  6.11205216e-01  5.12835000e-02  4.38220570e-01
  5.64844479e-01  5.43040584e-01  5.05430406e+01  7.69478952e-01
  2.19419941e-01 -1.92220488e-28  4.00395386e-01]


In [ ]:
#WEEK 10

X = Combined_input_data10
y = Combined_output_data10

lower = X.min(axis=0)
upper = X.max(axis=0)

threshold = np.quantile(y, 0.75)
top_points = X[y >= threshold]

center = top_points.mean(axis=0)

rng = np.random.default_rng(101)
candidates = rng.normal(loc=center, scale=0.03, size=(2000, 2))
candidates = np.clip(candidates, lower, upper)

dist = np.sqrt(((candidates[:, None, :] - X[None, :, :]) ** 2).sum(axis=2))
min_dist = dist.min(axis=1)

next_query = candidates[np.argmax(min_dist)]
query_string = "-".join([f"{v:0.6f}" for v in next_query])
print(query_string)

0.698401-0.703055


In [9]:
#WEEK 11

new_data_point = np.array([[0.698401, 0.703055]])
Combined_input_data11 = np.concatenate((Combined_input_data10, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_2/W11_inputs.npy", Combined_input_data11)
print(Combined_input_data11)

new_output_data_point = np.array([0.6280379485856032])
Combined_output_data11 = np.concatenate((Combined_output_data10, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_2/W11_outputs.npy", Combined_output_data11)

print(Combined_output_data11)

[[0.66579958 0.12396913]
 [0.87779099 0.7786275 ]
 [0.14269907 0.34900513]
 [0.84527543 0.71112027]
 [0.45464714 0.29045518]
 [0.57771284 0.77197318]
 [0.43816606 0.68501826]
 [0.34174959 0.02869772]
 [0.33864816 0.21386725]
 [0.70263656 0.9265642 ]
 [0.14597    0.921486  ]
 [0.652719   0.877025  ]
 [0.751452   0.87691   ]
 [0.701759   0.877518  ]
 [0.701759   0.877518  ]
 [0.872215   0.378675  ]
 [0.640096   0.510236  ]
 [0.389551   0.923422  ]
 [0.876671   0.156991  ]
 [0.698401   0.703055  ]]
[ 5.38996119e-01  4.20586240e-01 -6.56236244e-02  2.93992912e-01
  2.14964510e-01  2.31055498e-02  2.44619344e-01  3.87490152e-02
 -1.38576181e-02  6.11205216e-01  5.12835000e-02  4.38220570e-01
  5.64844479e-01  5.43040584e-01  5.05430406e+01  7.69478952e-01
  2.19419941e-01 -1.92220488e-28  4.00395386e-01  6.28037949e-01]


In [ ]:
#WEEK 11
from sklearn.cluster import KMeans

X = Combined_input_data11
y = Combined_output_data11

threshold = np.quantile(y, 0.70)
top_X = X[y >= threshold]
top_y = y[y >= threshold]

k = min(3, len(top_X))
kmeans = KMeans(n_clusters=k, random_state=12, n_init=10)
labels = kmeans.fit_predict(top_X)

best_cluster = None
best_score = -np.inf

for c in range(k):
    cluster_points = top_X[labels == c]
    cluster_y = top_y[labels == c]
    # prefer high mean and low variance
    score = cluster_y.mean() - 0.2 * cluster_y.std()
    if score > best_score:
        best_score = score
        best_cluster = cluster_points

centroid = best_cluster.mean(axis=0)

rng = np.random.default_rng(12)
candidates = rng.normal(loc=centroid, scale=0.03, size=(2000, 2))
candidates = np.clip(candidates, X.min(axis=0), X.max(axis=0))

dist = np.sqrt(((candidates[:, None, :] - X[None, :, :]) ** 2).sum(axis=2))
next_query = candidates[np.argmax(dist.min(axis=1))]

print("-".join([f"{v:0.6f}" for v in next_query]))

0.739923-0.792855


In [11]:
#WEEK 12

new_data_point = np.array([[0.739923, 0.792855]])
Combined_input_data12 = np.concatenate((Combined_input_data11, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_2/W12_inputs.npy", Combined_input_data12)
print(Combined_input_data12)

new_output_data_point = np.array([0.41753878893437696])
Combined_output_data12 = np.concatenate((Combined_output_data11, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_2/W12_outputs.npy", Combined_output_data12)

print(Combined_output_data12)

[[0.66579958 0.12396913]
 [0.87779099 0.7786275 ]
 [0.14269907 0.34900513]
 [0.84527543 0.71112027]
 [0.45464714 0.29045518]
 [0.57771284 0.77197318]
 [0.43816606 0.68501826]
 [0.34174959 0.02869772]
 [0.33864816 0.21386725]
 [0.70263656 0.9265642 ]
 [0.14597    0.921486  ]
 [0.652719   0.877025  ]
 [0.751452   0.87691   ]
 [0.701759   0.877518  ]
 [0.701759   0.877518  ]
 [0.872215   0.378675  ]
 [0.640096   0.510236  ]
 [0.389551   0.923422  ]
 [0.876671   0.156991  ]
 [0.698401   0.703055  ]
 [0.739923   0.792855  ]]
[ 5.38996119e-01  4.20586240e-01 -6.56236244e-02  2.93992912e-01
  2.14964510e-01  2.31055498e-02  2.44619344e-01  3.87490152e-02
 -1.38576181e-02  6.11205216e-01  5.12835000e-02  4.38220570e-01
  5.64844479e-01  5.43040584e-01  5.05430406e+01  7.69478952e-01
  2.19419941e-01 -1.92220488e-28  4.00395386e-01  6.28037949e-01
  4.17538789e-01]


In [ ]:
#WEEK 12

from sklearn.decomposition import PCA

X = Combined_input_data12
y = Combined_output_data12

threshold = np.quantile(y, 0.70)
top_X = X[y >= threshold]

center = top_X.mean(axis=0)
lower = X.min(axis=0)
upper = X.max(axis=0)

pca = PCA(n_components=2)
pca.fit(top_X)
pc1 = pca.components_[0]

rng = np.random.default_rng(122)
n_candidates = 4000

steps = rng.normal(0.0, 0.03, size=(n_candidates, 1))
noise = rng.normal(0, 0.015, size=(n_candidates, 2))
candidates = center + steps * pc1 + noise
candidates = np.clip(candidates, lower, upper)

dist = np.sqrt(((candidates[:, None, :] - X[None, :, :])**2).sum(axis=2))
min_dist = dist.min(axis=1)

next_query = candidates[np.argmax(min_dist)]
print("-".join([f"{v:0.6f}" for v in next_query]))

0.760606-0.586254


In [13]:
#WEEK 13

new_data_point = np.array([[0.760606, 0.586254]])
Combined_input_data13 = np.concatenate((Combined_input_data12, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_2/W13_inputs.npy", Combined_input_data13)
print(Combined_input_data13)

new_output_data_point = np.array([0.21584187372047284])
Combined_output_data13 = np.concatenate((Combined_output_data12, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_2/W13_outputs.npy", Combined_output_data13)

print(Combined_output_data13)

[[0.66579958 0.12396913]
 [0.87779099 0.7786275 ]
 [0.14269907 0.34900513]
 [0.84527543 0.71112027]
 [0.45464714 0.29045518]
 [0.57771284 0.77197318]
 [0.43816606 0.68501826]
 [0.34174959 0.02869772]
 [0.33864816 0.21386725]
 [0.70263656 0.9265642 ]
 [0.14597    0.921486  ]
 [0.652719   0.877025  ]
 [0.751452   0.87691   ]
 [0.701759   0.877518  ]
 [0.701759   0.877518  ]
 [0.872215   0.378675  ]
 [0.640096   0.510236  ]
 [0.389551   0.923422  ]
 [0.876671   0.156991  ]
 [0.698401   0.703055  ]
 [0.739923   0.792855  ]
 [0.760606   0.586254  ]]
[ 5.38996119e-01  4.20586240e-01 -6.56236244e-02  2.93992912e-01
  2.14964510e-01  2.31055498e-02  2.44619344e-01  3.87490152e-02
 -1.38576181e-02  6.11205216e-01  5.12835000e-02  4.38220570e-01
  5.64844479e-01  5.43040584e-01  5.05430406e+01  7.69478952e-01
  2.19419941e-01 -1.92220488e-28  4.00395386e-01  6.28037949e-01
  4.17538789e-01  2.15841874e-01]


In [ ]:
#WEEK 13

X = Combined_input_data13
y = Combined_output_data13

lower = X.min(axis=0)
upper = X.max(axis=0)

threshold = np.quantile(y, 0.75)
top_X = X[y >= threshold]
top_y = y[y >= threshold]

k = min(3, len(top_X))
kmeans = KMeans(n_clusters=k, random_state=102, n_init=10)
labels = kmeans.fit_predict(top_X)

best_cluster = None
best_score = -np.inf

for c in range(k):
    cluster_points = top_X[labels == c]
    cluster_y = top_y[labels == c]
    # robust reward: mean - penalty for variance
    score = cluster_y.mean() - 0.2 * cluster_y.std()
    if score > best_score:
        best_score = score
        best_cluster = cluster_points

centroid = best_cluster.mean(axis=0)

# Small exploration hedge around robust region
rng = np.random.default_rng(102)
candidates = rng.normal(loc=centroid, scale=0.02, size=(2000, 2))
candidates = np.clip(candidates, lower, upper)

dist = np.sqrt(((candidates[:, None, :] - X[None, :, :])**2).sum(axis=2))
min_dist = dist.min(axis=1)

next_query = candidates[np.argmax(min_dist)]
print("-".join([f"{v:0.6f}" for v in next_query]))

0.678610-0.820126
