In [1]:
#Load packages required for loading the npy files.
import numpy as np
import pandas as pd

# #Load the npy file called "data.npy"
Initial_input_data = np.load("/Users/mayukotakamiya/MachineLearning/initial_data/function_6/initial_inputs.npy")
Initial_output_data = np.load("/Users/mayukotakamiya/MachineLearning/initial_data/function_6/initial_outputs.npy")

#I want to know dimentionality of the initial_input_data  
Initial_input_data.shape




(20, 5)

In [2]:

# X and y already loaded
X = Initial_input_data
y = Initial_output_data

def propose_next_point(X, y, n_candidates=8000, w_exploit=0.6, w_explore=0.4, seed=42):
    """
    Simple explore/exploit heuristic:
    - exploit: sample near best observed point
    - explore: sample far from existing samples
    """

    rng = np.random.default_rng(seed)
    n, d = X.shape

    # Best observed point so far
    best_x = X[np.argmax(y)]

    # Determine sampling bounds from existing data
    lower_bounds = X.min(axis=0)
    upper_bounds = X.max(axis=0)

    # Generate random candidate points within observed bounds
    C = rng.uniform(lower_bounds, upper_bounds, size=(n_candidates, d))

    # Exploitation term (closer to best is better)
    dist_to_best = np.linalg.norm(C - best_x, axis=1)
    exploit = 1 - (dist_to_best / (dist_to_best.max() + 1e-12))

    # Exploration term (farther from existing points is better)
    dists = np.sqrt(((C[:, None, :] - X[None, :, :]) ** 2).sum(axis=2))
    min_dist = dists.min(axis=1)
    explore = min_dist / (min_dist.max() + 1e-12)

    # Combined score
    score = w_exploit * exploit + w_explore * explore

    return C[np.argmax(score)]

def format_query(x):
    return "-".join([f"{v:0.6f}" for v in x])

# Generate next query
next_x = propose_next_point(X, y)

print("Submit this to the portal:")
print(format_query(next_x))

Submit this to the portal:
0.145970-0.921486


In [2]:
###WEEK 2
#I want to see the data in /Users/mayukotakamiya/MachineLearning/initial_data/function_1/initial_inputs.npy
print(Initial_input_data)
#I WANT TO create a new npy file by adding a new data point which is [0.433534 0.458467]
new_data_point = np.array([[0.954643, 0.122648, 0.952408, 0.157563, 0.481674]])
Combined_input_data = np.concatenate((Initial_input_data, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_6/W2_inputs.npy", Combined_input_data)
print(Combined_input_data)

[[0.7281861  0.15469257 0.73255167 0.69399651 0.05640131]
 [0.24238435 0.84409997 0.5778091  0.67902128 0.50195289]
 [0.72952261 0.7481062  0.67977464 0.35655228 0.67105368]
 [0.77062024 0.11440374 0.04677993 0.64832428 0.27354905]
 [0.6188123  0.33180214 0.18728787 0.75623847 0.3288348 ]
 [0.78495809 0.91068235 0.7081201  0.95922543 0.0049115 ]
 [0.14511079 0.8966846  0.89632223 0.72627154 0.23627199]
 [0.94506907 0.28845905 0.97880576 0.96165559 0.59801594]
 [0.12572016 0.86272469 0.02854433 0.24660527 0.75120624]
 [0.75759436 0.35583141 0.0165229  0.4342072  0.11243304]
 [0.5367969  0.30878091 0.41187929 0.38822518 0.5225283 ]
 [0.95773967 0.23566857 0.09914585 0.15680593 0.07131737]
 [0.6293079  0.80348368 0.81140844 0.04561319 0.11062446]
 [0.02173531 0.42808424 0.83593944 0.48948866 0.51108173]
 [0.43934426 0.69892383 0.42682022 0.10947609 0.87788847]
 [0.25890557 0.79367771 0.6421139  0.19667346 0.59310318]
 [0.43216593 0.71561781 0.3418191  0.70499988 0.61496184]
 [0.78287982 0

In [3]:
print(Initial_output_data)

#I want to create a new npy file bt adding a new data point to the Initial_output_data
new_output_data_point = np.array([-2.061197721706384])
Combined_output_data = np.concatenate((Initial_output_data, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_6/W2_outputs.npy", Combined_output_data)

print(Combined_output_data)

[-0.71426495 -1.20995524 -1.67219994 -1.53605771 -0.82923655 -1.24704893
 -1.23378638 -1.69434344 -2.57116963 -1.30911635 -1.14478485 -1.91267714
 -1.62283895 -1.35668211 -2.0184254  -1.70255784 -1.29424696 -0.93575656
 -2.15576776 -1.74688209]
[-0.71426495 -1.20995524 -1.67219994 -1.53605771 -0.82923655 -1.24704893
 -1.23378638 -1.69434344 -2.57116963 -1.30911635 -1.14478485 -1.91267714
 -1.62283895 -1.35668211 -2.0184254  -1.70255784 -1.29424696 -0.93575656
 -2.15576776 -1.74688209 -2.06119772]


In [87]:
#Assess the exploitation vs exploration strategy
x=Combined_input_data
y=Combined_output_data

best_score_w2= np.max(y)
improvement= best_score_w2 - np.max(Initial_output_data)

print("Improvement:", improvement)
print("Output range:", y.min(), "to", y.max())
print("Std deviation:", np.std(y))


Improvement: 0.007087524491951498
Output range: -0.0036060626443634764 to 0.007087524491952269
Std deviation: 0.002376682573738607


In [ ]:
##Function1- For week2, it seems there is a big improvement by having the improvement more than 10% of the output range. Therefore, more exploitation than exploration.
##Function2- For week2, no improvement at all. Therefore use more exploration than exploitation
##Function3- for week2, no improvement at all.Therefore use more exploration than exploitation. 
##Function4- for week2, no improvement at all.Therefore use more exploration than exploitation. 
##Function5- for week2, no improvement at all.Therefore use more exploration than exploitation. 
##Function6- for week2, no improvement at all.Therefore use more exploration than exploitation. 
##Function7- for week2, no improvement at all.Therefore use more exploration than exploitation. 
#Function8- for week2, there is small-moderate improvement. Take a balanced approach (6:4)

In [88]:
#Re-run the loop
X=Combined_input_data
y=Combined_output_data

def propose_next_point(X, y, n_candidates=8000, w_exploit=0.75, w_explore=0.25, seed=234):
    """
    Simple explore/exploit heuristic:
    - exploit: sample near best observed point
    - explore: sample far from existing samples
    """

    rng = np.random.default_rng(seed)
    n, d = X.shape

    # Best observed point so far
    best_x = X[np.argmax(y)]
    
    radius = 0.05  # small local refinement

    # Determine sampling bounds from existing data
    lower = np.maximum(best_x - radius, X.min(axis=0))
    upper = np.minimum(best_x + radius, X.max(axis=0))


    # Generate random candidate points within observed bounds
    C = rng.uniform(lower, upper, size=(n_candidates, d))

    # Exploitation term (closer to best is better)
    dist_to_best = np.linalg.norm(C - best_x, axis=1)
    exploit = 1 - (dist_to_best / (dist_to_best.max() + 1e-12))

    # Exploration term (farther from existing points is better)
    dists = np.sqrt(((C[:, None, :] - X[None, :, :]) ** 2).sum(axis=2))
    min_dist = dists.min(axis=1)
    explore = min_dist / (min_dist.max() + 1e-12)

    # Combined score
    score = w_exploit * exploit + w_explore * explore

    return C[np.argmax(score)]

def format_query(x):
    return "-".join([f"{v:0.6f}" for v in x])

# Generate next query
next_x = propose_next_point(X, y)

print("Submit this to the portal:")
print(format_query(next_x))

Submit this to the portal:
0.433582-0.457940


In [4]:
####WEEK 3
new_data_point = np.array([[0.686711, 0.202156, 0.686200, 0.644513, 0.100754]])
Combined_input_data3 = np.concatenate((Combined_input_data, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_6/W3_inputs.npy", Combined_input_data3)
print(Combined_input_data3)

new_output_data_point = np.array([-0.64620117628392])
Combined_output_data3 = np.concatenate((Combined_output_data, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_6/W3_outputs.npy", Combined_output_data3)

print(Combined_output_data3)


[[0.7281861  0.15469257 0.73255167 0.69399651 0.05640131]
 [0.24238435 0.84409997 0.5778091  0.67902128 0.50195289]
 [0.72952261 0.7481062  0.67977464 0.35655228 0.67105368]
 [0.77062024 0.11440374 0.04677993 0.64832428 0.27354905]
 [0.6188123  0.33180214 0.18728787 0.75623847 0.3288348 ]
 [0.78495809 0.91068235 0.7081201  0.95922543 0.0049115 ]
 [0.14511079 0.8966846  0.89632223 0.72627154 0.23627199]
 [0.94506907 0.28845905 0.97880576 0.96165559 0.59801594]
 [0.12572016 0.86272469 0.02854433 0.24660527 0.75120624]
 [0.75759436 0.35583141 0.0165229  0.4342072  0.11243304]
 [0.5367969  0.30878091 0.41187929 0.38822518 0.5225283 ]
 [0.95773967 0.23566857 0.09914585 0.15680593 0.07131737]
 [0.6293079  0.80348368 0.81140844 0.04561319 0.11062446]
 [0.02173531 0.42808424 0.83593944 0.48948866 0.51108173]
 [0.43934426 0.69892383 0.42682022 0.10947609 0.87788847]
 [0.25890557 0.79367771 0.6421139  0.19667346 0.59310318]
 [0.43216593 0.71561781 0.3418191  0.70499988 0.61496184]
 [0.78287982 0

In [5]:
#WEEK 3 Assess the exploitation vs exploration strategy
x=Combined_input_data3
y=Combined_output_data3

best_score_w2= np.max(y)
improvement= best_score_w2 - np.max(Combined_output_data)

print("Improvement:", improvement)
print("Output range:", y.min(), "to", y.max())
print("Std deviation:", np.std(y))

Improvement: 0.06806377153632037
Output range: -2.5711696316081234 to -0.64620117628392
Std deviation: 0.4800389391561264


In [6]:
#WEEK 3 -re run the loop. moderate improvement so adjust exploit vs explore ratio to 0.55: 0.45
X=Combined_input_data3
y=Combined_output_data3

def propose_next_point(X, y, n_candidates=8000, w_exploit=0.55, w_explore=0.45, seed=234):

    rng = np.random.default_rng(seed)
    n, d = X.shape

    # Best observed point so far
    best_x = X[np.argmax(y)]
    
    radius = 0.05  # small local refinement

    # Determine sampling bounds from existing data
    lower = np.maximum(best_x - radius, X.min(axis=0))
    upper = np.minimum(best_x + radius, X.max(axis=0))


    # Generate random candidate points within observed bounds
    C = rng.uniform(lower, upper, size=(n_candidates, d))

    # Exploitation term (closer to best is better)
    dist_to_best = np.linalg.norm(C - best_x, axis=1)
    exploit = 1 - (dist_to_best / (dist_to_best.max() + 1e-12))

    # Exploration term (farther from existing points is better)
    dists = np.sqrt(((C[:, None, :] - X[None, :, :]) ** 2).sum(axis=2))
    min_dist = dists.min(axis=1)
    explore = min_dist / (min_dist.max() + 1e-12)

    # Combined score
    score = w_exploit * exploit + w_explore * explore

    return C[np.argmax(score)]

def format_query(x):
    return "-".join([f"{v:0.6f}" for v in x])

# Generate next query
next_x = propose_next_point(X, y)

print("Submit this to the portal:")
print(format_query(next_x))

Submit this to the portal:
0.686137-0.210601-0.685594-0.646791-0.108468


In [7]:
####WEEK 4
new_data_point = np.array([[0.686137, 0.210601, 0.685594, 0.646791, 0.108468]])
Combined_input_data4 = np.concatenate((Combined_input_data3, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_6/W4_inputs.npy", Combined_input_data4)
print(Combined_input_data4)

new_output_data_point = np.array([-0.5337419878421241])
Combined_output_data4 = np.concatenate((Combined_output_data3, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_6/W4_outputs.npy", Combined_output_data4)

print(Combined_output_data4)

[[0.7281861  0.15469257 0.73255167 0.69399651 0.05640131]
 [0.24238435 0.84409997 0.5778091  0.67902128 0.50195289]
 [0.72952261 0.7481062  0.67977464 0.35655228 0.67105368]
 [0.77062024 0.11440374 0.04677993 0.64832428 0.27354905]
 [0.6188123  0.33180214 0.18728787 0.75623847 0.3288348 ]
 [0.78495809 0.91068235 0.7081201  0.95922543 0.0049115 ]
 [0.14511079 0.8966846  0.89632223 0.72627154 0.23627199]
 [0.94506907 0.28845905 0.97880576 0.96165559 0.59801594]
 [0.12572016 0.86272469 0.02854433 0.24660527 0.75120624]
 [0.75759436 0.35583141 0.0165229  0.4342072  0.11243304]
 [0.5367969  0.30878091 0.41187929 0.38822518 0.5225283 ]
 [0.95773967 0.23566857 0.09914585 0.15680593 0.07131737]
 [0.6293079  0.80348368 0.81140844 0.04561319 0.11062446]
 [0.02173531 0.42808424 0.83593944 0.48948866 0.51108173]
 [0.43934426 0.69892383 0.42682022 0.10947609 0.87788847]
 [0.25890557 0.79367771 0.6421139  0.19667346 0.59310318]
 [0.43216593 0.71561781 0.3418191  0.70499988 0.61496184]
 [0.78287982 0

In [ ]:
##WEEK 4 -NN surrogate
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPRegressor

X = Combined_input_data4
y = Combined_output_data4

print("Dataset shape:", X.shape)

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

model = MLPRegressor(
    hidden_layer_sizes=(20,10),
    activation='relu',
    solver='adam',
    max_iter=2000,
    random_state=42
)

model.fit(X_scaled, y)

best_idx = np.argmax(y)
best_x = X[best_idx]

rng = np.random.default_rng(42)

# global exploration candidates
lower = X.min(axis=0)
upper = X.max(axis=0)

global_candidates = rng.uniform(lower, upper, size=(5000, X.shape[1]))

# local refinement candidates around best point
local_candidates = rng.normal(best_x, 0.05, size=(5000, X.shape[1]))
local_candidates = np.clip(local_candidates, lower, upper)

# combine
candidates = np.vstack([global_candidates, local_candidates])

dist = np.sqrt(((candidates[:,None,:] - X[None,:,:])**2).sum(axis=2))
min_dist = dist.min(axis=1)

mask = min_dist > 0.01
candidates = candidates[mask]

candidates_scaled = scaler.transform(candidates)
predictions = model.predict(candidates_scaled)


best_candidate = candidates[np.argmax(predictions)]


query_string = "-".join([f"{v:0.6f}" for v in best_candidate])

print("Next query:")
print(query_string)

Dataset shape: (23, 5)
Next query:
0.139277-0.236039-0.917640-0.671865-0.049716


In [9]:
#WEEK 5 
new_data_point = np.array([[0.139277, 0.236039, 0.917640, 0.671865, 0.049716]])
Combined_input_data5 = np.concatenate((Combined_input_data4, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_6/W5_inputs.npy", Combined_input_data5)
print(Combined_input_data5)

new_output_data_point = np.array([-0.7907330891626921])
Combined_output_data5 = np.concatenate((Combined_output_data4, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_6/W5_outputs.npy", Combined_output_data5)

print(Combined_output_data5)

[[0.7281861  0.15469257 0.73255167 0.69399651 0.05640131]
 [0.24238435 0.84409997 0.5778091  0.67902128 0.50195289]
 [0.72952261 0.7481062  0.67977464 0.35655228 0.67105368]
 [0.77062024 0.11440374 0.04677993 0.64832428 0.27354905]
 [0.6188123  0.33180214 0.18728787 0.75623847 0.3288348 ]
 [0.78495809 0.91068235 0.7081201  0.95922543 0.0049115 ]
 [0.14511079 0.8966846  0.89632223 0.72627154 0.23627199]
 [0.94506907 0.28845905 0.97880576 0.96165559 0.59801594]
 [0.12572016 0.86272469 0.02854433 0.24660527 0.75120624]
 [0.75759436 0.35583141 0.0165229  0.4342072  0.11243304]
 [0.5367969  0.30878091 0.41187929 0.38822518 0.5225283 ]
 [0.95773967 0.23566857 0.09914585 0.15680593 0.07131737]
 [0.6293079  0.80348368 0.81140844 0.04561319 0.11062446]
 [0.02173531 0.42808424 0.83593944 0.48948866 0.51108173]
 [0.43934426 0.69892383 0.42682022 0.10947609 0.87788847]
 [0.25890557 0.79367771 0.6421139  0.19667346 0.59310318]
 [0.43216593 0.71561781 0.3418191  0.70499988 0.61496184]
 [0.78287982 0

In [ ]:
#WEEK 5- Neural network surrogate (more expressive model), Balanced exploration–exploitation (since improvement was moderate, not strong), Higher-dimensional search awareness, Feature influence learning (deep learning concept)


X = Combined_input_data5
y = Combined_output_data5

print("Dataset shape:", X.shape)

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)


model = MLPRegressor(
    hidden_layer_sizes=(32, 16),   # slightly larger for 5D
    activation="relu",
    solver="adam",
    max_iter=3000,
    random_state=42
)

model.fit(X_scaled, y)

best_idx = np.argmax(y)
best_x = X[best_idx]

print("Best value:", y[best_idx])

rng = np.random.default_rng(42)

lower = X.min(axis=0)
upper = X.max(axis=0)

# Global exploration (important in 5D)
global_candidates = rng.uniform(lower, upper, size=(6000, 5))

# Local refinement (around best point)
local_candidates = rng.normal(loc=best_x, scale=0.04, size=(6000, 5))
local_candidates = np.clip(local_candidates, lower, upper)

# Combine
candidates = np.vstack([global_candidates, local_candidates])

dist = np.sqrt(((candidates[:, None, :] - X[None, :, :])**2).sum(axis=2))
min_dist = dist.min(axis=1)

mask = min_dist > 0.01
candidates = candidates[mask]
min_dist = min_dist[mask]

candidates_scaled = scaler.transform(candidates)
predictions = model.predict(candidates_scaled)

explore_score = min_dist / (min_dist.max() + 1e-12)

# Balanced strategy (since improvement was moderate)
score = predictions + 0.1 * explore_score

next_query = candidates[np.argmax(score)]

query_string = "-".join([f"{v:0.6f}" for v in next_query])

print("Next query:")
print(query_string)

Dataset shape: (24, 5)
Best value: -0.5337419878421241
Next query:
0.436300-0.369267-0.633968-0.608580-0.014144


In [11]:
#WEEK 6
new_data_point = np.array([[0.139277, 0.236039, 0.917640, 0.671865, 0.049716]])
Combined_input_data6 = np.concatenate((Combined_input_data5, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_6/W6_inputs.npy", Combined_input_data6)
print(Combined_input_data6)

new_output_data_point = np.array([-0.7907330891626921])
Combined_output_data6 = np.concatenate((Combined_output_data5, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_6/W6_outputs.npy", Combined_output_data6)

print(Combined_output_data6)

[[0.7281861  0.15469257 0.73255167 0.69399651 0.05640131]
 [0.24238435 0.84409997 0.5778091  0.67902128 0.50195289]
 [0.72952261 0.7481062  0.67977464 0.35655228 0.67105368]
 [0.77062024 0.11440374 0.04677993 0.64832428 0.27354905]
 [0.6188123  0.33180214 0.18728787 0.75623847 0.3288348 ]
 [0.78495809 0.91068235 0.7081201  0.95922543 0.0049115 ]
 [0.14511079 0.8966846  0.89632223 0.72627154 0.23627199]
 [0.94506907 0.28845905 0.97880576 0.96165559 0.59801594]
 [0.12572016 0.86272469 0.02854433 0.24660527 0.75120624]
 [0.75759436 0.35583141 0.0165229  0.4342072  0.11243304]
 [0.5367969  0.30878091 0.41187929 0.38822518 0.5225283 ]
 [0.95773967 0.23566857 0.09914585 0.15680593 0.07131737]
 [0.6293079  0.80348368 0.81140844 0.04561319 0.11062446]
 [0.02173531 0.42808424 0.83593944 0.48948866 0.51108173]
 [0.43934426 0.69892383 0.42682022 0.10947609 0.87788847]
 [0.25890557 0.79367771 0.6421139  0.19667346 0.59310318]
 [0.43216593 0.71561781 0.3418191  0.70499988 0.61496184]
 [0.78287982 0

In [ ]:
## WEEK 6 
#Use a neural network surrogate
#Combine:
#global exploration (important in 5D)
#local refinement
#Keep a balanced scoring function
#Avoid overfitting by not over-exploiting

X = Combined_input_data6
y = Combined_output_data6

print("Dataset shape:", X.shape)

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

model = MLPRegressor(
    hidden_layer_sizes=(32, 16),   # moderate depth for 5D
    activation="relu",
    solver="adam",
    alpha=1e-3,                    # regularisation
    max_iter=3500,
    random_state=42
)

model.fit(X_scaled, y)

best_idx = np.argmax(y)
best_x = X[best_idx]

print("Best value:", y[best_idx])

rng = np.random.default_rng(123)

lower = X.min(axis=0)
upper = X.max(axis=0)

# Global exploration (important in 5D)
global_candidates = rng.uniform(lower, upper, size=(6000, 5))

# Local refinement around best point
local_candidates = rng.normal(loc=best_x, scale=0.04, size=(6000, 5))
local_candidates = np.clip(local_candidates, lower, upper)

# Combine candidates
candidates = np.vstack([global_candidates, local_candidates])

dist = np.sqrt(((candidates[:, None, :] - X[None, :, :])**2).sum(axis=2))
min_dist = dist.min(axis=1)

mask = min_dist > 0.01
candidates = candidates[mask]
min_dist = min_dist[mask]

print("Candidates after filtering:", candidates.shape[0])

candidates_scaled = scaler.transform(candidates)
predictions = model.predict(candidates_scaled)

explore_score = min_dist / (min_dist.max() + 1e-12)

# Balanced exploration–exploitation
score = predictions + 0.10 * explore_score

best_candidate_idx = np.argmax(score)
next_query = candidates[best_candidate_idx]

print("Predicted best value:", predictions[best_candidate_idx])

query_string = "-".join([f"{v:0.6f}" for v in next_query])

print("Next query:")
print(query_string)

Dataset shape: (25, 5)
Best value: -0.5337419878421241
Candidates after filtering: 11996
Predicted best value: -0.519991242425857
Next query:
0.476298-0.538763-0.409703-0.575815-0.067376


In [ ]:
#WEEK 7
Combined_input_data6 = np.load("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_6/W6_inputs.npy")
Combined_output_data6 = np.load("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_6/W6_outputs.npy")

new_data_point = np.array([[0.476298, 0.538763, 0.409703, 0.575815, 0.067376]])
Combined_input_data7 = np.concatenate((Combined_input_data6, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_6/W7_inputs.npy", Combined_input_data7)
print(Combined_input_data7)

new_output_data_point = np.array([-0.6493962248983561])
Combined_output_data7 = np.concatenate((Combined_output_data6, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_6/W7_outputs.npy", Combined_output_data7)

print(Combined_output_data7)

[[0.7281861  0.15469257 0.73255167 0.69399651 0.05640131]
 [0.24238435 0.84409997 0.5778091  0.67902128 0.50195289]
 [0.72952261 0.7481062  0.67977464 0.35655228 0.67105368]
 [0.77062024 0.11440374 0.04677993 0.64832428 0.27354905]
 [0.6188123  0.33180214 0.18728787 0.75623847 0.3288348 ]
 [0.78495809 0.91068235 0.7081201  0.95922543 0.0049115 ]
 [0.14511079 0.8966846  0.89632223 0.72627154 0.23627199]
 [0.94506907 0.28845905 0.97880576 0.96165559 0.59801594]
 [0.12572016 0.86272469 0.02854433 0.24660527 0.75120624]
 [0.75759436 0.35583141 0.0165229  0.4342072  0.11243304]
 [0.5367969  0.30878091 0.41187929 0.38822518 0.5225283 ]
 [0.95773967 0.23566857 0.09914585 0.15680593 0.07131737]
 [0.6293079  0.80348368 0.81140844 0.04561319 0.11062446]
 [0.02173531 0.42808424 0.83593944 0.48948866 0.51108173]
 [0.43934426 0.69892383 0.42682022 0.10947609 0.87788847]
 [0.25890557 0.79367771 0.6421139  0.19667346 0.59310318]
 [0.43216593 0.71561781 0.3418191  0.70499988 0.61496184]
 [0.78287982 0

In [ ]:
#WEEK 7 

X = Combined_input_data7
y = Combined_output_data7

print("Dataset shape:", X.shape)

HIDDEN_LAYERS = (32, 16)   # moderate model for 5D
ALPHA = 1e-3               # regularisation
LOCAL_RADIUS = 0.04
N_LOCAL = 5500
N_GLOBAL = 5500
MIN_SEP = 0.01
EXPLORE_BONUS = 0.10
SEED = 321
MAX_ITER = 4000

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)


model = MLPRegressor(
    hidden_layer_sizes=HIDDEN_LAYERS,
    activation="relu",
    solver="adam",
    alpha=ALPHA,
    max_iter=MAX_ITER,
    random_state=SEED
)

model.fit(X_scaled, y)

best_idx = np.argmax(y)
best_x = X[best_idx]
best_y = y[best_idx]

print("Best value so far:", best_y)
print("Best point so far:", best_x)


rng = np.random.default_rng(SEED)

lower = X.min(axis=0)
upper = X.max(axis=0)

# Local refinement around best point
local_candidates = rng.normal(loc=best_x, scale=LOCAL_RADIUS, size=(N_LOCAL, 5))
local_candidates = np.clip(local_candidates, lower, upper)

# Global exploration
global_candidates = rng.uniform(lower, upper, size=(N_GLOBAL, 5))

# Combine candidates
candidates = np.vstack([local_candidates, global_candidates])

dist_to_existing = np.sqrt(((candidates[:, None, :] - X[None, :, :]) ** 2).sum(axis=2))
min_dist_existing = dist_to_existing.min(axis=1)

mask = min_dist_existing > MIN_SEP
candidates = candidates[mask]
min_dist_existing = min_dist_existing[mask]

print("Candidates after filtering:", candidates.shape[0])


candidates_scaled = scaler.transform(candidates)
predictions = model.predict(candidates_scaled)

explore_score = min_dist_existing / (min_dist_existing.max() + 1e-12)
score = predictions + EXPLORE_BONUS * explore_score


next_query = candidates[np.argmax(score)]


query_string = "-".join([f"{v:0.6f}" for v in next_query])

print("Next query:")
print(query_string)

Dataset shape: (26, 5)
Best value so far: -0.5337419878421241
Best point so far: [0.686137 0.210601 0.685594 0.646791 0.108468]
Candidates after filtering: 11000
Next query:
0.555153-0.287285-0.509316-0.770948-0.190263


In [3]:
#WEEK 8

new_data_point = np.array([[0.555153, 0.287285, 0.509316, 0.770948, 0.190263]])
Combined_input_data8 = np.concatenate((Combined_input_data7, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_6/W8_inputs.npy", Combined_input_data8)
print(Combined_input_data8)

new_output_data_point = np.array([-0.41253432385368105])
Combined_output_data8 = np.concatenate((Combined_output_data7, new_output_data_point), axis=0)
Combined_output_data8 = np.concatenate((Combined_output_data7, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_6/W8_outputs.npy", Combined_output_data8)

print(Combined_output_data8)

[[0.7281861  0.15469257 0.73255167 0.69399651 0.05640131]
 [0.24238435 0.84409997 0.5778091  0.67902128 0.50195289]
 [0.72952261 0.7481062  0.67977464 0.35655228 0.67105368]
 [0.77062024 0.11440374 0.04677993 0.64832428 0.27354905]
 [0.6188123  0.33180214 0.18728787 0.75623847 0.3288348 ]
 [0.78495809 0.91068235 0.7081201  0.95922543 0.0049115 ]
 [0.14511079 0.8966846  0.89632223 0.72627154 0.23627199]
 [0.94506907 0.28845905 0.97880576 0.96165559 0.59801594]
 [0.12572016 0.86272469 0.02854433 0.24660527 0.75120624]
 [0.75759436 0.35583141 0.0165229  0.4342072  0.11243304]
 [0.5367969  0.30878091 0.41187929 0.38822518 0.5225283 ]
 [0.95773967 0.23566857 0.09914585 0.15680593 0.07131737]
 [0.6293079  0.80348368 0.81140844 0.04561319 0.11062446]
 [0.02173531 0.42808424 0.83593944 0.48948866 0.51108173]
 [0.43934426 0.69892383 0.42682022 0.10947609 0.87788847]
 [0.25890557 0.79367771 0.6421139  0.19667346 0.59310318]
 [0.43216593 0.71561781 0.3418191  0.70499988 0.61496184]
 [0.78287982 0

In [ ]:
#WEEK 8

X = Combined_input_data8
y = Combined_output_data8

print("Dataset shape:", X.shape)


# balanced / medium-temperature search
HIDDEN_LAYERS = (32, 16)
ALPHA = 1e-3
LOCAL_RADIUS = 0.038

# candidate budget
N_LOCAL_BEST = 3500
N_LOCAL_TOP = 3500
N_GLOBAL = 5000

# attention + shortlist settings
TOP_QUANTILE = 0.80   # top 20% attention set
TOP_K = 35
EXPLORE_BONUS = 0.11

# near-duplicate protection
MIN_SEP = 0.01

SEED = 456
MAX_ITER = 4000

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

model = MLPRegressor(
    hidden_layer_sizes=HIDDEN_LAYERS,
    activation="relu",
    solver="adam",
    alpha=ALPHA,
    max_iter=MAX_ITER,
    random_state=SEED
)

model.fit(X_scaled, y)

best_idx = np.argmax(y)
best_x = X[best_idx]
best_y = y[best_idx]

threshold = np.quantile(y, TOP_QUANTILE)
top_points = X[y >= threshold]

print("Best value so far:", best_y)
print("Best point so far:", best_x)
print("Top attention points:", len(top_points))

if len(top_points) == 0:
    top_points = X[best_idx:best_idx + 1]


rng = np.random.default_rng(SEED)

lower = X.min(axis=0)
upper = X.max(axis=0)

# local candidates around current best
local_best = rng.normal(loc=best_x, scale=LOCAL_RADIUS, size=(N_LOCAL_BEST, 5))

# local candidates around top-performing region
local_top = []
n_per_top = max(100, N_LOCAL_TOP // len(top_points))
for pt in top_points:
    local = rng.normal(loc=pt, scale=LOCAL_RADIUS * 1.1, size=(n_per_top, 5))
    local_top.append(local)
local_top = np.vstack(local_top)

# global exploration
global_candidates = rng.uniform(lower, upper, size=(N_GLOBAL, 5))

# combine and clip
candidates = np.vstack([local_best, local_top, global_candidates])
candidates = np.clip(candidates, lower, upper)

dist_to_existing = np.sqrt(((candidates[:, None, :] - X[None, :, :]) ** 2).sum(axis=2))
min_dist_existing = dist_to_existing.min(axis=1)

mask = min_dist_existing > MIN_SEP
candidates = candidates[mask]
min_dist_existing = min_dist_existing[mask]

print("Candidates after filtering:", candidates.shape[0])


candidates_scaled = scaler.transform(candidates)
predictions = model.predict(candidates_scaled)

explore_score = min_dist_existing / (min_dist_existing.max() + 1e-12)

# balanced score: prediction + novelty
score = predictions + EXPLORE_BONUS * explore_score

top_k_idx = np.argsort(score)[-TOP_K:]
shortlist = candidates[top_k_idx]
shortlist_score = score[top_k_idx]
shortlist_explore = explore_score[top_k_idx]

# slight novelty preference within the shortlist
final_score = shortlist_score + 0.05 * shortlist_explore
next_query = shortlist[np.argmax(final_score)]

query_string = "-".join([f"{v:0.6f}" for v in next_query])

print("Next query:")
print(query_string)

Dataset shape: (27, 5)
Best value so far: -0.41253432385368105
Best point so far: [0.555153 0.287285 0.509316 0.770948 0.190263]
Top attention points: 7
Candidates after filtering: 12000
Next query:
0.642501-0.325664-0.500943-0.794295-0.043482


In [5]:
#WEEK 9

new_data_point = np.array([[0.642501, 0.325664, 0.500943, 0.794295, 0.043482]])
Combined_input_data9 = np.concatenate((Combined_input_data8, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_6/W9_inputs.npy", Combined_input_data9)
print(Combined_input_data9)

new_output_data_point = np.array([-0.44323492363684747])
Combined_output_data9 = np.concatenate((Combined_output_data8, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_6/W9_outputs.npy", Combined_output_data9)

print(Combined_output_data9)

[[0.7281861  0.15469257 0.73255167 0.69399651 0.05640131]
 [0.24238435 0.84409997 0.5778091  0.67902128 0.50195289]
 [0.72952261 0.7481062  0.67977464 0.35655228 0.67105368]
 [0.77062024 0.11440374 0.04677993 0.64832428 0.27354905]
 [0.6188123  0.33180214 0.18728787 0.75623847 0.3288348 ]
 [0.78495809 0.91068235 0.7081201  0.95922543 0.0049115 ]
 [0.14511079 0.8966846  0.89632223 0.72627154 0.23627199]
 [0.94506907 0.28845905 0.97880576 0.96165559 0.59801594]
 [0.12572016 0.86272469 0.02854433 0.24660527 0.75120624]
 [0.75759436 0.35583141 0.0165229  0.4342072  0.11243304]
 [0.5367969  0.30878091 0.41187929 0.38822518 0.5225283 ]
 [0.95773967 0.23566857 0.09914585 0.15680593 0.07131737]
 [0.6293079  0.80348368 0.81140844 0.04561319 0.11062446]
 [0.02173531 0.42808424 0.83593944 0.48948866 0.51108173]
 [0.43934426 0.69892383 0.42682022 0.10947609 0.87788847]
 [0.25890557 0.79367771 0.6421139  0.19667346 0.59310318]
 [0.43216593 0.71561781 0.3418191  0.70499988 0.61496184]
 [0.78287982 0

In [ ]:
# WEEK 9 
X = Combined_input_data9
y = Combined_output_data9

print("Dataset shape:", X.shape)

# Moderate trust in the surrogate
HIDDEN_LAYERS = (32, 16)
ALPHA = 1e-3
LOCAL_RADIUS = 0.032

# Candidate budget
N_LOCAL_BEST = 4200
N_LOCAL_TOP = 3000
N_GLOBAL = 3000

# Strong region, but not too narrow
TOP_QUANTILE = 0.82   # top 18%
TOP_K = 25
EXPLORE_BONUS = 0.09

# Duplicate protection
MIN_SEP = 0.01

SEED = 789
MAX_ITER = 4500

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

model = MLPRegressor(
    hidden_layer_sizes=HIDDEN_LAYERS,
    activation="relu",
    solver="adam",
    alpha=ALPHA,
    max_iter=MAX_ITER,
    random_state=SEED
)

model.fit(X_scaled, y)

best_idx = np.argmax(y)
best_x = X[best_idx]
best_y = y[best_idx]

threshold = np.quantile(y, TOP_QUANTILE)
top_points = X[y >= threshold]

print("Best value so far:", best_y)
print("Best point so far:", best_x)
print("Top attention points:", len(top_points))

if len(top_points) == 0:
    top_points = X[best_idx:best_idx + 1]

rng = np.random.default_rng(SEED)

lower = X.min(axis=0)
upper = X.max(axis=0)

# Local refinement around best point
local_best = rng.normal(loc=best_x, scale=LOCAL_RADIUS, size=(N_LOCAL_BEST, 5))

# Local refinement around other strong points
local_top = []
n_per_top = max(80, N_LOCAL_TOP // len(top_points))
for pt in top_points:
    local = rng.normal(loc=pt, scale=LOCAL_RADIUS * 1.08, size=(n_per_top, 5))
    local_top.append(local)
local_top = np.vstack(local_top)

# Global exploration
global_candidates = rng.uniform(lower, upper, size=(N_GLOBAL, 5))

# Combine and clip
candidates = np.vstack([local_best, local_top, global_candidates])
candidates = np.clip(candidates, lower, upper)

dist_to_existing = np.sqrt(((candidates[:, None, :] - X[None, :, :]) ** 2).sum(axis=2))
min_dist_existing = dist_to_existing.min(axis=1)

mask = min_dist_existing > MIN_SEP
candidates = candidates[mask]
min_dist_existing = min_dist_existing[mask]

print("Candidates after filtering:", candidates.shape[0])

candidates_scaled = scaler.transform(candidates)
predictions = model.predict(candidates_scaled)

explore_score = min_dist_existing / (min_dist_existing.max() + 1e-12)

# Surrogate-led score with moderate novelty protection
score = predictions + EXPLORE_BONUS * explore_score

top_k_idx = np.argsort(score)[-TOP_K:]
shortlist = candidates[top_k_idx]
shortlist_score = score[top_k_idx]
shortlist_explore = explore_score[top_k_idx]

# Small novelty preference inside the shortlist
final_score = shortlist_score + 0.04 * shortlist_explore
next_query = shortlist[np.argmax(final_score)]

query_string = "-".join([f"{v:0.6f}" for v in next_query])

print("Next query:")
print(query_string)

Dataset shape: (28, 5)
Best value so far: -0.41253432385368105
Best point so far: [0.555153 0.287285 0.509316 0.770948 0.190263]
Top attention points: 5
Candidates after filtering: 10200
Next query:
0.617851-0.374756-0.693736-0.708191-0.079015


In [7]:
#WEEK 10

new_data_point = np.array([[0.617851, 0.374756, 0.693736, 0.708191, 0.079015]])
Combined_input_data10 = np.concatenate((Combined_input_data9, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_6/W10_inputs.npy", Combined_input_data10)
print(Combined_input_data10)

new_output_data_point = np.array([-0.35586135440286115])
Combined_output_data10 = np.concatenate((Combined_output_data9, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_6/W10_outputs.npy", Combined_output_data10)

print(Combined_output_data10)

[[0.7281861  0.15469257 0.73255167 0.69399651 0.05640131]
 [0.24238435 0.84409997 0.5778091  0.67902128 0.50195289]
 [0.72952261 0.7481062  0.67977464 0.35655228 0.67105368]
 [0.77062024 0.11440374 0.04677993 0.64832428 0.27354905]
 [0.6188123  0.33180214 0.18728787 0.75623847 0.3288348 ]
 [0.78495809 0.91068235 0.7081201  0.95922543 0.0049115 ]
 [0.14511079 0.8966846  0.89632223 0.72627154 0.23627199]
 [0.94506907 0.28845905 0.97880576 0.96165559 0.59801594]
 [0.12572016 0.86272469 0.02854433 0.24660527 0.75120624]
 [0.75759436 0.35583141 0.0165229  0.4342072  0.11243304]
 [0.5367969  0.30878091 0.41187929 0.38822518 0.5225283 ]
 [0.95773967 0.23566857 0.09914585 0.15680593 0.07131737]
 [0.6293079  0.80348368 0.81140844 0.04561319 0.11062446]
 [0.02173531 0.42808424 0.83593944 0.48948866 0.51108173]
 [0.43934426 0.69892383 0.42682022 0.10947609 0.87788847]
 [0.25890557 0.79367771 0.6421139  0.19667346 0.59310318]
 [0.43216593 0.71561781 0.3418191  0.70499988 0.61496184]
 [0.78287982 0

In [ ]:
#WEEK 10
from sklearn.pipeline import make_pipeline
from sklearn.linear_model import Ridge

X = Combined_input_data10
y = Combined_output_data10

model = make_pipeline(StandardScaler(), Ridge(alpha=1.5))
model.fit(X, y)

best_x = X[np.argmax(y)]
lower = X.min(axis=0)
upper = X.max(axis=0)

ridge = model.named_steps["ridge"]
coefs = ridge.coef_

# move more on influential dimensions, less on weak ones
importance = np.abs(coefs)
importance = importance / (importance.max() + 1e-12)

step = 0.025
direction = np.sign(coefs) * importance
next_query = best_x + step * direction
next_query = np.clip(next_query, lower, upper)

query_string = "-".join([f"{v:0.6f}" for v in next_query])
print(query_string)
print("Feature coefficients:", coefs)

0.607930-0.364793-0.697220-0.725661-0.054015
Feature coefficients: [-0.11966632 -0.12016652  0.04201647  0.21071846 -0.30153543]


In [9]:
#WEEK 11

new_data_point = np.array([[0.607930, 0.364793, 0.697220, 0.725661, 0.054015]])
Combined_input_data11 = np.concatenate((Combined_input_data10, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_6/W11_inputs.npy", Combined_input_data11)
print(Combined_input_data11)

new_output_data_point = np.array([-0.3264239130136448])
Combined_output_data11 = np.concatenate((Combined_output_data10, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_6/W11_outputs.npy", Combined_output_data11)

print(Combined_output_data11)

[[0.7281861  0.15469257 0.73255167 0.69399651 0.05640131]
 [0.24238435 0.84409997 0.5778091  0.67902128 0.50195289]
 [0.72952261 0.7481062  0.67977464 0.35655228 0.67105368]
 [0.77062024 0.11440374 0.04677993 0.64832428 0.27354905]
 [0.6188123  0.33180214 0.18728787 0.75623847 0.3288348 ]
 [0.78495809 0.91068235 0.7081201  0.95922543 0.0049115 ]
 [0.14511079 0.8966846  0.89632223 0.72627154 0.23627199]
 [0.94506907 0.28845905 0.97880576 0.96165559 0.59801594]
 [0.12572016 0.86272469 0.02854433 0.24660527 0.75120624]
 [0.75759436 0.35583141 0.0165229  0.4342072  0.11243304]
 [0.5367969  0.30878091 0.41187929 0.38822518 0.5225283 ]
 [0.95773967 0.23566857 0.09914585 0.15680593 0.07131737]
 [0.6293079  0.80348368 0.81140844 0.04561319 0.11062446]
 [0.02173531 0.42808424 0.83593944 0.48948866 0.51108173]
 [0.43934426 0.69892383 0.42682022 0.10947609 0.87788847]
 [0.25890557 0.79367771 0.6421139  0.19667346 0.59310318]
 [0.43216593 0.71561781 0.3418191  0.70499988 0.61496184]
 [0.78287982 0

In [ ]:
#WEEK 11
from sklearn.cluster import KMeans

X = Combined_input_data11
y = Combined_output_data11

threshold = np.quantile(y, 0.75)
top_X = X[y >= threshold]
top_y = y[y >= threshold]

k = min(3, len(top_X))
kmeans = KMeans(n_clusters=k, random_state=16, n_init=10)
labels = kmeans.fit_predict(top_X)

centroids = []
scores = []

for c in range(k):
    cluster_points = top_X[labels == c]
    cluster_y = top_y[labels == c]
    centroids.append(cluster_points.mean(axis=0))
    scores.append(cluster_y.mean())

centroids = np.array(centroids)
scores = np.array(scores)
order = np.argsort(scores)[::-1]

# If top two clusters are far apart, test midpoint
if k >= 2:
    dist = np.linalg.norm(centroids[order[0]] - centroids[order[1]])
    if dist > 0.25 * np.sqrt(X.shape[1]):
        next_query = 0.5 * (centroids[order[0]] + centroids[order[1]])
    else:
        next_query = centroids[order[0]]
else:
    next_query = centroids[order[0]]

next_query = np.clip(next_query, X.min(axis=0), X.max(axis=0))
print("-".join([f"{v:0.6f}" for v in next_query]))

0.605859-0.338124-0.600304-0.749774-0.091694


In [11]:
#WEEK 12

new_data_point = np.array([[0.605859, 0.338124, 0.600304, 0.749774, 0.091694]])
Combined_input_data12 = np.concatenate((Combined_input_data11, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_6/W12_inputs.npy", Combined_input_data12)
print(Combined_input_data12)

new_output_data_point = np.array([-0.29467483454780347])
Combined_output_data12 = np.concatenate((Combined_output_data11, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_6/W12_outputs.npy", Combined_output_data12)

print(Combined_output_data12)

[[0.7281861  0.15469257 0.73255167 0.69399651 0.05640131]
 [0.24238435 0.84409997 0.5778091  0.67902128 0.50195289]
 [0.72952261 0.7481062  0.67977464 0.35655228 0.67105368]
 [0.77062024 0.11440374 0.04677993 0.64832428 0.27354905]
 [0.6188123  0.33180214 0.18728787 0.75623847 0.3288348 ]
 [0.78495809 0.91068235 0.7081201  0.95922543 0.0049115 ]
 [0.14511079 0.8966846  0.89632223 0.72627154 0.23627199]
 [0.94506907 0.28845905 0.97880576 0.96165559 0.59801594]
 [0.12572016 0.86272469 0.02854433 0.24660527 0.75120624]
 [0.75759436 0.35583141 0.0165229  0.4342072  0.11243304]
 [0.5367969  0.30878091 0.41187929 0.38822518 0.5225283 ]
 [0.95773967 0.23566857 0.09914585 0.15680593 0.07131737]
 [0.6293079  0.80348368 0.81140844 0.04561319 0.11062446]
 [0.02173531 0.42808424 0.83593944 0.48948866 0.51108173]
 [0.43934426 0.69892383 0.42682022 0.10947609 0.87788847]
 [0.25890557 0.79367771 0.6421139  0.19667346 0.59310318]
 [0.43216593 0.71561781 0.3418191  0.70499988 0.61496184]
 [0.78287982 0

In [ ]:
#WEEK 12
from sklearn.decomposition import PCA

X = Combined_input_data12
y = Combined_output_data12

threshold = np.quantile(y, 0.80)
top_X = X[y >= threshold]

best_x = X[np.argmax(y)]
lower = X.min(axis=0)
upper = X.max(axis=0)

pca = PCA(n_components=2)
pca.fit(top_X)
pc1, pc2 = pca.components_

model = make_pipeline(StandardScaler(), Ridge(alpha=1.5))
model.fit(X, y)

rng = np.random.default_rng(126)
n_candidates = 7000

a = rng.normal(0, 0.025, size=(n_candidates, 1))
b = rng.normal(0, 0.015, size=(n_candidates, 1))
noise = rng.normal(0, 0.008, size=(n_candidates, 5))

candidates = best_x + a * pc1 + b * pc2 + noise
candidates = np.clip(candidates, lower, upper)

pred = model.predict(candidates)
dist = np.sqrt(((candidates[:, None, :] - X[None, :, :])**2).sum(axis=2))
min_dist = dist.min(axis=1)

score = pred + 0.08 * (min_dist / (min_dist.max() + 1e-12))
next_query = candidates[np.argmax(score)]

print("-".join([f"{v:0.6f}" for v in next_query]))

0.581382-0.363119-0.532842-0.814967-0.091303


In [13]:
#WEEK 13

new_data_point = np.array([[0.581382, 0.363119, 0.532842, 0.814967, 0.091303]])
Combined_input_data13 = np.concatenate((Combined_input_data12, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_6/W13_inputs.npy", Combined_input_data13)
print(Combined_input_data13)

new_output_data_point = np.array([-0.3353367107194658])
Combined_output_data13 = np.concatenate((Combined_output_data12, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_6/W13_outputs.npy", Combined_output_data13)

print(Combined_output_data13)

[[0.7281861  0.15469257 0.73255167 0.69399651 0.05640131]
 [0.24238435 0.84409997 0.5778091  0.67902128 0.50195289]
 [0.72952261 0.7481062  0.67977464 0.35655228 0.67105368]
 [0.77062024 0.11440374 0.04677993 0.64832428 0.27354905]
 [0.6188123  0.33180214 0.18728787 0.75623847 0.3288348 ]
 [0.78495809 0.91068235 0.7081201  0.95922543 0.0049115 ]
 [0.14511079 0.8966846  0.89632223 0.72627154 0.23627199]
 [0.94506907 0.28845905 0.97880576 0.96165559 0.59801594]
 [0.12572016 0.86272469 0.02854433 0.24660527 0.75120624]
 [0.75759436 0.35583141 0.0165229  0.4342072  0.11243304]
 [0.5367969  0.30878091 0.41187929 0.38822518 0.5225283 ]
 [0.95773967 0.23566857 0.09914585 0.15680593 0.07131737]
 [0.6293079  0.80348368 0.81140844 0.04561319 0.11062446]
 [0.02173531 0.42808424 0.83593944 0.48948866 0.51108173]
 [0.43934426 0.69892383 0.42682022 0.10947609 0.87788847]
 [0.25890557 0.79367771 0.6421139  0.19667346 0.59310318]
 [0.43216593 0.71561781 0.3418191  0.70499988 0.61496184]
 [0.78287982 0

In [ ]:
#WEEK 13
X = Combined_input_data13
y = Combined_output_data13

best_x = X[np.argmax(y)]
lower = X.min(axis=0)
upper = X.max(axis=0)

model = make_pipeline(StandardScaler(), Ridge(alpha=1.5))
model.fit(X, y)

rng = np.random.default_rng(106)

# Mostly local, some broader search
local_candidates = rng.normal(loc=best_x, scale=0.025, size=(4500, 5))
global_candidates = rng.uniform(lower, upper, size=(2500, 5))

candidates = np.vstack([local_candidates, global_candidates])
candidates = np.clip(candidates, lower, upper)

pred = model.predict(candidates)
dist = np.sqrt(((candidates[:, None, :] - X[None, :, :])**2).sum(axis=2))
min_dist = dist.min(axis=1)

# low-epsilon policy: mostly exploit, slightly explore
score = pred + 0.06 * (min_dist / (min_dist.max() + 1e-12))
next_query = candidates[np.argmax(score)]

print("-".join([f"{v:0.6f}" for v in next_query]))

0.130454-0.284784-0.879997-0.914487-0.016090
