In [2]:
#Load packages required for loading the npy files.
import numpy as np
import pandas as pd

# #Load the npy file called "data.npy"
Initial_input_data = np.load("/Users/mayukotakamiya/MachineLearning/initial_data/function_1/initial_inputs.npy")
Initial_output_data = np.load("/Users/mayukotakamiya/MachineLearning/initial_data/function_1/initial_outputs.npy")

#I want to know dimentionality of the initial_input_data  
Initial_input_data.shape




(10, 2)

In [84]:

# X and y already loaded
X = Initial_input_data
y = Initial_output_data

def propose_next_point(X, y, n_candidates=8000, w_exploit=0.6, w_explore=0.4, seed=42):
    """
    Simple explore/exploit heuristic:
    - exploit: sample near best observed point
    - explore: sample far from existing samples
    """

    rng = np.random.default_rng(seed)
    n, d = X.shape

    # Best observed point so far
    best_x = X[np.argmax(y)]

    # Determine sampling bounds from existing data
    lower_bounds = X.min(axis=0)
    upper_bounds = X.max(axis=0)

    # Generate random candidate points within observed bounds
    C = rng.uniform(lower_bounds, upper_bounds, size=(n_candidates, d))

    # Exploitation term (closer to best is better)
    dist_to_best = np.linalg.norm(C - best_x, axis=1)
    exploit = 1 - (dist_to_best / (dist_to_best.max() + 1e-12))

    # Exploration term (farther from existing points is better)
    dists = np.sqrt(((C[:, None, :] - X[None, :, :]) ** 2).sum(axis=2))
    min_dist = dists.min(axis=1)
    explore = min_dist / (min_dist.max() + 1e-12)

    # Combined score
    score = w_exploit * exploit + w_explore * explore

    return C[np.argmax(score)]

def format_query(x):
    return "-".join([f"{v:0.6f}" for v in x])

# Generate next query
next_x = propose_next_point(X, y)

print("Submit this to the portal:")
print(format_query(next_x))

Submit this to the portal:
0.433534-0.458467


In [3]:
###WEEK 2
#I want to see the data in /Users/mayukotakamiya/MachineLearning/initial_data/function_1/initial_inputs.npy
print(Initial_input_data)
#I WANT TO create a new npy file by adding a new data point which is [0.433534 0.458467]
new_data_point = np.array([[0.433534, 0.458467]])
Combined_input_data = np.concatenate((Initial_input_data, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_1/W2_inputs.npy", Combined_input_data)
print(Combined_input_data)

[[0.31940389 0.76295937]
 [0.57432921 0.8798981 ]
 [0.73102363 0.73299988]
 [0.84035342 0.26473161]
 [0.65011406 0.68152635]
 [0.41043714 0.1475543 ]
 [0.31269116 0.07872278]
 [0.68341817 0.86105746]
 [0.08250725 0.40348751]
 [0.88388983 0.58225397]]
[[0.31940389 0.76295937]
 [0.57432921 0.8798981 ]
 [0.73102363 0.73299988]
 [0.84035342 0.26473161]
 [0.65011406 0.68152635]
 [0.41043714 0.1475543 ]
 [0.31269116 0.07872278]
 [0.68341817 0.86105746]
 [0.08250725 0.40348751]
 [0.88388983 0.58225397]
 [0.433534   0.458467  ]]


In [4]:
print(Initial_output_data)

#I want to create a new npy file bt adding a new data point to the Initial_output_data
new_output_data_point = np.array([0.007087524491952269])
Combined_output_data = np.concatenate((Initial_output_data, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_1/W2_outputs.npy", Combined_output_data)

print(Combined_output_data)

[ 1.32267704e-079  1.03307824e-046  7.71087511e-016  3.34177101e-124
 -3.60606264e-003 -2.15924904e-054 -2.08909327e-091  2.53500115e-040
  3.60677119e-081  6.22985647e-048]
[ 1.32267704e-079  1.03307824e-046  7.71087511e-016  3.34177101e-124
 -3.60606264e-003 -2.15924904e-054 -2.08909327e-091  2.53500115e-040
  3.60677119e-081  6.22985647e-048  7.08752449e-003]


In [87]:
#Assess the exploitation vs exploration strategy
x=Combined_input_data
y=Combined_output_data

best_score_w2= np.max(y)
improvement= best_score_w2 - np.max(Initial_output_data)

print("Improvement:", improvement)
print("Output range:", y.min(), "to", y.max())
print("Std deviation:", np.std(y))


Improvement: 0.007087524491951498
Output range: -0.0036060626443634764 to 0.007087524491952269
Std deviation: 0.002376682573738607


In [ ]:
##Function1- For week2, it seems there is a big improvement by having the improvement more than 10% of the output range. Therefore, more exploitation than exploration.
##Function2- For week2, no improvement at all. Therefore use more exploration than exploitation
##Function3- for week2, no improvement at all.Therefore use more exploration than exploitation. 
##Function4- for week2, no improvement at all.Therefore use more exploration than exploitation. 
##Function5- for week2, no improvement at all.Therefore use more exploration than exploitation. 
##Function6- for week2, no improvement at all.Therefore use more exploration than exploitation. 
##Function7- for week2, no improvement at all.Therefore use more exploration than exploitation. 
#Function8- for week2, there is small-moderate improvement. Take a balanced approach (6:4)

In [88]:
#Re-run the loop
X=Combined_input_data
y=Combined_output_data

def propose_next_point(X, y, n_candidates=8000, w_exploit=0.75, w_explore=0.25, seed=234):
    """
    Simple explore/exploit heuristic:
    - exploit: sample near best observed point
    - explore: sample far from existing samples
    """

    rng = np.random.default_rng(seed)
    n, d = X.shape

    # Best observed point so far
    best_x = X[np.argmax(y)]
    
    radius = 0.05  # small local refinement

    # Determine sampling bounds from existing data
    lower = np.maximum(best_x - radius, X.min(axis=0))
    upper = np.minimum(best_x + radius, X.max(axis=0))


    # Generate random candidate points within observed bounds
    C = rng.uniform(lower, upper, size=(n_candidates, d))

    # Exploitation term (closer to best is better)
    dist_to_best = np.linalg.norm(C - best_x, axis=1)
    exploit = 1 - (dist_to_best / (dist_to_best.max() + 1e-12))

    # Exploration term (farther from existing points is better)
    dists = np.sqrt(((C[:, None, :] - X[None, :, :]) ** 2).sum(axis=2))
    min_dist = dists.min(axis=1)
    explore = min_dist / (min_dist.max() + 1e-12)

    # Combined score
    score = w_exploit * exploit + w_explore * explore

    return C[np.argmax(score)]

def format_query(x):
    return "-".join([f"{v:0.6f}" for v in x])

# Generate next query
next_x = propose_next_point(X, y)

print("Submit this to the portal:")
print(format_query(next_x))

Submit this to the portal:
0.433582-0.457940


In [5]:
####WEEK 3
new_data_point = np.array([[0.434285, 0.458885]])
Combined_input_data3 = np.concatenate((Combined_input_data, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_1/W3_inputs.npy", Combined_input_data3)
print(Combined_input_data3)

new_output_data_point = np.array([0.005251741633542124])
Combined_output_data3 = np.concatenate((Combined_output_data, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_1/W3_outputs.npy", Combined_output_data3)

print(Combined_output_data3)


[[0.31940389 0.76295937]
 [0.57432921 0.8798981 ]
 [0.73102363 0.73299988]
 [0.84035342 0.26473161]
 [0.65011406 0.68152635]
 [0.41043714 0.1475543 ]
 [0.31269116 0.07872278]
 [0.68341817 0.86105746]
 [0.08250725 0.40348751]
 [0.88388983 0.58225397]
 [0.433534   0.458467  ]
 [0.434285   0.458885  ]]
[ 1.32267704e-079  1.03307824e-046  7.71087511e-016  3.34177101e-124
 -3.60606264e-003 -2.15924904e-054 -2.08909327e-091  2.53500115e-040
  3.60677119e-081  6.22985647e-048  7.08752449e-003  5.25174163e-003]


In [6]:
#WEEK 3 Assess the exploitation vs exploration strategy
x=Combined_input_data3
y=Combined_output_data3

best_score_w2= np.max(y)
improvement= best_score_w2 - np.max(Combined_output_data)

print("Improvement:", improvement)
print("Output range:", y.min(), "to", y.max())
print("Std deviation:", np.std(y))

Improvement: 0.0
Output range: -0.0036060626443634764 to 0.007087524491952269
Std deviation: 0.002653013137364431


In [7]:
#WEEK 3 -re run the loop. No improvement so adjust exploit vs explore ratio to 0.45:0.55
X=Combined_input_data3
y=Combined_output_data3

def propose_next_point(X, y, n_candidates=8000, w_exploit=0.45, w_explore=0.55, seed=234):

    rng = np.random.default_rng(seed)
    n, d = X.shape

    # Best observed point so far
    best_x = X[np.argmax(y)]
    
    radius = 0.05  # small local refinement

    # Determine sampling bounds from existing data
    lower = np.maximum(best_x - radius, X.min(axis=0))
    upper = np.minimum(best_x + radius, X.max(axis=0))


    # Generate random candidate points within observed bounds
    C = rng.uniform(lower, upper, size=(n_candidates, d))

    # Exploitation term (closer to best is better)
    dist_to_best = np.linalg.norm(C - best_x, axis=1)
    exploit = 1 - (dist_to_best / (dist_to_best.max() + 1e-12))

    # Exploration term (farther from existing points is better)
    dists = np.sqrt(((C[:, None, :] - X[None, :, :]) ** 2).sum(axis=2))
    min_dist = dists.min(axis=1)
    explore = min_dist / (min_dist.max() + 1e-12)

    # Combined score
    score = w_exploit * exploit + w_explore * explore

    return C[np.argmax(score)]

def format_query(x):
    return "-".join([f"{v:0.6f}" for v in x])

# Generate next query
next_x = propose_next_point(X, y)

print("Submit this to the portal:")
print(format_query(next_x))

Submit this to the portal:
0.383616-0.409388


In [8]:
####WEEK 4
new_data_point = np.array([[0.383616, 0.409388]])
Combined_input_data4 = np.concatenate((Combined_input_data3, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_1/W4_inputs.npy", Combined_input_data4)
print(Combined_input_data4)

new_output_data_point = np.array([0.004042733938041736])
Combined_output_data4 = np.concatenate((Combined_output_data3, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_1/W4_outputs.npy", Combined_output_data4)

print(Combined_output_data4)

[[0.31940389 0.76295937]
 [0.57432921 0.8798981 ]
 [0.73102363 0.73299988]
 [0.84035342 0.26473161]
 [0.65011406 0.68152635]
 [0.41043714 0.1475543 ]
 [0.31269116 0.07872278]
 [0.68341817 0.86105746]
 [0.08250725 0.40348751]
 [0.88388983 0.58225397]
 [0.433534   0.458467  ]
 [0.434285   0.458885  ]
 [0.383616   0.409388  ]]
[ 1.32267704e-079  1.03307824e-046  7.71087511e-016  3.34177101e-124
 -3.60606264e-003 -2.15924904e-054 -2.08909327e-091  2.53500115e-040
  3.60677119e-081  6.22985647e-048  7.08752449e-003  5.25174163e-003
  4.04273394e-003]


In [9]:
#WEEK 4 Assess the exploitation vs exploration strategy
x=Combined_input_data4
y=Combined_output_data4

best_score_w2= np.max(y)
improvement= best_score_w2 - np.max(Combined_output_data3)

print("Improvement:", improvement)
print("Output range:", y.min(), "to", y.max())
print("Std deviation:", np.std(y))

Improvement: 0.0
Output range: -0.0036060626443634764 to 0.007087524491952269
Std deviation: 0.0026976548563347465


In [10]:
#WEEK 4 -re run the loop. No improvement so adjust exploit vs explore ratio to 0.45:0.55
X=Combined_input_data4
y=Combined_output_data4

def propose_next_point(X, y, n_candidates=8000, w_exploit=0.45, w_explore=0.55, seed=100):

    rng = np.random.default_rng(seed)
    n, d = X.shape

    # Best observed point so far
    best_x = X[np.argmax(y)]
    
    radius = 0.05  # small local refinement

    # Determine sampling bounds from existing data
    lower = np.maximum(best_x - radius, X.min(axis=0))
    upper = np.minimum(best_x + radius, X.max(axis=0))


    # Generate random candidate points within observed bounds
    C = rng.uniform(lower, upper, size=(n_candidates, d))

    # Exploitation term (closer to best is better)
    dist_to_best = np.linalg.norm(C - best_x, axis=1)
    exploit = 1 - (dist_to_best / (dist_to_best.max() + 1e-12))

    # Exploration term (farther from existing points is better)
    dists = np.sqrt(((C[:, None, :] - X[None, :, :]) ** 2).sum(axis=2))
    min_dist = dists.min(axis=1)
    explore = min_dist / (min_dist.max() + 1e-12)

    # Combined score
    score = w_exploit * exploit + w_explore * explore
    return C[np.argmax(score)]

def format_query(x):
    return "-".join([f"{v:0.6f}" for v in x])

# Generate next query
next_x = propose_next_point(X, y)

print("Submit this to the portal:")
print(format_query(next_x))

Submit this to the portal:
0.383914-0.507406


In [11]:
#WEEK 5 
new_data_point = np.array([[0.383914, 0.507406]])
Combined_input_data5 = np.concatenate((Combined_input_data4, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_1/W5_inputs.npy", Combined_input_data5)
print(Combined_input_data5)

new_output_data_point = np.array([-5.0871855063036176e-8])
Combined_output_data5 = np.concatenate((Combined_output_data4, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_1/W5_outputs.npy", Combined_output_data5)

print(Combined_output_data5)

[[0.31940389 0.76295937]
 [0.57432921 0.8798981 ]
 [0.73102363 0.73299988]
 [0.84035342 0.26473161]
 [0.65011406 0.68152635]
 [0.41043714 0.1475543 ]
 [0.31269116 0.07872278]
 [0.68341817 0.86105746]
 [0.08250725 0.40348751]
 [0.88388983 0.58225397]
 [0.433534   0.458467  ]
 [0.434285   0.458885  ]
 [0.383616   0.409388  ]
 [0.383914   0.507406  ]]
[ 1.32267704e-079  1.03307824e-046  7.71087511e-016  3.34177101e-124
 -3.60606264e-003 -2.15924904e-054 -2.08909327e-091  2.53500115e-040
  3.60677119e-081  6.22985647e-048  7.08752449e-003  5.25174163e-003
  4.04273394e-003 -5.08718551e-008]


In [ ]:
##Week 5 focuses on local search around the best point, keeps some exploration, avoids duplicate queries, adapts to your observed data

X = Combined_input_data5
y = Combined_output_data5

print("Dataset shape:", X.shape)

best_idx = np.argmax(y)
best_x = X[best_idx]

print("Best point so far:", best_x)
print("Best value:", y[best_idx])

rng = np.random.default_rng(42)

lower = X.min(axis=0)
upper = X.max(axis=0)

# --- Local candidates (exploitation) ---
local_candidates = rng.normal(loc=best_x, scale=0.05, size=(2000, 2))

# --- Global candidates (exploration) ---
global_candidates = rng.uniform(lower, upper, size=(2000, 2))

# Combine
candidates = np.vstack([local_candidates, global_candidates])

# Clip to bounds
candidates = np.clip(candidates, lower, upper)

dist = np.sqrt(((candidates[:, None, :] - X[None, :, :])**2).sum(axis=2))
min_dist = dist.min(axis=1)

mask = min_dist > 0.01
candidates = candidates[mask]

# Exploitation: distance to best point (closer is better)
dist_to_best = np.linalg.norm(candidates - best_x, axis=1)
exploit_score = 1 - dist_to_best / (dist_to_best.max() + 1e-12)

# Exploration: distance from existing points (farther is better)
explore_score = min_dist[mask]
explore_score = explore_score / (explore_score.max() + 1e-12)

# Balanced score (slightly exploration-focused since last improvement may have stalled)
score = 0.45 * exploit_score + 0.55 * explore_score

next_query = candidates[np.argmax(score)]

query_string = "-".join([f"{v:0.6f}" for v in next_query])

print("Next query:")
print(query_string)

Dataset shape: (14, 2)
Best point so far: [0.433534 0.458467]
Best value: 0.007087524491952269
Next query:
0.674312-0.431524


In [13]:
#WEEK 6
new_data_point = np.array([[0.674312, 0.431524]])
Combined_input_data6 = np.concatenate((Combined_input_data5, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_1/W6_inputs.npy", Combined_input_data6)
print(Combined_input_data6)

new_output_data_point = np.array([5.12277145464331e-31])
Combined_output_data6 = np.concatenate((Combined_output_data5, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_1/W6_outputs.npy", Combined_output_data6)

print(Combined_output_data6)

[[0.31940389 0.76295937]
 [0.57432921 0.8798981 ]
 [0.73102363 0.73299988]
 [0.84035342 0.26473161]
 [0.65011406 0.68152635]
 [0.41043714 0.1475543 ]
 [0.31269116 0.07872278]
 [0.68341817 0.86105746]
 [0.08250725 0.40348751]
 [0.88388983 0.58225397]
 [0.433534   0.458467  ]
 [0.434285   0.458885  ]
 [0.383616   0.409388  ]
 [0.383914   0.507406  ]
 [0.674312   0.431524  ]]
[ 1.32267704e-079  1.03307824e-046  7.71087511e-016  3.34177101e-124
 -3.60606264e-003 -2.15924904e-054 -2.08909327e-091  2.53500115e-040
  3.60677119e-081  6.22985647e-048  7.08752449e-003  5.25174163e-003
  4.04273394e-003 -5.08718551e-008  5.12277145e-031]


In [ ]:
##WEEK 6
#Focus near the current best point (refinement)
#Keep some exploration (avoid local trap)
#Reduce randomness compared to earlier rounds
#Avoid neural networks (unnecessary complexity)

X = Combined_input_data6
y = Combined_output_data6

print("Dataset shape:", X.shape)

best_idx = np.argmax(y)
best_x = X[best_idx]

print("Best value:", y[best_idx])
print("Best point:", best_x)

rng = np.random.default_rng(123)  # new seed to avoid duplicates

lower = X.min(axis=0)
upper = X.max(axis=0)

# Local refinement (main focus)
local_candidates = rng.normal(loc=best_x, scale=0.03, size=(3000, 2))
local_candidates = np.clip(local_candidates, lower, upper)

# Moderate global exploration
global_candidates = rng.uniform(lower, upper, size=(2000, 2))

# Combine candidates
candidates = np.vstack([local_candidates, global_candidates])

dist = np.sqrt(((candidates[:, None, :] - X[None, :, :])**2).sum(axis=2))
min_dist = dist.min(axis=1)

mask = min_dist > 0.01
candidates = candidates[mask]
min_dist = min_dist[mask]

# Exploitation: closeness to best point
dist_to_best = np.linalg.norm(candidates - best_x, axis=1)
exploit_score = 1 - dist_to_best / (dist_to_best.max() + 1e-12)

# Exploration: distance from known points
explore_score = min_dist / (min_dist.max() + 1e-12)

# Balanced but slightly exploit-focused (Query 6)
score = 0.6 * exploit_score + 0.4 * explore_score

next_query = candidates[np.argmax(score)]

query_string = "-".join([f"{v:0.6f}" for v in next_query])

print("Next query:")
print(query_string)

Dataset shape: (15, 2)
Best value: 0.007087524491952269
Best point: [0.433534 0.458467]
Next query:
0.538921-0.302247


In [3]:
#WEEK 7
import numpy as np
import pandas as pd
Combined_input_data6 = np.load("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_1/W6_inputs.npy")
Combined_output_data6 = np.load("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_1/W6_outputs.npy")

new_data_point = np.array([[0.538921, 0.302247]])
Combined_input_data7 = np.concatenate((Combined_input_data6, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_1/W7_inputs.npy", Combined_input_data7)
print(Combined_input_data7)

new_output_data_point = np.array([-2.69937093855915e-23])
Combined_output_data7 = np.concatenate((Combined_output_data6, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_1/W7_outputs.npy", Combined_output_data7)

print(Combined_output_data7)

[[0.66579958 0.12396913]
 [0.87779099 0.7786275 ]
 [0.14269907 0.34900513]
 [0.84527543 0.71112027]
 [0.45464714 0.29045518]
 [0.57771284 0.77197318]
 [0.43816606 0.68501826]
 [0.34174959 0.02869772]
 [0.33864816 0.21386725]
 [0.70263656 0.9265642 ]
 [0.14597    0.921486  ]
 [0.652719   0.877025  ]
 [0.751452   0.87691   ]
 [0.701759   0.877518  ]
 [0.701759   0.877518  ]
 [0.538921   0.302247  ]]
[ 5.38996119e-01  4.20586240e-01 -6.56236244e-02  2.93992912e-01
  2.14964510e-01  2.31055498e-02  2.44619344e-01  3.87490152e-02
 -1.38576181e-02  6.11205216e-01  5.12835000e-02  4.38220570e-01
  5.64844479e-01  5.43040584e-01  5.05430406e+01 -2.69937094e-23]


In [ ]:
#WEEK 7

X = Combined_input_data7
y = Combined_output_data7

print("Dataset shape:", X.shape)

EXPLOIT_WEIGHT = 0.65
EXPLORE_WEIGHT = 0.35
LOCAL_RADIUS = 0.025
N_LOCAL = 4000
N_GLOBAL = 1500
MIN_SEP = 0.01
SEED = 321

best_idx = np.argmax(y)
best_x = X[best_idx]
best_y = y[best_idx]

print("Best value so far:", best_y)
print("Best point so far:", best_x)

rng = np.random.default_rng(SEED)

lower = X.min(axis=0)
upper = X.max(axis=0)

# Local refinement around best point
local_candidates = rng.normal(loc=best_x, scale=LOCAL_RADIUS, size=(N_LOCAL, 2))
local_candidates = np.clip(local_candidates, lower, upper)

# Global exploration
global_candidates = rng.uniform(lower, upper, size=(N_GLOBAL, 2))

# Combine
candidates = np.vstack([local_candidates, global_candidates])

dist_to_existing = np.sqrt(((candidates[:, None, :] - X[None, :, :]) ** 2).sum(axis=2))
min_dist_existing = dist_to_existing.min(axis=1)

mask = min_dist_existing > MIN_SEP
candidates = candidates[mask]
min_dist_existing = min_dist_existing[mask]

print("Candidates after filtering:", candidates.shape[0])

# Exploitation: closer to best point is better
dist_to_best = np.linalg.norm(candidates - best_x, axis=1)
exploit_score = 1 - dist_to_best / (dist_to_best.max() + 1e-12)

# Exploration: farther from known points is better
explore_score = min_dist_existing / (min_dist_existing.max() + 1e-12)

# Combined score
score = EXPLOIT_WEIGHT * exploit_score + EXPLORE_WEIGHT * explore_score

next_query = candidates[np.argmax(score)]

query_string = "-".join([f"{v:0.6f}" for v in next_query])

print("Next query:")
print(query_string)

Dataset shape: (16, 2)
Best value so far: 50.543040584470276
Best point so far: [0.701759 0.877518]
Candidates after filtering: 5046
Next query:
0.700409-0.758584


In [5]:
#WEEK 8

new_data_point = np.array([[0.700409, 0.758584]])
Combined_input_data8 = np.concatenate((Combined_input_data7, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_1/W8_inputs.npy", Combined_input_data8)
print(Combined_input_data8)

new_output_data_point = np.array([-4.141057806672472e-16])
Combined_output_data8 = np.concatenate((Combined_output_data7, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_1/W8_outputs.npy", Combined_output_data8)

print(Combined_output_data8)

[[0.66579958 0.12396913]
 [0.87779099 0.7786275 ]
 [0.14269907 0.34900513]
 [0.84527543 0.71112027]
 [0.45464714 0.29045518]
 [0.57771284 0.77197318]
 [0.43816606 0.68501826]
 [0.34174959 0.02869772]
 [0.33864816 0.21386725]
 [0.70263656 0.9265642 ]
 [0.14597    0.921486  ]
 [0.652719   0.877025  ]
 [0.751452   0.87691   ]
 [0.701759   0.877518  ]
 [0.701759   0.877518  ]
 [0.538921   0.302247  ]
 [0.700409   0.758584  ]]
[ 5.38996119e-01  4.20586240e-01 -6.56236244e-02  2.93992912e-01
  2.14964510e-01  2.31055498e-02  2.44619344e-01  3.87490152e-02
 -1.38576181e-02  6.11205216e-01  5.12835000e-02  4.38220570e-01
  5.64844479e-01  5.43040584e-01  5.05430406e+01 -2.69937094e-23
 -4.14105781e-16]


In [ ]:
#WEEK 8 

X = Combined_input_data8
y = Combined_output_data8

print("Dataset shape:", X.shape)

# "Low temperature" -> more focused search
EXPLOIT_WEIGHT = 0.72
EXPLORE_WEIGHT = 0.28

# tighter local search radius
LOCAL_RADIUS = 0.020

# candidate budget
N_LOCAL = 5000
N_GLOBAL = 1200

# avoid near-duplicate queries
MIN_SEP = 0.01

# top-k style selection
TOP_K = 25

SEED = 456

best_idx = np.argmax(y)
best_x = X[best_idx]
best_y = y[best_idx]

# Use top 20% as "attention set"
threshold = np.quantile(y, 0.80)
top_points = X[y >= threshold]

print("Best value so far:", best_y)
print("Best point so far:", best_x)
print("Top attention points:", len(top_points))

# fallback if very few points qualify
if len(top_points) == 0:
    top_points = X[best_idx:best_idx+1]

rng = np.random.default_rng(SEED)

lower = X.min(axis=0)
upper = X.max(axis=0)

# local candidates around current best
local_best = rng.normal(loc=best_x, scale=LOCAL_RADIUS, size=(N_LOCAL // 2, 2))

# local candidates around top-performing region
local_top = []
for pt in top_points:
    local = rng.normal(loc=pt, scale=LOCAL_RADIUS * 1.2, size=(max(50, N_LOCAL // (2 * len(top_points))), 2))
    local_top.append(local)
local_top = np.vstack(local_top)

# global exploration candidates
global_candidates = rng.uniform(lower, upper, size=(N_GLOBAL, 2))

# combine and clip to observed bounds
candidates = np.vstack([local_best, local_top, global_candidates])
candidates = np.clip(candidates, lower, upper)

dist_to_existing = np.sqrt(((candidates[:, None, :] - X[None, :, :]) ** 2).sum(axis=2))
min_dist_existing = dist_to_existing.min(axis=1)

mask = min_dist_existing > MIN_SEP
candidates = candidates[mask]
min_dist_existing = min_dist_existing[mask]

print("Candidates after filtering:", candidates.shape[0])

# Exploitation: closeness to best point
dist_to_best = np.linalg.norm(candidates - best_x, axis=1)
exploit_score = 1 - dist_to_best / (dist_to_best.max() + 1e-12)

# Exploration: distance from known points
explore_score = min_dist_existing / (min_dist_existing.max() + 1e-12)

# Combined score
score = EXPLOIT_WEIGHT * exploit_score + EXPLORE_WEIGHT * explore_score

top_k_idx = np.argsort(score)[-TOP_K:]
top_k_candidates = candidates[top_k_idx]
top_k_scores = score[top_k_idx]
top_k_explore = explore_score[top_k_idx]

# choose the candidate with the best blend of score + novelty
final_score = top_k_scores + 0.05 * top_k_explore
next_query = top_k_candidates[np.argmax(final_score)]

query_string = "-".join([f"{v:0.6f}" for v in next_query])

print("Next query:")
print(query_string)

Dataset shape: (17, 2)
Best value so far: 50.543040584470276
Best point so far: [0.701759 0.877518]
Top attention points: 4
Candidates after filtering: 5491
Next query:
0.680043-0.819023


In [8]:
#WEEK 9

new_data_point = np.array([[0.680043, 0.819023]])
Combined_input_data9 = np.concatenate((Combined_input_data8, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_1/W9_inputs.npy", Combined_input_data9)
print(Combined_input_data9)

new_output_data_point = np.array([-1.9222048797672574e-28])
Combined_output_data9 = np.concatenate((Combined_output_data8, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_1/W9_outputs.npy", Combined_output_data9)

print(Combined_output_data9)

[[0.66579958 0.12396913]
 [0.87779099 0.7786275 ]
 [0.14269907 0.34900513]
 [0.84527543 0.71112027]
 [0.45464714 0.29045518]
 [0.57771284 0.77197318]
 [0.43816606 0.68501826]
 [0.34174959 0.02869772]
 [0.33864816 0.21386725]
 [0.70263656 0.9265642 ]
 [0.14597    0.921486  ]
 [0.652719   0.877025  ]
 [0.751452   0.87691   ]
 [0.701759   0.877518  ]
 [0.701759   0.877518  ]
 [0.538921   0.302247  ]
 [0.700409   0.758584  ]
 [0.680043   0.819023  ]]
[ 5.38996119e-01  4.20586240e-01 -6.56236244e-02  2.93992912e-01
  2.14964510e-01  2.31055498e-02  2.44619344e-01  3.87490152e-02
 -1.38576181e-02  6.11205216e-01  5.12835000e-02  4.38220570e-01
  5.64844479e-01  5.43040584e-01  5.05430406e+01 -2.69937094e-23
 -4.14105781e-16 -1.92220488e-28]


In [ ]:
#WEEK 9 

X = Combined_input_data9
y = Combined_output_data9

print("Dataset shape:", X.shape)

# Strong exploitation: enough data should now reveal the best region
EXPLOIT_WEIGHT = 0.80
EXPLORE_WEIGHT = 0.20

# Tight local search radius
LOCAL_RADIUS = 0.015

# Candidate budget
N_LOCAL_BEST = 5000
N_LOCAL_TOP = 2000
N_GLOBAL = 800

# Focus on strongest region
TOP_QUANTILE = 0.85   # top 15%
TOP_K = 15

# Avoid duplicate queries
MIN_SEP = 0.01

SEED = 789

best_idx = np.argmax(y)
best_x = X[best_idx]
best_y = y[best_idx]

threshold = np.quantile(y, TOP_QUANTILE)
top_points = X[y >= threshold]

print("Best value so far:", best_y)
print("Best point so far:", best_x)
print("Top attention points:", len(top_points))

if len(top_points) == 0:
    top_points = X[best_idx:best_idx + 1]

rng = np.random.default_rng(SEED)

lower = X.min(axis=0)
upper = X.max(axis=0)

# Very focused local search around best point
local_best = rng.normal(loc=best_x, scale=LOCAL_RADIUS, size=(N_LOCAL_BEST, 2))

# Small local search around other strong points
local_top = []
n_per_top = max(50, N_LOCAL_TOP // len(top_points))
for pt in top_points:
    local = rng.normal(loc=pt, scale=LOCAL_RADIUS * 1.1, size=(n_per_top, 2))
    local_top.append(local)
local_top = np.vstack(local_top)

# Small global component
global_candidates = rng.uniform(lower, upper, size=(N_GLOBAL, 2))

# Combine and clip
candidates = np.vstack([local_best, local_top, global_candidates])
candidates = np.clip(candidates, lower, upper)

dist_to_existing = np.sqrt(((candidates[:, None, :] - X[None, :, :]) ** 2).sum(axis=2))
min_dist_existing = dist_to_existing.min(axis=1)

mask = min_dist_existing > MIN_SEP
candidates = candidates[mask]
min_dist_existing = min_dist_existing[mask]

print("Candidates after filtering:", candidates.shape[0])

# Exploitation: closeness to best point
dist_to_best = np.linalg.norm(candidates - best_x, axis=1)
exploit_score = 1 - dist_to_best / (dist_to_best.max() + 1e-12)

# Exploration: novelty relative to previous points
explore_score = min_dist_existing / (min_dist_existing.max() + 1e-12)

# Combined score
score = EXPLOIT_WEIGHT * exploit_score + EXPLORE_WEIGHT * explore_score

top_k_idx = np.argsort(score)[-TOP_K:]
shortlist = candidates[top_k_idx]
shortlist_score = score[top_k_idx]
shortlist_explore = explore_score[top_k_idx]

# Small novelty bonus inside the shortlist
final_score = shortlist_score + 0.03 * shortlist_explore
next_query = shortlist[np.argmax(final_score)]


query_string = "-".join([f"{v:0.6f}" for v in next_query])

print("Next query:")
print(query_string)

Dataset shape: (18, 2)
Best value so far: 50.543040584470276
Best point so far: [0.701759 0.877518]
Top attention points: 3
Candidates after filtering: 6348
Next query:
0.707782-0.869530


In [10]:
#WEEK 10

new_data_point = np.array([[0.707782, 0.869530]])
Combined_input_data10 = np.concatenate((Combined_input_data9, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_1/W10_inputs.npy", Combined_input_data10)
print(Combined_input_data10)

new_output_data_point = np.array([-3.731754298794736e-45])
Combined_output_data10 = np.concatenate((Combined_output_data9, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_1/W10_outputs.npy", Combined_output_data10)

print(Combined_output_data10)

[[0.66579958 0.12396913]
 [0.87779099 0.7786275 ]
 [0.14269907 0.34900513]
 [0.84527543 0.71112027]
 [0.45464714 0.29045518]
 [0.57771284 0.77197318]
 [0.43816606 0.68501826]
 [0.34174959 0.02869772]
 [0.33864816 0.21386725]
 [0.70263656 0.9265642 ]
 [0.14597    0.921486  ]
 [0.652719   0.877025  ]
 [0.751452   0.87691   ]
 [0.701759   0.877518  ]
 [0.701759   0.877518  ]
 [0.538921   0.302247  ]
 [0.700409   0.758584  ]
 [0.680043   0.819023  ]
 [0.707782   0.86953   ]]
[ 5.38996119e-01  4.20586240e-01 -6.56236244e-02  2.93992912e-01
  2.14964510e-01  2.31055498e-02  2.44619344e-01  3.87490152e-02
 -1.38576181e-02  6.11205216e-01  5.12835000e-02  4.38220570e-01
  5.64844479e-01  5.43040584e-01  5.05430406e+01 -2.69937094e-23
 -4.14105781e-16 -1.92220488e-28 -3.73175430e-45]


In [ ]:
#WEEK 10

X = Combined_input_data10
y = Combined_output_data10

best_idx = np.argmax(y)
best_x = X[best_idx]

lower = X.min(axis=0)
upper = X.max(axis=0)

step = 0.02
candidates = []

# axis-wise local moves
for dx1 in [-step, 0, step]:
    for dx2 in [-step, 0, step]:
        if dx1 == 0 and dx2 == 0:
            continue
        pt = best_x + np.array([dx1, dx2])
        pt = np.clip(pt, lower, upper)
        candidates.append(pt)

candidates = np.array(candidates)

# prefer points not too close to old samples
dist = np.sqrt(((candidates[:, None, :] - X[None, :, :]) ** 2).sum(axis=2))
min_dist = dist.min(axis=1)

next_query = candidates[np.argmax(min_dist)]
query_string = "-".join([f"{v:0.6f}" for v in next_query])
print(query_string)

0.681759-0.857518


In [12]:
#WEEK 11

new_data_point = np.array([[0.681759, 0.857518]])
Combined_input_data11 = np.concatenate((Combined_input_data10, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_1/W11_inputs.npy", Combined_input_data11)
print(Combined_input_data11)

new_output_data_point = np.array([4.059692681921214e-39])
Combined_output_data11 = np.concatenate((Combined_output_data10, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_1/W11_outputs.npy", Combined_output_data11)

print(Combined_output_data11)

[[0.66579958 0.12396913]
 [0.87779099 0.7786275 ]
 [0.14269907 0.34900513]
 [0.84527543 0.71112027]
 [0.45464714 0.29045518]
 [0.57771284 0.77197318]
 [0.43816606 0.68501826]
 [0.34174959 0.02869772]
 [0.33864816 0.21386725]
 [0.70263656 0.9265642 ]
 [0.14597    0.921486  ]
 [0.652719   0.877025  ]
 [0.751452   0.87691   ]
 [0.701759   0.877518  ]
 [0.701759   0.877518  ]
 [0.538921   0.302247  ]
 [0.700409   0.758584  ]
 [0.680043   0.819023  ]
 [0.707782   0.86953   ]
 [0.681759   0.857518  ]]
[ 5.38996119e-01  4.20586240e-01 -6.56236244e-02  2.93992912e-01
  2.14964510e-01  2.31055498e-02  2.44619344e-01  3.87490152e-02
 -1.38576181e-02  6.11205216e-01  5.12835000e-02  4.38220570e-01
  5.64844479e-01  5.43040584e-01  5.05430406e+01 -2.69937094e-23
 -4.14105781e-16 -1.92220488e-28 -3.73175430e-45  4.05969268e-39]


In [ ]:
#WEEK 11
from sklearn.cluster import KMeans

X = Combined_input_data11
y = Combined_output_data11

threshold = np.quantile(y, 0.80)
top_X = X[y >= threshold]

k = min(2, len(top_X))
kmeans = KMeans(n_clusters=k, random_state=11, n_init=10)
labels = kmeans.fit_predict(top_X)

# Choose cluster with highest mean output
best_cluster = None
best_mean = -np.inf
for c in range(k):
    cluster_points = top_X[labels == c]
    cluster_y = y[y >= threshold][labels == c]
    if cluster_y.mean() > best_mean:
        best_mean = cluster_y.mean()
        best_cluster = cluster_points

centroid = best_cluster.mean(axis=0)

# Move slightly outward from centroid toward farthest point in cluster
dists = np.linalg.norm(best_cluster - centroid, axis=1)
edge_point = best_cluster[np.argmax(dists)]
direction = edge_point - centroid
direction = direction / (np.linalg.norm(direction) + 1e-12)

next_query = centroid + 0.02 * direction
next_query = np.clip(next_query, X.min(axis=0), X.max(axis=0))

print("-".join([f"{v:0.6f}" for v in next_query]))

0.702409-0.913864


In [14]:
#WEEK 12

new_data_point = np.array([[0.702409, 0.913864]])
Combined_input_data12 = np.concatenate((Combined_input_data11, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_1/W12_inputs.npy", Combined_input_data12)
print(Combined_input_data12)

new_output_data_point = np.array([-3.4690341835368425e-61])
Combined_output_data12 = np.concatenate((Combined_output_data11, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_1/W12_outputs.npy", Combined_output_data12)

print(Combined_output_data12)

[[0.66579958 0.12396913]
 [0.87779099 0.7786275 ]
 [0.14269907 0.34900513]
 [0.84527543 0.71112027]
 [0.45464714 0.29045518]
 [0.57771284 0.77197318]
 [0.43816606 0.68501826]
 [0.34174959 0.02869772]
 [0.33864816 0.21386725]
 [0.70263656 0.9265642 ]
 [0.14597    0.921486  ]
 [0.652719   0.877025  ]
 [0.751452   0.87691   ]
 [0.701759   0.877518  ]
 [0.701759   0.877518  ]
 [0.538921   0.302247  ]
 [0.700409   0.758584  ]
 [0.680043   0.819023  ]
 [0.707782   0.86953   ]
 [0.681759   0.857518  ]
 [0.702409   0.913864  ]]
[ 5.38996119e-01  4.20586240e-01 -6.56236244e-02  2.93992912e-01
  2.14964510e-01  2.31055498e-02  2.44619344e-01  3.87490152e-02
 -1.38576181e-02  6.11205216e-01  5.12835000e-02  4.38220570e-01
  5.64844479e-01  5.43040584e-01  5.05430406e+01 -2.69937094e-23
 -4.14105781e-16 -1.92220488e-28 -3.73175430e-45  4.05969268e-39
 -3.46903418e-61]


In [ ]:
#WEEK 12
from sklearn.decomposition import PCA

X = Combined_input_data12
y = Combined_output_data12

threshold = np.quantile(y, 0.80)
top_X = X[y >= threshold]

best_x = X[np.argmax(y)]
lower = X.min(axis=0)
upper = X.max(axis=0)

# PCA on top-performing points
pca = PCA(n_components=2)
pca.fit(top_X)
pc1 = pca.components_[0]

rng = np.random.default_rng(121)
n_candidates = 3000

# mostly along first principal direction, small perpendicular noise
steps = rng.normal(0.02, 0.01, size=(n_candidates, 1))
noise = rng.normal(0, 0.01, size=(n_candidates, 2))
candidates = best_x + steps * pc1 + noise
candidates = np.clip(candidates, lower, upper)

# avoid duplicates
dist = np.sqrt(((candidates[:, None, :] - X[None, :, :])**2).sum(axis=2))
min_dist = dist.min(axis=1)

score = min_dist
next_query = candidates[np.argmax(score)]

print("-".join([f"{v:0.6f}" for v in next_query]))

0.663790-0.925433


In [17]:
#WEEK 13

new_data_point = np.array([[0.663790, 0.925433]])
Combined_input_data13 = np.concatenate((Combined_input_data12, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_1/W13_inputs.npy", Combined_input_data13)
print(Combined_input_data13)

new_output_data_point = np.array([1.9016713583789546e-63])
Combined_output_data13 = np.concatenate((Combined_output_data12, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_1/W13_outputs.npy", Combined_output_data13)

print(Combined_output_data13)

[[0.66579958 0.12396913]
 [0.87779099 0.7786275 ]
 [0.14269907 0.34900513]
 [0.84527543 0.71112027]
 [0.45464714 0.29045518]
 [0.57771284 0.77197318]
 [0.43816606 0.68501826]
 [0.34174959 0.02869772]
 [0.33864816 0.21386725]
 [0.70263656 0.9265642 ]
 [0.14597    0.921486  ]
 [0.652719   0.877025  ]
 [0.751452   0.87691   ]
 [0.701759   0.877518  ]
 [0.701759   0.877518  ]
 [0.538921   0.302247  ]
 [0.700409   0.758584  ]
 [0.680043   0.819023  ]
 [0.707782   0.86953   ]
 [0.681759   0.857518  ]
 [0.702409   0.913864  ]
 [0.66379    0.925433  ]]
[ 5.38996119e-01  4.20586240e-01 -6.56236244e-02  2.93992912e-01
  2.14964510e-01  2.31055498e-02  2.44619344e-01  3.87490152e-02
 -1.38576181e-02  6.11205216e-01  5.12835000e-02  4.38220570e-01
  5.64844479e-01  5.43040584e-01  5.05430406e+01 -2.69937094e-23
 -4.14105781e-16 -1.92220488e-28 -3.73175430e-45  4.05969268e-39
 -3.46903418e-61  1.90167136e-63]


In [ ]:
#WEEK 13

X = Combined_input_data13
y = Combined_output_data13

best_x = X[np.argmax(y)]
lower = X.min(axis=0)
upper = X.max(axis=0)

# Treat top region as a "high-value arm"
threshold = np.quantile(y, 0.85)
top_X = X[y >= threshold]
top_y = y[y >= threshold]

k = min(2, len(top_X))
kmeans = KMeans(n_clusters=k, random_state=101, n_init=10)
labels = kmeans.fit_predict(top_X)

best_cluster = None
best_score = -np.inf

for c in range(k):
    cluster_points = top_X[labels == c]
    cluster_y = top_y[labels == c]
    score = cluster_y.mean()
    if score > best_score:
        best_score = score
        best_cluster = cluster_points

centroid = best_cluster.mean(axis=0)

# Greedy move: between centroid and best point
next_query = 0.6 * best_x + 0.4 * centroid
next_query = np.clip(next_query, lower, upper)

print("-".join([f"{v:0.6f}" for v in next_query]))

0.701876-0.884057
