In [1]:
#Load packages required for loading the npy files.
import numpy as np
import pandas as pd

# #Load the npy file called "data.npy"
Initial_input_data = np.load("/Users/mayukotakamiya/MachineLearning/initial_data/function_4/initial_inputs.npy")
Initial_output_data = np.load("/Users/mayukotakamiya/MachineLearning/initial_data/function_4/initial_outputs.npy")

#I want to know dimentionality of the initial_input_data  
Initial_input_data.shape




(30, 4)

In [2]:

# X and y already loaded
X = Initial_input_data
y = Initial_output_data

def propose_next_point(X, y, n_candidates=8000, w_exploit=0.6, w_explore=0.4, seed=42):
    """
    Simple explore/exploit heuristic:
    - exploit: sample near best observed point
    - explore: sample far from existing samples
    """

    rng = np.random.default_rng(seed)
    n, d = X.shape

    # Best observed point so far
    best_x = X[np.argmax(y)]

    # Determine sampling bounds from existing data
    lower_bounds = X.min(axis=0)
    upper_bounds = X.max(axis=0)

    # Generate random candidate points within observed bounds
    C = rng.uniform(lower_bounds, upper_bounds, size=(n_candidates, d))

    # Exploitation term (closer to best is better)
    dist_to_best = np.linalg.norm(C - best_x, axis=1)
    exploit = 1 - (dist_to_best / (dist_to_best.max() + 1e-12))

    # Exploration term (farther from existing points is better)
    dists = np.sqrt(((C[:, None, :] - X[None, :, :]) ** 2).sum(axis=2))
    min_dist = dists.min(axis=1)
    explore = min_dist / (min_dist.max() + 1e-12)

    # Combined score
    score = w_exploit * exploit + w_explore * explore

    return C[np.argmax(score)]

def format_query(x):
    return "-".join([f"{v:0.6f}" for v in x])

# Generate next query
next_x = propose_next_point(X, y)

print("Submit this to the portal:")
print(format_query(next_x))

Submit this to the portal:
0.145970-0.921486


In [2]:
###WEEK 2
#I want to see the data in /Users/mayukotakamiya/MachineLearning/initial_data/function_1/initial_inputs.npy
print(Initial_input_data)
#I WANT TO create a new npy file by adding a new data point which is [0.433534 0.458467]
new_data_point = np.array([[0.917607, 0.386844, 0.045430, 0.13895]])
Combined_input_data = np.concatenate((Initial_input_data, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_4/W2_inputs.npy", Combined_input_data)
print(Combined_input_data)

[[0.89698105 0.72562797 0.17540431 0.70169437]
 [0.8893564  0.49958786 0.53926886 0.50878344]
 [0.25094624 0.03369313 0.14538002 0.49493242]
 [0.34696206 0.0062504  0.76056361 0.61302356]
 [0.12487118 0.12977019 0.38440048 0.2870761 ]
 [0.80130271 0.50023109 0.70664456 0.19510284]
 [0.24770826 0.06044543 0.04218635 0.44132425]
 [0.74670224 0.7570915  0.36935306 0.20656628]
 [0.40066503 0.07257425 0.88676825 0.24384229]
 [0.6260706  0.58675126 0.43880578 0.77885769]
 [0.95713529 0.59764438 0.76611385 0.77620991]
 [0.73281243 0.14524998 0.47681272 0.13336573]
 [0.65511548 0.07239183 0.68715175 0.08151656]
 [0.21973443 0.83203134 0.48286416 0.08256923]
 [0.48859419 0.2119651  0.93917791 0.37619173]
 [0.16713049 0.87655456 0.21723954 0.95980098]
 [0.21691119 0.16608583 0.24137226 0.77006248]
 [0.38748784 0.80453226 0.75179548 0.72382744]
 [0.98562189 0.66693268 0.15678328 0.8565348 ]
 [0.03782483 0.66485335 0.16198218 0.25392378]
 [0.68348638 0.9027701  0.33541983 0.99948256]
 [0.17034731 

In [3]:
print(Initial_output_data)

#I want to create a new npy file bt adding a new data point to the Initial_output_data
new_output_data_point = np.array([-21.287725631313773])
Combined_output_data = np.concatenate((Initial_output_data, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_4/W2_outputs.npy", Combined_output_data)

print(Combined_output_data)

[-22.10828779 -14.60139663 -11.69993246 -16.05376511 -10.06963343
 -15.48708254 -12.68168498 -16.02639977 -17.04923465 -12.74176599
 -27.31639636 -13.52764887 -16.6791152  -16.50715856 -17.81799934
 -26.56182083 -12.75832422 -19.44155762 -28.90327367 -13.70274694
 -29.4270914  -11.56574199 -26.85778644  -7.96677535  -6.70208925
 -32.62566022 -19.98949793  -4.02554228 -13.12278233 -23.1394284 ]
[-22.10828779 -14.60139663 -11.69993246 -16.05376511 -10.06963343
 -15.48708254 -12.68168498 -16.02639977 -17.04923465 -12.74176599
 -27.31639636 -13.52764887 -16.6791152  -16.50715856 -17.81799934
 -26.56182083 -12.75832422 -19.44155762 -28.90327367 -13.70274694
 -29.4270914  -11.56574199 -26.85778644  -7.96677535  -6.70208925
 -32.62566022 -19.98949793  -4.02554228 -13.12278233 -23.1394284
 -21.28772563]


In [87]:
#Assess the exploitation vs exploration strategy
x=Combined_input_data
y=Combined_output_data

best_score_w2= np.max(y)
improvement= best_score_w2 - np.max(Initial_output_data)

print("Improvement:", improvement)
print("Output range:", y.min(), "to", y.max())
print("Std deviation:", np.std(y))


Improvement: 0.007087524491951498
Output range: -0.0036060626443634764 to 0.007087524491952269
Std deviation: 0.002376682573738607


In [ ]:
##Function1- For week2, it seems there is a big improvement by having the improvement more than 10% of the output range. Therefore, more exploitation than exploration.
##Function2- For week2, no improvement at all. Therefore use more exploration than exploitation
##Function3- for week2, no improvement at all.Therefore use more exploration than exploitation. 
##Function4- for week2, no improvement at all.Therefore use more exploration than exploitation. 
##Function5- for week2, no improvement at all.Therefore use more exploration than exploitation. 
##Function6- for week2, no improvement at all.Therefore use more exploration than exploitation. 
##Function7- for week2, no improvement at all.Therefore use more exploration than exploitation. 
#Function8- for week2, there is small-moderate improvement. Take a balanced approach (6:4)

In [88]:
#Re-run the loop
X=Combined_input_data
y=Combined_output_data

def propose_next_point(X, y, n_candidates=8000, w_exploit=0.75, w_explore=0.25, seed=234):
    """
    Simple explore/exploit heuristic:
    - exploit: sample near best observed point
    - explore: sample far from existing samples
    """

    rng = np.random.default_rng(seed)
    n, d = X.shape

    # Best observed point so far
    best_x = X[np.argmax(y)]
    
    radius = 0.05  # small local refinement

    # Determine sampling bounds from existing data
    lower = np.maximum(best_x - radius, X.min(axis=0))
    upper = np.minimum(best_x + radius, X.max(axis=0))


    # Generate random candidate points within observed bounds
    C = rng.uniform(lower, upper, size=(n_candidates, d))

    # Exploitation term (closer to best is better)
    dist_to_best = np.linalg.norm(C - best_x, axis=1)
    exploit = 1 - (dist_to_best / (dist_to_best.max() + 1e-12))

    # Exploration term (farther from existing points is better)
    dists = np.sqrt(((C[:, None, :] - X[None, :, :]) ** 2).sum(axis=2))
    min_dist = dists.min(axis=1)
    explore = min_dist / (min_dist.max() + 1e-12)

    # Combined score
    score = w_exploit * exploit + w_explore * explore

    return C[np.argmax(score)]

def format_query(x):
    return "-".join([f"{v:0.6f}" for v in x])

# Generate next query
next_x = propose_next_point(X, y)

print("Submit this to the portal:")
print(format_query(next_x))

Submit this to the portal:
0.433582-0.457940


In [4]:
####WEEK 3
new_data_point = np.array([[0.528859, 0.470383, 0.377902, 0.199357]])
Combined_input_data3 = np.concatenate((Combined_input_data, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_4/W3_inputs.npy", Combined_input_data3)
print(Combined_input_data3)

new_output_data_point = np.array([-5.085343912467263])
Combined_output_data3 = np.concatenate((Combined_output_data, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_4/W3_outputs.npy", Combined_output_data3)

print(Combined_output_data3)


[[0.89698105 0.72562797 0.17540431 0.70169437]
 [0.8893564  0.49958786 0.53926886 0.50878344]
 [0.25094624 0.03369313 0.14538002 0.49493242]
 [0.34696206 0.0062504  0.76056361 0.61302356]
 [0.12487118 0.12977019 0.38440048 0.2870761 ]
 [0.80130271 0.50023109 0.70664456 0.19510284]
 [0.24770826 0.06044543 0.04218635 0.44132425]
 [0.74670224 0.7570915  0.36935306 0.20656628]
 [0.40066503 0.07257425 0.88676825 0.24384229]
 [0.6260706  0.58675126 0.43880578 0.77885769]
 [0.95713529 0.59764438 0.76611385 0.77620991]
 [0.73281243 0.14524998 0.47681272 0.13336573]
 [0.65511548 0.07239183 0.68715175 0.08151656]
 [0.21973443 0.83203134 0.48286416 0.08256923]
 [0.48859419 0.2119651  0.93917791 0.37619173]
 [0.16713049 0.87655456 0.21723954 0.95980098]
 [0.21691119 0.16608583 0.24137226 0.77006248]
 [0.38748784 0.80453226 0.75179548 0.72382744]
 [0.98562189 0.66693268 0.15678328 0.8565348 ]
 [0.03782483 0.66485335 0.16198218 0.25392378]
 [0.68348638 0.9027701  0.33541983 0.99948256]
 [0.17034731 

In [5]:
#WEEK 3 Assess the exploitation vs exploration strategy
x=Combined_input_data3
y=Combined_output_data3

best_score_w2= np.max(y)
improvement= best_score_w2 - np.max(Combined_output_data)

print("Improvement:", improvement)
print("Output range:", y.min(), "to", y.max())
print("Std deviation:", np.std(y))

Improvement: 0.0
Output range: -32.625660215962455 to -4.025542281908162
Std deviation: 7.158054790991586


In [6]:
#WEEK 3 -re run the loop. no ate improvement so adjust exploit vs explore ratio to 0.6: 0.4
X=Combined_input_data3
y=Combined_output_data3

def propose_next_point(X, y, n_candidates=8000, w_exploit=0.45, w_explore=0.55, seed=234):

    rng = np.random.default_rng(seed)
    n, d = X.shape

    # Best observed point so far
    best_x = X[np.argmax(y)]
    
    radius = 0.05  # small local refinement

    # Determine sampling bounds from existing data
    lower = np.maximum(best_x - radius, X.min(axis=0))
    upper = np.minimum(best_x + radius, X.max(axis=0))


    # Generate random candidate points within observed bounds
    C = rng.uniform(lower, upper, size=(n_candidates, d))

    # Exploitation term (closer to best is better)
    dist_to_best = np.linalg.norm(C - best_x, axis=1)
    exploit = 1 - (dist_to_best / (dist_to_best.max() + 1e-12))

    # Exploration term (farther from existing points is better)
    dists = np.sqrt(((C[:, None, :] - X[None, :, :]) ** 2).sum(axis=2))
    min_dist = dists.min(axis=1)
    explore = min_dist / (min_dist.max() + 1e-12)

    # Combined score
    score = w_exploit * exploit + w_explore * explore

    return C[np.argmax(score)]

def format_query(x):
    return "-".join([f"{v:0.6f}" for v in x])

# Generate next query
next_x = propose_next_point(X, y)

print("Submit this to the portal:")
print(format_query(next_x))

Submit this to the portal:
0.535315-0.475877-0.379563-0.298824


In [7]:
####WEEK 4
new_data_point = np.array([[0.535315, 0.475877, 0.379563, 0.298824]])
Combined_input_data4 = np.concatenate((Combined_input_data3, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_4/W4_inputs.npy", Combined_input_data4)
print(Combined_input_data4)

new_output_data_point = np.array([-3.731919875089353])
Combined_output_data4 = np.concatenate((Combined_output_data3, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_4/W4_outputs.npy", Combined_output_data4)

print(Combined_output_data4)

[[0.89698105 0.72562797 0.17540431 0.70169437]
 [0.8893564  0.49958786 0.53926886 0.50878344]
 [0.25094624 0.03369313 0.14538002 0.49493242]
 [0.34696206 0.0062504  0.76056361 0.61302356]
 [0.12487118 0.12977019 0.38440048 0.2870761 ]
 [0.80130271 0.50023109 0.70664456 0.19510284]
 [0.24770826 0.06044543 0.04218635 0.44132425]
 [0.74670224 0.7570915  0.36935306 0.20656628]
 [0.40066503 0.07257425 0.88676825 0.24384229]
 [0.6260706  0.58675126 0.43880578 0.77885769]
 [0.95713529 0.59764438 0.76611385 0.77620991]
 [0.73281243 0.14524998 0.47681272 0.13336573]
 [0.65511548 0.07239183 0.68715175 0.08151656]
 [0.21973443 0.83203134 0.48286416 0.08256923]
 [0.48859419 0.2119651  0.93917791 0.37619173]
 [0.16713049 0.87655456 0.21723954 0.95980098]
 [0.21691119 0.16608583 0.24137226 0.77006248]
 [0.38748784 0.80453226 0.75179548 0.72382744]
 [0.98562189 0.66693268 0.15678328 0.8565348 ]
 [0.03782483 0.66485335 0.16198218 0.25392378]
 [0.68348638 0.9027701  0.33541983 0.99948256]
 [0.17034731 

In [ ]:
##WEEK 4 - neural-network surrogate + candidate search
# import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPRegressor

X = Combined_input_data4   
y = Combined_output_data4  

print("Dataset shape:", X.shape)

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

model = MLPRegressor(
    hidden_layer_sizes=(16, 8),  # small network
    activation="relu",
    solver="adam",
    max_iter=2000,
    random_state=42
)

model.fit(X_scaled, y)

rng = np.random.default_rng(42)

lower = X.min(axis=0)
upper = X.max(axis=0)

n_candidates = 8000

candidates = rng.uniform(lower, upper, size=(n_candidates, X.shape[1]))

dist = np.sqrt(((candidates[:, None, :] - X[None, :, :]) ** 2).sum(axis=2))
min_dist = dist.min(axis=1)

mask = min_dist > 0.01
candidates = candidates[mask]

candidates_scaled = scaler.transform(candidates)

predictions = model.predict(candidates_scaled)

best_idx = np.argmax(predictions)

next_query = candidates[best_idx]

query_string = "-".join([f"{v:0.6f}" for v in next_query])

print("Next query:")
print(query_string)

Dataset shape: (33, 4)
Next query:
0.518538-0.405371-0.346910-0.310848


/Users/mayukotakamiya/miniforge3/envs/tf-metal/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (2000) reached and the optimization hasn't converged yet.
  warnings.warn(


In [9]:
#WEEK 5 
new_data_point = np.array([[0.518538, 0.405371, 0.346910, 0.310848]])
Combined_input_data5 = np.concatenate((Combined_input_data4, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_4/W5_inputs.npy", Combined_input_data5)
print(Combined_input_data5)

new_output_data_point = np.array([-1.906457262166167])
Combined_output_data5 = np.concatenate((Combined_output_data4, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_4/W5_outputs.npy", Combined_output_data5)

print(Combined_output_data5)

[[0.89698105 0.72562797 0.17540431 0.70169437]
 [0.8893564  0.49958786 0.53926886 0.50878344]
 [0.25094624 0.03369313 0.14538002 0.49493242]
 [0.34696206 0.0062504  0.76056361 0.61302356]
 [0.12487118 0.12977019 0.38440048 0.2870761 ]
 [0.80130271 0.50023109 0.70664456 0.19510284]
 [0.24770826 0.06044543 0.04218635 0.44132425]
 [0.74670224 0.7570915  0.36935306 0.20656628]
 [0.40066503 0.07257425 0.88676825 0.24384229]
 [0.6260706  0.58675126 0.43880578 0.77885769]
 [0.95713529 0.59764438 0.76611385 0.77620991]
 [0.73281243 0.14524998 0.47681272 0.13336573]
 [0.65511548 0.07239183 0.68715175 0.08151656]
 [0.21973443 0.83203134 0.48286416 0.08256923]
 [0.48859419 0.2119651  0.93917791 0.37619173]
 [0.16713049 0.87655456 0.21723954 0.95980098]
 [0.21691119 0.16608583 0.24137226 0.77006248]
 [0.38748784 0.80453226 0.75179548 0.72382744]
 [0.98562189 0.66693268 0.15678328 0.8565348 ]
 [0.03782483 0.66485335 0.16198218 0.25392378]
 [0.68348638 0.9027701  0.33541983 0.99948256]
 [0.17034731 

In [ ]:
##WEEK 5- Use a neural network surrogate, Slightly increase model capacity, Combine: local refinement (around best point), global exploration, Add diversity + exploration bonus

X = Combined_input_data5
y = Combined_output_data5

print("Dataset shape:", X.shape)

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

model = MLPRegressor(
    hidden_layer_sizes=(24, 12),   # slightly deeper than Function 3
    activation="relu",
    solver="adam",
    max_iter=2500,
    random_state=42
)

model.fit(X_scaled, y)

best_idx = np.argmax(y)
best_x = X[best_idx]

print("Best value:", y[best_idx])

rng = np.random.default_rng(42)

lower = X.min(axis=0)
upper = X.max(axis=0)

# Local candidates (refinement)
local_candidates = rng.normal(loc=best_x, scale=0.04, size=(4000, 4))
local_candidates = np.clip(local_candidates, lower, upper)

# Global candidates (exploration)
global_candidates = rng.uniform(lower, upper, size=(4000, 4))

# Combine
candidates = np.vstack([local_candidates, global_candidates])

dist = np.sqrt(((candidates[:, None, :] - X[None, :, :])**2).sum(axis=2))
min_dist = dist.min(axis=1)

mask = min_dist > 0.01
candidates = candidates[mask]
min_dist = min_dist[mask]

candidates_scaled = scaler.transform(candidates)
predictions = model.predict(candidates_scaled)

explore_score = min_dist / (min_dist.max() + 1e-12)

# Balanced scoring (slightly exploit-leaning)
score = predictions + 0.1 * explore_score

next_query = candidates[np.argmax(score)]

query_string = "-".join([f"{v:0.6f}" for v in next_query])

print("Next query:")
print(query_string)

Dataset shape: (34, 4)
Best value: -1.906457262166167
Next query:
0.450748-0.410078-0.369322-0.328472


In [11]:
#WEEK 6
new_data_point = np.array([[0.518538, 0.405371, 0.346910, 0.310848]])
Combined_input_data6 = np.concatenate((Combined_input_data5, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_4/W6_inputs.npy", Combined_input_data6)
print(Combined_input_data6)

new_output_data_point = np.array([-1.906457262166167])
Combined_output_data6 = np.concatenate((Combined_output_data5, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/initial_data/function_4/W6_outputs.npy", Combined_output_data6)

print(Combined_output_data6)

[[0.89698105 0.72562797 0.17540431 0.70169437]
 [0.8893564  0.49958786 0.53926886 0.50878344]
 [0.25094624 0.03369313 0.14538002 0.49493242]
 [0.34696206 0.0062504  0.76056361 0.61302356]
 [0.12487118 0.12977019 0.38440048 0.2870761 ]
 [0.80130271 0.50023109 0.70664456 0.19510284]
 [0.24770826 0.06044543 0.04218635 0.44132425]
 [0.74670224 0.7570915  0.36935306 0.20656628]
 [0.40066503 0.07257425 0.88676825 0.24384229]
 [0.6260706  0.58675126 0.43880578 0.77885769]
 [0.95713529 0.59764438 0.76611385 0.77620991]
 [0.73281243 0.14524998 0.47681272 0.13336573]
 [0.65511548 0.07239183 0.68715175 0.08151656]
 [0.21973443 0.83203134 0.48286416 0.08256923]
 [0.48859419 0.2119651  0.93917791 0.37619173]
 [0.16713049 0.87655456 0.21723954 0.95980098]
 [0.21691119 0.16608583 0.24137226 0.77006248]
 [0.38748784 0.80453226 0.75179548 0.72382744]
 [0.98562189 0.66693268 0.15678328 0.8565348 ]
 [0.03782483 0.66485335 0.16198218 0.25392378]
 [0.68348638 0.9027701  0.33541983 0.99948256]
 [0.17034731 

In [ ]:
##WEEK 6 
#Use a moderately expressive neural network
#Combine:
#local refinement (around best point)
#global exploration
#Maintain balanced scoring
#Avoid overfitting (limited data)

X = Combined_input_data6
y = Combined_output_data6

print("Dataset shape:", X.shape)

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

model = MLPRegressor(
    hidden_layer_sizes=(24, 12),   # moderate depth
    activation="relu",
    solver="adam",
    alpha=1e-3,                    # regularisation
    max_iter=3000,
    random_state=42
)

model.fit(X_scaled, y)

best_idx = np.argmax(y)
best_x = X[best_idx]

print("Best value:", y[best_idx])

rng = np.random.default_rng(123)

lower = X.min(axis=0)
upper = X.max(axis=0)

# Local refinement
local_candidates = rng.normal(loc=best_x, scale=0.04, size=(4000, 4))
local_candidates = np.clip(local_candidates, lower, upper)

# Global exploration
global_candidates = rng.uniform(lower, upper, size=(4000, 4))

# Combine candidates
candidates = np.vstack([local_candidates, global_candidates])

dist = np.sqrt(((candidates[:, None, :] - X[None, :, :])**2).sum(axis=2))
min_dist = dist.min(axis=1)

mask = min_dist > 0.01
candidates = candidates[mask]
min_dist = min_dist[mask]

candidates_scaled = scaler.transform(candidates)
predictions = model.predict(candidates_scaled)

explore_score = min_dist / (min_dist.max() + 1e-12)

# Balanced approach
score = predictions + 0.10 * explore_score

next_query = candidates[np.argmax(score)]

query_string = "-".join([f"{v:0.6f}" for v in next_query])

print("Next query:")
print(query_string)

Dataset shape: (35, 4)
Best value: -1.906457262166167
Next query:
0.496807-0.402115-0.353326-0.329238


In [ ]:
#WEEK 7
Combined_input_data6 = np.load("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_4/W6_inputs.npy")
Combined_output_data6 = np.load("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_4/W6_outputs.npy")

new_data_point = np.array([[0.496807, 0.402115, 0.353326, 0.329238]])
Combined_input_data7 = np.concatenate((Combined_input_data6, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_4/W7_inputs.npy", Combined_input_data7)
print(Combined_input_data7)

new_output_data_point = np.array([-1.25309521899587])
Combined_output_data7 = np.concatenate((Combined_output_data6, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_4/W7_outputs.npy", Combined_output_data7)

print(Combined_output_data7)

[[0.89698105 0.72562797 0.17540431 0.70169437]
 [0.8893564  0.49958786 0.53926886 0.50878344]
 [0.25094624 0.03369313 0.14538002 0.49493242]
 [0.34696206 0.0062504  0.76056361 0.61302356]
 [0.12487118 0.12977019 0.38440048 0.2870761 ]
 [0.80130271 0.50023109 0.70664456 0.19510284]
 [0.24770826 0.06044543 0.04218635 0.44132425]
 [0.74670224 0.7570915  0.36935306 0.20656628]
 [0.40066503 0.07257425 0.88676825 0.24384229]
 [0.6260706  0.58675126 0.43880578 0.77885769]
 [0.95713529 0.59764438 0.76611385 0.77620991]
 [0.73281243 0.14524998 0.47681272 0.13336573]
 [0.65511548 0.07239183 0.68715175 0.08151656]
 [0.21973443 0.83203134 0.48286416 0.08256923]
 [0.48859419 0.2119651  0.93917791 0.37619173]
 [0.16713049 0.87655456 0.21723954 0.95980098]
 [0.21691119 0.16608583 0.24137226 0.77006248]
 [0.38748784 0.80453226 0.75179548 0.72382744]
 [0.98562189 0.66693268 0.15678328 0.8565348 ]
 [0.03782483 0.66485335 0.16198218 0.25392378]
 [0.68348638 0.9027701  0.33541983 0.99948256]
 [0.17034731 

In [ ]:
#WEEK 7

X = Combined_input_data7
y = Combined_output_data7

print("Dataset shape:", X.shape)


HIDDEN_LAYERS = (24, 12)   # moderate NN
ALPHA = 1e-3               # regularisation
LOCAL_RADIUS = 0.035
N_LOCAL = 5000
N_GLOBAL = 3000
MIN_SEP = 0.01
EXPLORE_BONUS = 0.10
SEED = 321
MAX_ITER = 3500

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)


model = MLPRegressor(
    hidden_layer_sizes=HIDDEN_LAYERS,
    activation="relu",
    solver="adam",
    alpha=ALPHA,
    max_iter=MAX_ITER,
    random_state=SEED
)

model.fit(X_scaled, y)

best_idx = np.argmax(y)
best_x = X[best_idx]
best_y = y[best_idx]

print("Best value so far:", best_y)
print("Best point so far:", best_x)

rng = np.random.default_rng(SEED)

lower = X.min(axis=0)
upper = X.max(axis=0)

# Local refinement around best point
local_candidates = rng.normal(loc=best_x, scale=LOCAL_RADIUS, size=(N_LOCAL, 4))
local_candidates = np.clip(local_candidates, lower, upper)

# Global exploration
global_candidates = rng.uniform(lower, upper, size=(N_GLOBAL, 4))

# Combine candidates
candidates = np.vstack([local_candidates, global_candidates])

dist_to_existing = np.sqrt(((candidates[:, None, :] - X[None, :, :]) ** 2).sum(axis=2))
min_dist_existing = dist_to_existing.min(axis=1)

mask = min_dist_existing > MIN_SEP
candidates = candidates[mask]
min_dist_existing = min_dist_existing[mask]

print("Candidates after filtering:", candidates.shape[0])

candidates_scaled = scaler.transform(candidates)
predictions = model.predict(candidates_scaled)

explore_score = min_dist_existing / (min_dist_existing.max() + 1e-12)
score = predictions + EXPLORE_BONUS * explore_score

next_query = candidates[np.argmax(score)]

query_string = "-".join([f"{v:0.6f}" for v in next_query])

print("Next query:")
print(query_string)

Dataset shape: (36, 4)
Best value so far: -1.25309521899587
Best point so far: [0.496807 0.402115 0.353326 0.329238]
Candidates after filtering: 7995
Next query:
0.503319-0.415419-0.409806-0.342233


In [3]:
#WEEK 8

new_data_point = np.array([[0.503319, 0.415419, 0.409806, 0.342233]])
Combined_input_data8 = np.concatenate((Combined_input_data7, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_4/W8_inputs.npy", Combined_input_data8)
print(Combined_input_data8)

new_output_data_point = np.array([-1.0537557945238478])
Combined_output_data8 = np.concatenate((Combined_output_data7, new_output_data_point), axis=0)
Combined_output_data8 = np.concatenate((Combined_output_data7, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_4/W8_outputs.npy", Combined_output_data8)

print(Combined_output_data8)

[[0.89698105 0.72562797 0.17540431 0.70169437]
 [0.8893564  0.49958786 0.53926886 0.50878344]
 [0.25094624 0.03369313 0.14538002 0.49493242]
 [0.34696206 0.0062504  0.76056361 0.61302356]
 [0.12487118 0.12977019 0.38440048 0.2870761 ]
 [0.80130271 0.50023109 0.70664456 0.19510284]
 [0.24770826 0.06044543 0.04218635 0.44132425]
 [0.74670224 0.7570915  0.36935306 0.20656628]
 [0.40066503 0.07257425 0.88676825 0.24384229]
 [0.6260706  0.58675126 0.43880578 0.77885769]
 [0.95713529 0.59764438 0.76611385 0.77620991]
 [0.73281243 0.14524998 0.47681272 0.13336573]
 [0.65511548 0.07239183 0.68715175 0.08151656]
 [0.21973443 0.83203134 0.48286416 0.08256923]
 [0.48859419 0.2119651  0.93917791 0.37619173]
 [0.16713049 0.87655456 0.21723954 0.95980098]
 [0.21691119 0.16608583 0.24137226 0.77006248]
 [0.38748784 0.80453226 0.75179548 0.72382744]
 [0.98562189 0.66693268 0.15678328 0.8565348 ]
 [0.03782483 0.66485335 0.16198218 0.25392378]
 [0.68348638 0.9027701  0.33541983 0.99948256]
 [0.17034731 

In [ ]:
#week 8

X = Combined_input_data8
y = Combined_output_data8

print("Dataset shape:", X.shape)

HIDDEN_LAYERS = (24, 12)
ALPHA = 1e-3
LOCAL_RADIUS = 0.032

# candidate budget
N_LOCAL_BEST = 3500
N_LOCAL_TOP = 3000
N_GLOBAL = 3500

# attention + shortlist settings
TOP_QUANTILE = 0.80   # top 20% attention set
TOP_K = 35
EXPLORE_BONUS = 0.10

# near-duplicate protection
MIN_SEP = 0.01

SEED = 456
MAX_ITER = 3500

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)


model = MLPRegressor(
    hidden_layer_sizes=HIDDEN_LAYERS,
    activation="relu",
    solver="adam",
    alpha=ALPHA,
    max_iter=MAX_ITER,
    random_state=SEED
)

model.fit(X_scaled, y)

best_idx = np.argmax(y)
best_x = X[best_idx]
best_y = y[best_idx]

threshold = np.quantile(y, TOP_QUANTILE)
top_points = X[y >= threshold]

print("Best value so far:", best_y)
print("Best point so far:", best_x)
print("Top attention points:", len(top_points))

if len(top_points) == 0:
    top_points = X[best_idx:best_idx + 1]

rng = np.random.default_rng(SEED)

lower = X.min(axis=0)
upper = X.max(axis=0)

# Local around current best
local_best = rng.normal(loc=best_x, scale=LOCAL_RADIUS, size=(N_LOCAL_BEST, 4))

# Local around top-performing region
local_top = []
n_per_top = max(100, N_LOCAL_TOP // len(top_points))
for pt in top_points:
    local = rng.normal(loc=pt, scale=LOCAL_RADIUS * 1.1, size=(n_per_top, 4))
    local_top.append(local)
local_top = np.vstack(local_top)

# Global exploration
global_candidates = rng.uniform(lower, upper, size=(N_GLOBAL, 4))

# Combine and clip
candidates = np.vstack([local_best, local_top, global_candidates])
candidates = np.clip(candidates, lower, upper)

dist_to_existing = np.sqrt(((candidates[:, None, :] - X[None, :, :]) ** 2).sum(axis=2))
min_dist_existing = dist_to_existing.min(axis=1)

mask = min_dist_existing > MIN_SEP
candidates = candidates[mask]
min_dist_existing = min_dist_existing[mask]

print("Candidates after filtering:", candidates.shape[0])

candidates_scaled = scaler.transform(candidates)
predictions = model.predict(candidates_scaled)

explore_score = min_dist_existing / (min_dist_existing.max() + 1e-12)

# Main score: surrogate output + exploration bonus
score = predictions + EXPLORE_BONUS * explore_score

# top-k shortlist
top_k_idx = np.argsort(score)[-TOP_K:]
shortlist = candidates[top_k_idx]
shortlist_score = score[top_k_idx]
shortlist_explore = explore_score[top_k_idx]

# final score slightly rewards diversity among strong candidates
final_score = shortlist_score + 0.05 * shortlist_explore
next_query = shortlist[np.argmax(final_score)]

query_string = "-".join([f"{v:0.6f}" for v in next_query])

print("Next query:")
print(query_string)

Dataset shape: (37, 4)
Best value so far: -1.0537557945238478
Best point so far: [0.503319 0.415419 0.409806 0.342233]
Top attention points: 8
Candidates after filtering: 9989
Next query:
0.503622-0.407393-0.378237-0.342794


In [5]:
#WEEK 9

new_data_point = np.array([[0.503622, 0.407393, 0.378237, 0.342794]])
Combined_input_data9 = np.concatenate((Combined_input_data8, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_4/W9_inputs.npy", Combined_input_data9)
print(Combined_input_data9)

new_output_data_point = np.array([-1.2329842470966912])
Combined_output_data9 = np.concatenate((Combined_output_data8, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_4/W9_outputs.npy", Combined_output_data9)

print(Combined_output_data9)

[[0.89698105 0.72562797 0.17540431 0.70169437]
 [0.8893564  0.49958786 0.53926886 0.50878344]
 [0.25094624 0.03369313 0.14538002 0.49493242]
 [0.34696206 0.0062504  0.76056361 0.61302356]
 [0.12487118 0.12977019 0.38440048 0.2870761 ]
 [0.80130271 0.50023109 0.70664456 0.19510284]
 [0.24770826 0.06044543 0.04218635 0.44132425]
 [0.74670224 0.7570915  0.36935306 0.20656628]
 [0.40066503 0.07257425 0.88676825 0.24384229]
 [0.6260706  0.58675126 0.43880578 0.77885769]
 [0.95713529 0.59764438 0.76611385 0.77620991]
 [0.73281243 0.14524998 0.47681272 0.13336573]
 [0.65511548 0.07239183 0.68715175 0.08151656]
 [0.21973443 0.83203134 0.48286416 0.08256923]
 [0.48859419 0.2119651  0.93917791 0.37619173]
 [0.16713049 0.87655456 0.21723954 0.95980098]
 [0.21691119 0.16608583 0.24137226 0.77006248]
 [0.38748784 0.80453226 0.75179548 0.72382744]
 [0.98562189 0.66693268 0.15678328 0.8565348 ]
 [0.03782483 0.66485335 0.16198218 0.25392378]
 [0.68348638 0.9027701  0.33541983 0.99948256]
 [0.17034731 

In [ ]:
#WEEK 9

X = Combined_input_data9
y = Combined_output_data9

print("Dataset shape:", X.shape)

# Moderate surrogate, now trusted more than before
HIDDEN_LAYERS = (24, 12)
ALPHA = 1e-3
LOCAL_RADIUS = 0.028

# Candidate budget
N_LOCAL_BEST = 4200
N_LOCAL_TOP = 2800
N_GLOBAL = 2200

# More exploitive than Query 8, but still not greedy
TOP_QUANTILE = 0.82   # top 18% attention set
TOP_K = 25
EXPLORE_BONUS = 0.08

# Duplicate protection
MIN_SEP = 0.01

SEED = 789
MAX_ITER = 4000

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)


model = MLPRegressor(
    hidden_layer_sizes=HIDDEN_LAYERS,
    activation="relu",
    solver="adam",
    alpha=ALPHA,
    max_iter=MAX_ITER,
    random_state=SEED
)

model.fit(X_scaled, y)

best_idx = np.argmax(y)
best_x = X[best_idx]
best_y = y[best_idx]

threshold = np.quantile(y, TOP_QUANTILE)
top_points = X[y >= threshold]

print("Best value so far:", best_y)
print("Best point so far:", best_x)
print("Top attention points:", len(top_points))

if len(top_points) == 0:
    top_points = X[best_idx:best_idx + 1]


rng = np.random.default_rng(SEED)

lower = X.min(axis=0)
upper = X.max(axis=0)

# Local search around current best
local_best = rng.normal(loc=best_x, scale=LOCAL_RADIUS, size=(N_LOCAL_BEST, 4))

# Local search around top-performing region
local_top = []
n_per_top = max(80, N_LOCAL_TOP // len(top_points))
for pt in top_points:
    local = rng.normal(loc=pt, scale=LOCAL_RADIUS * 1.08, size=(n_per_top, 4))
    local_top.append(local)
local_top = np.vstack(local_top)

# Global exploration
global_candidates = rng.uniform(lower, upper, size=(N_GLOBAL, 4))

# Combine and clip
candidates = np.vstack([local_best, local_top, global_candidates])
candidates = np.clip(candidates, lower, upper)

dist_to_existing = np.sqrt(((candidates[:, None, :] - X[None, :, :]) ** 2).sum(axis=2))
min_dist_existing = dist_to_existing.min(axis=1)

mask = min_dist_existing > MIN_SEP
candidates = candidates[mask]
min_dist_existing = min_dist_existing[mask]

print("Candidates after filtering:", candidates.shape[0])

candidates_scaled = scaler.transform(candidates)
predictions = model.predict(candidates_scaled)

explore_score = min_dist_existing / (min_dist_existing.max() + 1e-12)

# Surrogate-led score with modest novelty protection
score = predictions + EXPLORE_BONUS * explore_score

top_k_idx = np.argsort(score)[-TOP_K:]
shortlist = candidates[top_k_idx]
shortlist_score = score[top_k_idx]
shortlist_explore = explore_score[top_k_idx]

# Small novelty preference inside the shortlist
final_score = shortlist_score + 0.04 * shortlist_explore
next_query = shortlist[np.argmax(final_score)]


query_string = "-".join([f"{v:0.6f}" for v in next_query])

print("Next query:")
print(query_string)

Dataset shape: (38, 4)
Best value so far: -1.0537557945238478
Best point so far: [0.503319 0.415419 0.409806 0.342233]
Top attention points: 7
Candidates after filtering: 9174
Next query:
0.496407-0.425751-0.372524-0.354886


In [7]:
#WEEK 10

new_data_point = np.array([[0.496407, 0.425751, 0.372524, 0.354886]])
Combined_input_data10 = np.concatenate((Combined_input_data9, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_4/W10_inputs.npy", Combined_input_data10)
print(Combined_input_data10)

new_output_data_point = np.array([-0.9512212422437822])
Combined_output_data10 = np.concatenate((Combined_output_data9, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_4/W10_outputs.npy", Combined_output_data10)

print(Combined_output_data10)

[[0.89698105 0.72562797 0.17540431 0.70169437]
 [0.8893564  0.49958786 0.53926886 0.50878344]
 [0.25094624 0.03369313 0.14538002 0.49493242]
 [0.34696206 0.0062504  0.76056361 0.61302356]
 [0.12487118 0.12977019 0.38440048 0.2870761 ]
 [0.80130271 0.50023109 0.70664456 0.19510284]
 [0.24770826 0.06044543 0.04218635 0.44132425]
 [0.74670224 0.7570915  0.36935306 0.20656628]
 [0.40066503 0.07257425 0.88676825 0.24384229]
 [0.6260706  0.58675126 0.43880578 0.77885769]
 [0.95713529 0.59764438 0.76611385 0.77620991]
 [0.73281243 0.14524998 0.47681272 0.13336573]
 [0.65511548 0.07239183 0.68715175 0.08151656]
 [0.21973443 0.83203134 0.48286416 0.08256923]
 [0.48859419 0.2119651  0.93917791 0.37619173]
 [0.16713049 0.87655456 0.21723954 0.95980098]
 [0.21691119 0.16608583 0.24137226 0.77006248]
 [0.38748784 0.80453226 0.75179548 0.72382744]
 [0.98562189 0.66693268 0.15678328 0.8565348 ]
 [0.03782483 0.66485335 0.16198218 0.25392378]
 [0.68348638 0.9027701  0.33541983 0.99948256]
 [0.17034731 

In [ ]:
#WEEK 10
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Ridge

X = Combined_input_data10
y = Combined_output_data10

model = make_pipeline(StandardScaler(), Ridge(alpha=1.0))
model.fit(X, y)

best_x = X[np.argmax(y)]
lower = X.min(axis=0)
upper = X.max(axis=0)

step = 0.025
candidates = []

for j in range(X.shape[1]):
    for delta in [-step, step]:
        pt = best_x.copy()
        pt[j] += delta
        pt = np.clip(pt, lower, upper)
        candidates.append(pt)

candidates = np.array(candidates)
pred = model.predict(candidates)

dist = np.sqrt(((candidates[:, None, :] - X[None, :, :]) ** 2).sum(axis=2))
min_dist = dist.min(axis=1)

score = pred + 0.05 * (min_dist / (min_dist.max() + 1e-12))
next_query = candidates[np.argmax(score)]

query_string = "-".join([f"{v:0.6f}" for v in next_query])
print(query_string)

ridge = model.named_steps["ridge"]
print("Feature coefficients:", ridge.coef_)

0.496407-0.425751-0.372524-0.329886
Feature coefficients: [-2.55032453 -2.09148604 -0.98380785 -3.52745106]


In [10]:
#WEEK 11

new_data_point = np.array([[0.496407, 0.425751, 0.372524, 0.329886]])
Combined_input_data11 = np.concatenate((Combined_input_data10, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_4/W11_inputs.npy", Combined_input_data11)
print(Combined_input_data11)

new_output_data_point = np.array([-1.2072472026527907])
Combined_output_data11 = np.concatenate((Combined_output_data10, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_4/W11_outputs.npy", Combined_output_data11)

print(Combined_output_data11)

[[0.89698105 0.72562797 0.17540431 0.70169437]
 [0.8893564  0.49958786 0.53926886 0.50878344]
 [0.25094624 0.03369313 0.14538002 0.49493242]
 [0.34696206 0.0062504  0.76056361 0.61302356]
 [0.12487118 0.12977019 0.38440048 0.2870761 ]
 [0.80130271 0.50023109 0.70664456 0.19510284]
 [0.24770826 0.06044543 0.04218635 0.44132425]
 [0.74670224 0.7570915  0.36935306 0.20656628]
 [0.40066503 0.07257425 0.88676825 0.24384229]
 [0.6260706  0.58675126 0.43880578 0.77885769]
 [0.95713529 0.59764438 0.76611385 0.77620991]
 [0.73281243 0.14524998 0.47681272 0.13336573]
 [0.65511548 0.07239183 0.68715175 0.08151656]
 [0.21973443 0.83203134 0.48286416 0.08256923]
 [0.48859419 0.2119651  0.93917791 0.37619173]
 [0.16713049 0.87655456 0.21723954 0.95980098]
 [0.21691119 0.16608583 0.24137226 0.77006248]
 [0.38748784 0.80453226 0.75179548 0.72382744]
 [0.98562189 0.66693268 0.15678328 0.8565348 ]
 [0.03782483 0.66485335 0.16198218 0.25392378]
 [0.68348638 0.9027701  0.33541983 0.99948256]
 [0.17034731 

In [ ]:
#WEEK 11
from sklearn.cluster import KMeans

X = Combined_input_data11
y = Combined_output_data11

kmeans = KMeans(n_clusters=min(4, len(X)), random_state=14, n_init=10)
labels = kmeans.fit_predict(X)

best_cluster = None
best_score = -np.inf

for c in range(labels.max() + 1):
    cluster_points = X[labels == c]
    cluster_y = y[labels == c]
    if len(cluster_points) == 0:
        continue
    score = cluster_y.mean() - 0.1 * cluster_y.std()
    if score > best_score:
        best_score = score
        best_cluster = cluster_points

centroid = best_cluster.mean(axis=0)

rng = np.random.default_rng(14)
candidates = rng.normal(loc=centroid, scale=0.03, size=(3000, X.shape[1]))
candidates = np.clip(candidates, X.min(axis=0), X.max(axis=0))

dist = np.sqrt(((candidates[:, None, :] - X[None, :, :]) ** 2).sum(axis=2))
next_query = candidates[np.argmax(dist.min(axis=1))]

print("-".join([f"{v:0.6f}" for v in next_query]))

0.533383-0.620588-0.354830-0.230760


In [12]:
#WEEK 12

new_data_point = np.array([[0.533383, 0.620588, 0.354830, 0.230760]])
Combined_input_data12 = np.concatenate((Combined_input_data11, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_4/W12_inputs.npy", Combined_input_data12)
print(Combined_input_data12)

new_output_data_point = np.array([-6.251332630304685])
Combined_output_data12 = np.concatenate((Combined_output_data11, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_4/W12_outputs.npy", Combined_output_data12)

print(Combined_output_data12)

[[0.89698105 0.72562797 0.17540431 0.70169437]
 [0.8893564  0.49958786 0.53926886 0.50878344]
 [0.25094624 0.03369313 0.14538002 0.49493242]
 [0.34696206 0.0062504  0.76056361 0.61302356]
 [0.12487118 0.12977019 0.38440048 0.2870761 ]
 [0.80130271 0.50023109 0.70664456 0.19510284]
 [0.24770826 0.06044543 0.04218635 0.44132425]
 [0.74670224 0.7570915  0.36935306 0.20656628]
 [0.40066503 0.07257425 0.88676825 0.24384229]
 [0.6260706  0.58675126 0.43880578 0.77885769]
 [0.95713529 0.59764438 0.76611385 0.77620991]
 [0.73281243 0.14524998 0.47681272 0.13336573]
 [0.65511548 0.07239183 0.68715175 0.08151656]
 [0.21973443 0.83203134 0.48286416 0.08256923]
 [0.48859419 0.2119651  0.93917791 0.37619173]
 [0.16713049 0.87655456 0.21723954 0.95980098]
 [0.21691119 0.16608583 0.24137226 0.77006248]
 [0.38748784 0.80453226 0.75179548 0.72382744]
 [0.98562189 0.66693268 0.15678328 0.8565348 ]
 [0.03782483 0.66485335 0.16198218 0.25392378]
 [0.68348638 0.9027701  0.33541983 0.99948256]
 [0.17034731 

In [ ]:
#WEEK 12

from sklearn.decomposition import PCA


X = Combined_input_data12
y = Combined_output_data12

threshold = np.quantile(y, 0.80)
top_X = X[y >= threshold]

best_x = X[np.argmax(y)]
lower = X.min(axis=0)
upper = X.max(axis=0)

pca = PCA(n_components=2)
pca.fit(top_X)
pc1, pc2 = pca.components_

model = make_pipeline(StandardScaler(), Ridge(alpha=1.0))
model.fit(X, y)

rng = np.random.default_rng(124)
n_candidates = 6000

a = rng.normal(0, 0.025, size=(n_candidates, 1))
b = rng.normal(0, 0.015, size=(n_candidates, 1))
noise = rng.normal(0, 0.008, size=(n_candidates, 4))

candidates = best_x + a * pc1 + b * pc2 + noise
candidates = np.clip(candidates, lower, upper)

pred = model.predict(candidates)
dist = np.sqrt(((candidates[:, None, :] - X[None, :, :])**2).sum(axis=2))
min_dist = dist.min(axis=1)

score = pred + 0.07 * (min_dist / (min_dist.max() + 1e-12))
next_query = candidates[np.argmax(score)]

print("-".join([f"{v:0.6f}" for v in next_query]))

0.505131-0.403462-0.355030-0.304056


In [14]:
#WEEK 13

new_data_point = np.array([[0.505131, 0.403462, 0.355030, 0.304056]])
Combined_input_data13 = np.concatenate((Combined_input_data12, new_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_4/W13_inputs.npy", Combined_input_data13)
print(Combined_input_data13)

new_output_data_point = np.array([-1.9849893341256144])
Combined_output_data13 = np.concatenate((Combined_output_data12, new_output_data_point), axis=0)
np.save("/Users/mayukotakamiya/MachineLearning/ML-capstone-project/function_4/W13_outputs.npy", Combined_output_data13)

print(Combined_output_data13)

[[0.89698105 0.72562797 0.17540431 0.70169437]
 [0.8893564  0.49958786 0.53926886 0.50878344]
 [0.25094624 0.03369313 0.14538002 0.49493242]
 [0.34696206 0.0062504  0.76056361 0.61302356]
 [0.12487118 0.12977019 0.38440048 0.2870761 ]
 [0.80130271 0.50023109 0.70664456 0.19510284]
 [0.24770826 0.06044543 0.04218635 0.44132425]
 [0.74670224 0.7570915  0.36935306 0.20656628]
 [0.40066503 0.07257425 0.88676825 0.24384229]
 [0.6260706  0.58675126 0.43880578 0.77885769]
 [0.95713529 0.59764438 0.76611385 0.77620991]
 [0.73281243 0.14524998 0.47681272 0.13336573]
 [0.65511548 0.07239183 0.68715175 0.08151656]
 [0.21973443 0.83203134 0.48286416 0.08256923]
 [0.48859419 0.2119651  0.93917791 0.37619173]
 [0.16713049 0.87655456 0.21723954 0.95980098]
 [0.21691119 0.16608583 0.24137226 0.77006248]
 [0.38748784 0.80453226 0.75179548 0.72382744]
 [0.98562189 0.66693268 0.15678328 0.8565348 ]
 [0.03782483 0.66485335 0.16198218 0.25392378]
 [0.68348638 0.9027701  0.33541983 0.99948256]
 [0.17034731 

In [ ]:
#WEEK 13

X = Combined_input_data13
y = Combined_output_data13

lower = X.min(axis=0)
upper = X.max(axis=0)

# Region = arm
kmeans = KMeans(n_clusters=min(4, len(X)), random_state=104, n_init=10)
labels = kmeans.fit_predict(X)

best_cluster = None
best_score = -np.inf

for c in range(labels.max() + 1):
    cluster_points = X[labels == c]
    cluster_y = y[labels == c]
    score = cluster_y.mean()  # expected reward
    if score > best_score:
        best_score = score
        best_cluster = cluster_points

centroid = best_cluster.mean(axis=0)

model = make_pipeline(StandardScaler(), Ridge(alpha=1.0))
model.fit(X, y)

rng = np.random.default_rng(104)
candidates = rng.normal(loc=centroid, scale=0.025, size=(4000, X.shape[1]))
candidates = np.clip(candidates, lower, upper)

pred = model.predict(candidates)
dist = np.sqrt(((candidates[:, None, :] - X[None, :, :])**2).sum(axis=2))
min_dist = dist.min(axis=1)

score = pred + 0.04 * (min_dist / (min_dist.max() + 1e-12))
next_query = candidates[np.argmax(score)]

print("-".join([f"{v:0.6f}" for v in next_query]))

0.491128-0.419641-0.445521-0.152225
